<?php
$warehouse_id = '';
if ($adjustStockProducts = Mage::getModel('admin/session')->getData('physicalstocktaking_product_warehouse')) {
    $warehouse_id = $adjustStockProducts['warehouse_id'];
}
if ($this->getRequest()->getParam('id')) {
    $id = $this->getRequest()->getParam('id');
    $physical = Mage::getModel('inventoryphysicalstocktaking/physicalstocktaking')->load($id);
    $warehouse_id = $physical->getWarehouseId();
}
$warehouse = Mage::getModel('inventoryplus/warehouse')->load($warehouse_id);
$permission = Mage::helper('inventoryplus')->getPermission($warehouse_id, 'can_physical');
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Physical Stocktaking Information') ?></h4>
    </div>
    <div id="adjuststock_form" class="fieldset ">
        <input name="warehouse_id" type="hidden" value="<?php echo $warehouse_id ?>" id="warehouse_id"/>
        <div style='float:left; width:30%;'>
            <div>
                <label for="warehouse"><strong>
                        <?php echo $this->__('Warehouse') ?>:&nbsp;&nbsp;
                    </strong>
                </label>
                <a href="<?php echo $this->getUrl('inventoryplusadmin/adminhtml_warehouse/edit', array('id' => $warehouse_id)) ?>" title="<?php $this->__('View warehouse') ?>">
                    <?php echo $warehouse->getWarehouseName() ?>
                </a>
            </div><br />
            <div>
                <?php echo $warehouse->getStreet() ?>
                <?php if ($warehouse->getState()): ?>
                    <?php echo ' - ' . $warehouse->getState() ?>
                <?php endif ?>
                <?php if ($warehouse->getCity()): ?>
                    <?php echo ' - ' . $warehouse->getCity() ?><br />
                <?php endif ?>
                <?php echo Mage::getModel('directory/country')->load($warehouse->getCountryId())->getName() ?>
            </div>  
        </div>
        <div style="float:left;width: 60%;">
            <?php if ($this->getRequest()->getParam('id')): ?>
                <?php $id = $this->getRequest()->getParam('id') ?>
                <?php $adjustStock = Mage::getModel('inventoryphysicalstocktaking/physicalstocktaking')->load($id) ?>
                <?php $helper = Mage::helper('inventoryphysicalstocktaking'); ?>
                <label for="warehouse"><?php echo '<strong>' . $this->__('Status: ') . '</strong>' . $helper->getStatusPhysicalLabel($adjustStock->getStatus()); ?></label>
                <br />
                <label for="warehouse"><?php echo '<strong>' . $this->__('Created by: ') . '</strong>' . $adjustStock->getCreateBy() ?></label>
                <br />
                <?php $date = new Zend_Date(); ?>
                <?php $date->setLocale(Mage::app()->getLocale()->getLocaleCode()); ?>
                <?php $date_adjust = $date->setDate($adjustStock->getCreatedAt(), 'yyyy/MM/dd'); ?>
                <label for="warehouse"><?php echo '<strong>' . $this->__('Created on: ') . '</strong>' . Mage::helper('core')->formatDate($date_adjust, 'medium'); ?></label>
                <br /><br />
            <?php endif ?>

            <label for="warehouse"><strong><?php echo $this->__('Reason(s) for stocktaking') ?><?php if ($this->getRequest()->getParam('id')) echo ':' ?><?php echo ' ' ?></strong>
                <?php if (!$this->getRequest()->getParam('id')): ?>
                    <span class="required">*</span>
                <?php endif; ?>
            </label>
            <br />
            <?php if ((!$permission && $this->getRequest()->getParam('id')) || ($this->getRequest()->getParam('id') && $adjustStock->getStatus() != 0)): ?>
                <div style="width:700px;float:left">
                    <?php echo nl2br($adjustStock->getReason()) ?>
                </div>
            <?php else: ?>
                <textarea id="reason" name="reason" title="Reason(s) to adjust stock" style="width:350px; height:50px;" rows="2" cols="15" class="required-entry  textarea"> <?php
                    if ($this->getRequest()->getParam('id')) {
                        echo nl2br($adjustStock->getReason());
                    }
                    ?></textarea>

            <?php endif ?>
        </div>
        <div class="clear"></div>
    </div>
</div>
<?php if (!$this->getRequest()->getParam('id') || ($this->getRequest()->getParam('id') && $physical->getStatus() == 0)): ?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Import Products from CSV file') ?></h4>
        </div>
        <div id="adjuststock_form" class="fieldset ">
            <?php //import product form   ?>
            <div style="float:left;width: 30%;">
                <div>
                    <label for="fileToUpload">
                        <?php echo $this->__('Please choose a CSV file to import') ?>
                    </label><br />
                    <input style="width: 200px;" type="file" name="fileToUpload[]" id="fileToUpload" onchange="fileSelected();" enctype="multipart/form-data"/>
                    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" id="form_key"/>
                    <button style="" onclick="uploadFile()" class="scalable task" type="button" id="Upload"><span><?php echo $this->__('Import') ?></span></button>
                </div>
                <div class="clear"></div>
                <div id="fileName">
                </div>
                <div id="fileSize">
                </div>
                <div id="fileType">
                </div>
                <div id="progressNumber">
                </div>
            </div>
            <div id="messages" style="float: left;padding-left: 20px;width:60%;">
                <ul class="messages">
                    <li class="notice-msg">
                        <ul>
                            <li>
                                <?php echo $this->__('"If you want to import a physical stocktaking for loads of products in a warehouse, the structure of CSV file is as follows:') ?><br />                                                                       
                                <?php $example = "SKU: SKU of product counted<br />" ?>                                   
                                <?php $example .= "QTY: Quantity of product counted<br />" ?>                                                                  
                                <?php echo "<h3><b>SKU,QTY</b></h3>" ?>
                                <div style="padding-left: 20px;" ?>
                                    <?php echo $example ?>
                                </div>
                            </li>
                            <li>
                                <div style="float:left;">
                                    <b><?php echo $this->__('Example file') ?> (<a href="<?php echo Mage::getBaseUrl('media') . 'inventory/csv/import_product_to_physicalstocktaking.csv'; ?>"><?php echo $this->__('Download') ?></a>)</b>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
    </div>
<?php endif; ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">
            <?php if ($this->getRequest()->getParam('id')): ?>
                <?php echo $this->__('Products of Physical Stocktaking') ?>
            <?php else: ?>
                <?php echo $this->__('Product for Physical Stocktaking') ?> 
            <?php endif ?>
        </h4>
    </div>
</div>