<?php $id = $this->getIdBox() ?>
<?php $chart = Mage::getModel('inventorydashboard/items')->load($id) ?>
<?php     
    $resource = Mage::getSingleton('core/resource');        
    $readConnection = $resource->getConnection('core_read');
    $results = '';
    $sql = 'SELECT `warehouse_id`,sum(`qty_shipped`) as `total_shipped` FROM '.$resource->getTableName('erp_inventory_warehouse_shipment').' group by `warehouse_id`';     
    $results = $readConnection->query($sql);
    $warehouseShipment = array();
    if($results){
        foreach($results as $result){            
            $warehouseShipment[$result['warehouse_id']] = $result['total_shipped'];
        }
    }
    $warehouseCollection = Mage::getModel('inventoryplus/warehouse')->getCollection();
    $series = '';
    $i = 0;    
    foreach($warehouseCollection as $warehouse){
        $qtyShipped = 0;
        if(isset($warehouseShipment[$warehouse->getId()]))
            $qtyShipped = $warehouseShipment[$warehouse->getId()];
        if($i!=0)
            $series .= ',';
        $series .= '[\''.$warehouse->getWarehouseName().'('.$qtyShipped.' items)\','.$qtyShipped.']';
        $i++;
    }
?>
<div class="chart-parent-div">
<script type="text/javascript">
$(function () {
    $_('#<?php echo $id ?>').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: 1,//null,
            plotShadow: false
        },
        title: {
            text: '<?php echo $chart->getName() ?>',
            x: -20 //center
        },        
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f} %</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                }
            }
        },
        series: [{
            type: 'pie',
            name: '<?php echo $this->__('Warehouse Shipment') ?>',
            data: [                
                <?php echo $series ?>
            ]
        }]
    });
});
</script>


<div id="<?php echo $id ?>" class="chart-child-div"></div>
</div>