<?php
    $series = array();
    $id = $this->getIdBox();
    $requestData = Mage::helper('adminhtml')->prepareFilterString($this->getRequest()->getParam('top_filter'));
    $reportCode = $this->getReportCode();
    if(empty($requestData)){
        $requestData = array();
        $resource = Mage::getSingleton('core/resource');
        $readConnection = $resource->getConnection('core_read');
        $installer = Mage::getModel('core/resource');
        $sql = 'SELECT default_time_range
        FROM '.$installer->getTableName("erp_inventory_dashboard_report_type").'
        WHERE report_code = "'.$reportCode.'"';
        $results = $readConnection->fetchAll($sql);
        $requestData['report_radio_select'] = $reportCode;
        foreach($results as $time){$requestData['select_time'] = $time['default_time_range'];}
        $requestData['warehouse_select'] = "0";
    }
    $name = 'All Warehouses';
    if($requestData['warehouse_select'] > 0){
        $name = Mage::helper('inventoryreports')->getWarehouseName($requestData['warehouse_select']);
        $display = 0;
    }else{
        $display = 1;
    }
    $gettime = Mage::Helper('inventoryreports')->getTimeSelected($requestData);
    $warehouse_name = array();
    $total_order = array();
    $resource = Mage::getSingleton('core/resource');
    $readConnection = $resource->getConnection('core_read');
    $installer = Mage::getModel('core/resource');
    if(isset($requestData['warehouse_select']) && $requestData['warehouse_select'] > 0){
        $warehouse_collection = Mage::getModel('inventoryplus/warehouse')->load($requestData['warehouse_select']);
        $sql = 'SELECT COUNT(DISTINCT s.order_id) AS total_order, s.warehouse_name
            FROM '.$installer->getTableName("erp_inventory_warehouse_shipment s").'
            INNER JOIN '.$installer->getTableName("sales_flat_order o").'
            WHERE s.warehouse_id > 0 AND s.order_id = o.entity_id AND s.warehouse_name = "'.$warehouse_collection->getWarehouseName().'" AND o.created_at BETWEEN "'.$gettime['date_from'].'" AND "'.$gettime['date_to'].'"
            ';
    }
    else{
        $sql = 'SELECT COUNT(DISTINCT s.order_id) AS total_order, s.warehouse_name
                FROM '.$installer->getTableName("erp_inventory_warehouse_shipment s").'
                INNER JOIN '.$installer->getTableName("sales_flat_order o").'
                WHERE s.warehouse_id > 0 AND s.order_id = o.entity_id AND o.created_at BETWEEN "'.$gettime['date_from'].'" AND "'.$gettime['date_to'].'"
                GROUP BY s.warehouse_id
                ORDER BY COUNT(DISTINCT s.order_id)'
            ;
    }
    $results = $readConnection->fetchAll($sql);
    if(isset($requestData['warehouse_select']) && $requestData['warehouse_select'] > 0){
        $checkResult = 0;
        foreach($results as $result){
            if($checkResult > 10){
                $limit = 10;
                break;
            }
            if($result['total_order'] == NULL || $result['total_order'] <= 0){
                $limit = $checkResult;
                continue;
            }
            $checkResult++;
        } 
        if(isset($limit)){
            $sql .= 'LIMIT '.$limit.'';
            $results = $readConnection->fetchAll($sql);
        }
    }
    foreach ($results as $result) {
        $warehouse_name[]   =   $result['warehouse_name'];
        $total_order[]     =   $result['total_order'];
    }
    $i = 0;
    $categories = '[';
    foreach ($warehouse_name as $name_value) {
            if ($i != 0) {
                $categories .= ',';
            }
            $categories .= '"' . $name_value . '"';
            $i++;
        }
    $categories .= ']';    
//            Zend_debug::dump($categories);
    $j=0;
    $series['inventory_warehouse']['data'] = '[';    
    foreach($total_order as $number_value){
            if ($j != 0) {
                $series['inventory_warehouse']['data'] .= ',';
            }
            $series['inventory_warehouse']['data'] .= $number_value;
            $j++;
    }
    $series['inventory_warehouse']['data'] .= ']';
//            Zend_debug::dump($series);    
?>

            <!-- report by warehouse pie -->
            <div class="chart-parent-div">
                <?php
                $series = '';
                $i = 0;
                foreach ($results as $result) {
                    if ($i != 0)
                        $series .= ',';
                    $series .= '[\'' . $result['warehouse_name'] . '(' . $result['total_order'] . ' orders)\',' . $result['total_order'] . ']';
                    $i++;
                } 
                ?>
                
<script type="text/javascript">
    $(function () {
    $_('#<?php echo $id?>').highcharts({
    chart: {
        type: 'pie',
        options3d: {
            enabled: true,
            alpha: 50
        }
    },
    title: {
        text: '<?php echo $this->__('No. of Orders by Warehouse: "'.$name.'"') ?>',
    },
    plotOptions: {
        pie: {
            depth: 30
        }
    },
    series: [{
        data: [
            <?php echo $series;?>
        ]
    }]
    });
    });
</script>
                
                <div id="<?php echo $id?>" class="chart-child-div" ></div>
            </div><!--End pie-->