<?php
    $series = array();
    $id = $this->getIdBox();
    $requestData = Mage::helper('adminhtml')->prepareFilterString($this->getRequest()->getParam('top_filter'));
    $reportCode = $this->getReportCode();
    if(empty($requestData)){
        $requestData = array();
        $resource = Mage::getSingleton('core/resource');
        $readConnection = $resource->getConnection('core_read');
        $installer = Mage::getModel('core/resource');
        $sql = 'SELECT default_time_range
        FROM '.$installer->getTableName("erp_inventory_dashboard_report_type").'
        WHERE report_code = "'.$reportCode.'"';
        $results = $readConnection->fetchAll($sql);
        $requestData['report_radio_select'] = $reportCode;
        foreach($results as $time){$requestData['select_time'] = $time['default_time_range'];}
        $requestData['warehouse_select'] = "0";
    }
    $gettime = Mage::Helper('inventoryreports')->getTimeSelected($requestData);
    $name = 'All Warehouses';
    if($requestData['warehouse_select'] > 0){
        $name = Mage::helper('inventoryreports')->getWarehouseName($requestData['warehouse_select']);
    }
    $warehouse = Mage::helper('inventoryreports')->getWarehouseName($requestData['warehouse_select']);
    $warehouse_name = array();
    $total_send = array();
    $resource = Mage::getSingleton('core/resource');
    $readConnection = $resource->getConnection('core_read');
    $installer = Mage::getModel('core/resource');
    $is_warehouse = 0;
    if(isset($requestData['warehouse_select']) && $requestData['warehouse_select'] > 0){
        $is_warehouse = 1;
        $warehouse_collection = Mage::getModel('inventoryplus/warehouse')->load($requestData['warehouse_select']);
        $sql = 'SELECT s.warehouse_id_from, s.warehouse_name_from, s.warehouse_name_to, p.product_id, p.product_name, SUM(p.qty) AS total_send, s.created_at
                FROM '.$installer->getTableName("erp_inventory_warehouse_sendstock s").'
                INNER JOIN '.$installer->getTableName("erp_inventory_warehouse_sendstock_product p").'
                ON s.warehouse_sendstock_id = p.warehouse_sendstock_id
                WHERE s.created_at BETWEEN "'.$gettime['date_from'].'" AND "'.$gettime['date_to'].'" AND s.warehouse_name_from = "'.$warehouse_collection->getWarehouseName().'" 
                GROUP BY p.product_id
                ORDER BY SUM(p.qty)';
    }
    else{
        $is_warehouse = 0;
        $sql = 'SELECT warehouse_name_from, SUM(total_products) AS total_send 
                FROM `erp_inventory_warehouse_sendstock` 
                WHERE created_at BETWEEN "'.$gettime['date_from'].'" AND "'.$gettime['date_to'].'"
                GROUP BY warehouse_name_from
                ORDER BY SUM(total_products)';
    }
    $results = $readConnection->fetchAll($sql);
    if(isset($requestData['warehouse_select']) && $requestData['warehouse_select'] > 0){
        $checkResult = 0;
        foreach($results as $result){
            if($checkResult > 10){
                $limit = 10;
                break;
            }
            if($result['total_send'] == NULL){
                $limit = $checkResult;
                continue;
            }
            $checkResult++;
        } 
        if(isset($limit)){
            $sql .= 'LIMIT '.$limit.'';
            $results = $readConnection->fetchAll($sql);
        }
    }
    if($is_warehouse == '1'){
        foreach ($results as $result) {
        $warehouse_name[]   =   $result['product_name'];
        $total_send[]     =   ((int)$result['total_send']*(-1));
        }
    }
    else{
    foreach ($results as $result) {
        $warehouse_name[]   =   $result['warehouse_name_from'];
        $total_send[]     =   ((int)$result['total_send']*(-1));
    }
    }
    $i = 0;
    $categories = '[';
    foreach ($warehouse_name as $name_value) {
            if ($i != 0) {
                $categories .= ',';
            }
            $categories .= '"' . $name_value . '"';
            $i++;
        }
    $categories .= ']';    
//            Zend_debug::dump($categories);
    $j=0;
    $series['inventory_warehouse']['data'] = '[';    
    foreach($total_send as $number_value){
            if ($j != 0) {
                $series['inventory_warehouse']['data'] .= ',';
            }
            $series['inventory_warehouse']['data'] .= $number_value;
            $j++;
    }
    $series['inventory_warehouse']['data'] .= ']'; 
//            Zend_debug::dump($series);
?>
<?php
    $series = '';
    $i = 0;
    foreach ($results as $result) {
        if ($i != 0)
            $series .= ',';
        if($is_warehouse == '1'){
            $series .= '[\'' . $result['product_name'] . '(' . ((int)$result['total_send']*(-1)) . ' items sent)\',' . ((int)$result['total_send']*(-1)) . ']';
        }
        else{
            $series .= '[\'' . $result['warehouse_name_from'] . '(' . ((int)$result['total_send']*(-1)) . ' items sent)\',' . ((int)$result['total_send']*(-1)) . ']';
        }
        $i++;
    }
?>
            <!-- report by warehouse pie -->
<div class="chart-parent-div">
    <script type="text/javascript">
        $(function () {
        $_('#<?php echo $id?>').highcharts({
        chart: {
            type: 'pie',
            options3d: {
                enabled: true,
                alpha: 50
            }
        },
        title: {
            text: '<?php echo $this->__('Total Qty Sent by Warehouse:: "'.$name.'"') ?>',
        },
        plotOptions: {
            pie: {
                depth: 30
            }
        },
        series: [{
            data: [
                <?php echo $series;?>
            ]
        }]
        });
        });
    </script>
    <div id="<?php echo $id?>" class="chart-child-div" ></div>
</div>