<?php
$series = array();
$product_name = array();
$total_remain = array();
$id = $this->getIdBox();
$requestData = Mage::helper('adminhtml')->prepareFilterString($this->getRequest()->getParam('top_filter'));
$reportCode = $this->getReportCode();
if (empty($requestData)) {
    $requestData = array();
    $resource = Mage::getSingleton('core/resource');
    $readConnection = $resource->getConnection('core_read');
    $installer = Mage::getModel('core/resource');
    $sql = 'SELECT default_time_range
        FROM ' . $installer->getTableName("erp_inventory_dashboard_report_type") . '
        WHERE report_code = "' . $reportCode . '"';
    $results = $readConnection->fetchAll($sql);
    $requestData['report_radio_select'] = $reportCode;
    foreach ($results as $time) {
        $requestData['select_time'] = $time['default_time_range'];
    }
}
$gettime = Mage::Helper('inventoryreports')->getTimeSelected($requestData);
$resource = Mage::getSingleton('core/resource');
$readConnection = $resource->getConnection('core_read');
$installer = Mage::getModel('core/resource');

$sql = 'SELECT f.name, SUM(w.total_qty) AS total_remain
    FROM ' . $installer->getTableName("erp_inventory_warehouse_product") . ' w
    INNER JOIN ' . $installer->getTableName("catalog_product_flat_1") . ' f
    ON w.product_id = f.entity_id
    WHERE w.created_at BETWEEN "' . $gettime['date_from'] . '" AND "' . $gettime['date_to'] . '"
    GROUP BY w.product_id
    ORDER BY total_remain DESC
    ';

$results = $readConnection->fetchAll($sql);
if (isset($results)) {
    $checkResult = 0;
    foreach ($results as $result) {
        if ($checkResult > 7) {
            $limit = 7;
            break;
        }
        if ($result['total_remain'] == NULL || $result['total_remain'] <= 0) {
            $limit = $checkResult;
            continue;
        }
        $checkResult++;
    }
    if (isset($limit)) {
        $sql .= 'LIMIT ' . $limit . '';
        $results = $readConnection->fetchAll($sql);
    }
}
?>
<?php
unset($series);
foreach ($results as $result) {
    $product_name[] = $result['name'];
    $total_remain[] = ((int) $result['total_remain']);
}
$i = 0;
$categories = '[';
foreach ($product_name as $name_value) {
    if ($i != 0) {
        $categories .= ',';
    }
    $categories .= '"' . $name_value . '"';
    $i++;
}
$categories .= ']';
//            Zend_debug::dump($categories);
$j = 0;
$series['inventory_product']['data'] = '[';
foreach ($total_remain as $number_value) {
    if ($j != 0) {
        $series['inventory_product']['data'] .= ',';
    }
    $series['inventory_product']['data'] .= $number_value;
    $j++;
}
$series['inventory_product']['data'] .= ']';
//            Zend_debug::dump($series);
?>
<div class="chart-parent-div">
    <script type="text/javascript">
        $(function () {
            $_('#<?php echo $id ?>').highcharts({
            chart: {
            type: 'column',
                    margin: 70,
                    options3d: {
                    enabled: true,
                            alpha: 20,
                            beta: 1,
                            depth: 50
                    }
            },
                    title: {
                    text: '<?php echo $this->__('Qty. Remaining by Product') ?>'
                    },
                    legend: {
                    enabled:false
                    },
                    plotOptions: {
                    column: {
                    depth: 30
                    }
                    },
                    xAxis: {
                    categories: <?php echo $categories ?>
                    },
                    yAxis: {
                    opposite: true
                    },
                    series: [
<?php $count = 0; ?>
<?php foreach ($series as $serie): ?>
    <?php if (!$count == 0) echo ','; ?>
    <?php $count++; ?>
                        {
                            name: '<?php echo $serie['name']; ?>',
                                    data: <?php echo $serie['data']; ?>
                            }
<?php endforeach; ?>
                        ]
            }
            );
        });
    </script>
    <div class="chart-child-div" id="<?php echo $id ?>"></div>
</div>