<?php
$requestData = Mage::helper('adminhtml')->prepareFilterString($this->getRequest()->getParam('top_filter'));
$reportCode = $this->getReportCode();
$id_box = $this->getIdBox();
if (empty($requestData)) {
    $requestData = array();
    $resource = Mage::getSingleton('core/resource');
    $readConnection = $resource->getConnection('core_read');
    $installer = Mage::getModel('core/resource');
    $sql = 'SELECT default_time_range
    FROM ' . $installer->getTableName("erp_inventory_dashboard_report_type") . '
    WHERE report_code = "' . $reportCode . '"';
    $results = $readConnection->fetchAll($sql);
    $requestData['report_radio_select'] = $reportCode;
    foreach ($results as $time) {
        $requestData['select_time'] = $time['default_time_range'];
    }
}
$dataCollection = Mage::helper('inventoryreports/order')->getOrderReportCollection($requestData);
if (is_array($dataCollection)) {
    $collection = $dataCollection['collection'];
} else {
    $collection = $dataCollection;
}
?>
<?php if (count($collection) > 0): ?>
    <div class="chart-parent-div">
        <?php
        $columnData = Mage::helper('inventorydashboard')->getChartColumnData($collection, $requestData);
        $categories = $columnData['categories'];
        $series = $columnData['series'];
        ?>
        <script type="text/javascript">
            $(function () {
            $_('#<?php echo $id_box ?>').highcharts({
            chart: {
            type: 'column',
                    margin: 70,
                    options3d: {
                    enabled: true,
                            alpha: 20,
                            beta: 1,
                            depth: 50
                    }
            },
                    title: {
                    text: '<?php echo $this->__('Sales Report By Day of Week') ?>'
                    },
                    legend: {
                    enabled:false
                    },
                    plotOptions: {
                    column: {
                    depth: 30
                    }
                    },
                    xAxis: {
                    categories: <?php echo $categories ?>
                    },
                    yAxis: {
                    opposite: true
                    },
                    series: [
    <?php $count = 0; ?>
    <?php foreach ($series as $serie): ?>
        <?php if (!$count == 0) echo ','; ?>
        <?php $count++; ?>
                        {
                        name: '<?php echo $serie['name']; ?>',
                                data: <?php echo $serie['data']; ?>
                        }
    <?php endforeach; ?>
                    ]
            }
            );
            });
        </script>
        <div class="chart-child-div" id="<?php echo $id_box ?>"></div>
    </div>
<?php endif; ?>