<?php
$series = array();
$id = $this->getIdBox();
$requestData = Mage::helper('adminhtml')->prepareFilterString($this->getRequest()->getParam('top_filter'));
$reportCode = $this->getReportCode();
if (empty($requestData)) {
    $requestData = array();
    $resource = Mage::getSingleton('core/resource');
    $readConnection = $resource->getConnection('core_read');
    $installer = Mage::getModel('core/resource');
    $sql = 'SELECT default_time_range
        FROM ' . $installer->getTableName("erp_inventory_dashboard_report_type") . '
        WHERE report_code = "' . $reportCode . '"';
    $results = $readConnection->fetchAll($sql);
    $requestData['report_radio_select'] = $reportCode;
    foreach ($results as $time) {
        $requestData['select_time'] = $time['default_time_range'];
    }
    $requestData['warehouse_select'] = "0";
}
$name = 'All Warehouses';
if ($requestData['warehouse_select'] > 0) {
    $name = Mage::helper('inventoryreports')->getWarehouseName($requestData['warehouse_select']);
}
$gettime = Mage::Helper('inventoryreports')->getTimeSelected($requestData);
$warehouse_name = array();
$revenue = array();
$resource = Mage::getSingleton('core/resource');
$readConnection = $resource->getConnection('core_read');
$installer = Mage::getModel('core/resource');
if (isset($requestData['warehouse_select']) && $requestData['warehouse_select'] > 0) {    //Warehouse selected
    $warehouse_collection = Mage::getModel('inventoryplus/warehouse')->load($requestData['warehouse_select']);
    $sql = 'SELECT f.name as warehouse_name, sum(s.subtotal_shipped) as revenue, o.created_at
            FROM ' . $installer->getTableName("erp_inventory_warehouse_shipment s") . '
            INNER JOIN ' . $installer->getTableName("sales_flat_order o") . '
            ON s.order_id = o.entity_id
            INNER JOIN ' . $installer->getTableName("catalog_product_flat_1 f") . '
            ON s.product_id = f.entity_id
            WHERE s.warehouse_id = "' . $requestData['warehouse_select'] . '" AND s.qty_shipped > 0 AND o.created_at BETWEEN "' . $gettime['date_from'] . '" AND "' . $gettime['date_to'] . '"
            GROUP BY s.product_id
            ORDER BY sum(s.subtotal_shipped) DESC
            ';
} else {   //All warehouses     
    $sql = 'SELECT s.warehouse_name, sum(s.subtotal_shipped) as revenue, o.created_at
            FROM ' . $installer->getTableName("erp_inventory_warehouse_shipment s") . '
            INNER JOIN ' . $installer->getTableName("sales_flat_order o") . '
            ON s.order_id = o.entity_id
            WHERE s.qty_shipped > 0 AND o.created_at BETWEEN "' . $gettime['date_from'] . '" AND "' . $gettime['date_to'] . '"
            GROUP BY s.warehouse_name
            ORDER BY sum(s.subtotal_shipped) DESC
            ';
}
$results = $readConnection->fetchAll($sql);
if (isset($requestData['warehouse_select']) && $requestData['warehouse_select'] > 0) {
    $checkResult = 0;
    foreach ($results as $result) {
        if ($checkResult > 10) {
            $limit = 10;
            break;
        }
        if ($result['revenue'] == NULL || $result['revenue'] <= 0) {
            $limit = $checkResult;
            continue;
        }
        $checkResult++;
    }
    if (isset($limit)) {
        $sql .= 'LIMIT ' . $limit . '';
        $results = $readConnection->fetchAll($sql);
    }
}
foreach ($results as $result) {
    $warehouse_name[] = $result['warehouse_name'];
    $revenue[] = round($result['revenue']);
}
//    Zend_Debug::dump($warehouse_name);
$i = 0;
$categories = '[';
foreach ($warehouse_name as $name_value) {
    if ($i != 0) {
        $categories .= ',';
    }
    $categories .= '"' . $name_value . '"';
    $i++;
}
$categories .= ']';
//            Zend_debug::dump($categories);
$j = 0;
$series['inventory_warehouse']['name'] = $this->__('Sales By Warehouse Revenue');
$series['inventory_warehouse']['data'] = '[';
foreach ($revenue as $number_value) {
    if ($j != 0) {
        $series['inventory_warehouse']['data'] .= ',';
    }
    $series['inventory_warehouse']['data'] .= $number_value;
    $j++;
}
$series['inventory_warehouse']['data'] .= ']';
//            Zend_debug::dump($series);    
?>
<div class="chart-parent-div">
    <script type="text/javascript">
        $(function () {
            $_('#<?php echo $id ?>').highcharts({
            chart: {
            type: 'column',
                    margin: 70,
                    options3d: {
                    enabled: true,
                            alpha: 20,
                            beta: 1,
                            depth: 50
                    }
            },
                    title: {
                    text: '<?php echo $this->__('Revenue By Warehouse: "' . $name . '"') ?>'
                    },
                    legend: {
                    enabled:false
                    },
                    plotOptions: {
                    column: {
                    depth: 30
                    }
                    },
                    xAxis: {
                    categories: <?php echo $categories ?>
                    },
                    yAxis: {
                    opposite: true
                    },
                    series: [
<?php $count = 0; ?>
<?php foreach ($series as $serie): ?>
    <?php if (!$count == 0) echo ','; ?>
    <?php $count++; ?>
                        {
                            name: '<?php echo $serie['name']; ?>',
                                    data: <?php echo $serie['data']; ?>
                            }
<?php endforeach; ?>
                        ]
            }
            );
        });
    </script>
    <div class="chart-child-div" id="<?php echo $id ?>" ></div>
</div>