<?php
$series = array();
$id = $this->getIdBox();
$requestData = Mage::helper('adminhtml')->prepareFilterString($this->getRequest()->getParam('top_filter'));
$reportCode = $this->getReportCode();
if (empty($requestData)) {
    $requestData = array();
    $resource = Mage::getSingleton('core/resource');
    $readConnection = $resource->getConnection('core_read');
    $installer = Mage::getModel('core/resource');
    $sql = 'SELECT default_time_range
        FROM ' . $installer->getTableName("erp_inventory_dashboard_report_type") . '
        WHERE report_code = "' . $reportCode . '"';
    $results = $readConnection->fetchAll($sql);
    $requestData['report_radio_select'] = $reportCode;
    foreach ($results as $time) {
        $requestData['select_time'] = $time['default_time_range'];
    }
    $requestData['warehouse_select'] = "0";
}
$name = 'All Warehouses';
if ($requestData['warehouse_select'] > 0) {
    $name = Mage::helper('inventoryreports')->getWarehouseName($requestData['warehouse_select']);
}
$gettime = Mage::Helper('inventoryreports')->getTimeSelected($requestData);
$warehouse_name = array();
$total_request = array();
$resource = Mage::getSingleton('core/resource');
$readConnection = $resource->getConnection('core_read');
$installer = Mage::getModel('core/resource');
$is_warehouse = 0;
if (isset($requestData['warehouse_select']) && $requestData['warehouse_select'] > 0) {
    $is_warehouse = 1;
    $warehouse_collection = Mage::getModel('inventoryplus/warehouse')->load($requestData['warehouse_select']);
    $sql = 'SELECT s.warehouse_id_from, s.warehouse_name_from, s.warehouse_name_to, p.product_id, p.product_name, SUM(p.qty) AS total_request, s.created_at
                FROM ' . $installer->getTableName("erp_inventory_warehouse_requeststock s") . '
                INNER JOIN ' . $installer->getTableName("erp_inventory_warehouse_requeststock_product p") . '
                ON s.warehouse_requeststock_id = p.warehouse_requeststock_id
                WHERE s.created_at BETWEEN "' . $gettime['date_from'] . '" AND "' . $gettime['date_to'] . '" AND s.warehouse_name_from = "' . $warehouse_collection->getWarehouseName() . '"
                GROUP BY p.product_id
                ORDER BY SUM(p.qty) DESC';
} else {
    $is_warehouse = 0;
    $sql = 'SELECT warehouse_name_from, SUM(total_products) AS total_request 
                FROM ' . $installer->getTableName("erp_inventory_warehouse_requeststock") . '
                WHERE created_at BETWEEN "' . $gettime['date_from'] . '" AND "' . $gettime['date_to'] . '"
                GROUP BY warehouse_name_from
                ORDER BY SUM(total_products) DESC';
}
$results = $readConnection->fetchAll($sql);
if (isset($requestData['warehouse_select']) && $requestData['warehouse_select'] > 0) {
    $checkResult = 0;
    foreach ($results as $result) {
        if ($checkResult > 10) {
            $limit = 10;
            break;
        }
        if ($result['total_request'] == NULL || $result['total_request'] <= 0) {
            $limit = $checkResult;
            continue;
        }
        $checkResult++;
    }
    if (isset($limit)) {
        $sql .= 'LIMIT ' . $limit . '';
        $results = $readConnection->fetchAll($sql);
    }
}

if ($is_warehouse == '1') {
    foreach ($results as $result) {
        $warehouse_name[] = $result['product_name'];
        $total_request[] = $result['total_request'];
    }
} else {
    foreach ($results as $result) {
        $warehouse_name[] = $result['warehouse_name_from'];
        $total_request[] = $result['total_request'];
    }
}
$i = 0;
$categories = '[';
foreach ($warehouse_name as $name_value) {
    if ($i != 0) {
        $categories .= ',';
    }
    $categories .= '"' . $name_value . '"';
    $i++;
}
$categories .= ']';
//            Zend_debug::dump($categories);
$j = 0;
$series['inventory_warehouse']['data'] = '[';
foreach ($total_request as $number_value) {
    if ($j != 0) {
        $series['inventory_warehouse']['data'] .= ',';
    }
    $series['inventory_warehouse']['data'] .= $number_value;
    $j++;
}
$series['inventory_warehouse']['data'] .= ']';
//            Zend_debug::dump($series);    
?>
<div class="chart-parent-div">
    <script type="text/javascript">
        $(function () {
            $_('#<?php echo $id ?>').highcharts({
            chart: {
            type: 'column',
                    margin: 70,
                    options3d: {
                    enabled: true,
                            alpha: 20,
                            beta: 1,
                            depth: 50
                    }
            },
                    title: {
                    text: '<?php echo $this->__('Total Qty Requested by Warehouse "' . $name . '"') ?>'
                    },
                    legend: {
                    enabled:false
                    },
                    plotOptions: {
                    column: {
                    depth: 30
                    }
                    },
                    xAxis: {
                    categories: <?php echo $categories ?>
                    },
                    yAxis: {
                    opposite: true
                    },
                    series: [
<?php $count = 0; ?>
<?php foreach ($series as $serie): ?>
    <?php if (!$count == 0) echo ','; ?>
    <?php $count++; ?>
                        {
                            name: '<?php echo $serie['name']; ?>',
                                    data: <?php echo $serie['data']; ?>
                            }
<?php endforeach; ?>
                        ]
            }
            );
        });
    </script>
    <div class="chart-child-div" id="<?php echo $id ?>"></div>
</div>