<!----------------------------------------->

<?php $activeTab = $this->getActiveTab() ?>
<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo $this->__('Supplier'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul>
            <?php if($activeTab == 'dropship'): ?>
                <li class="current last"><strong><?php echo $this->__('Drop Shipments') ?></strong></li>
            <?php else: ?>
                <li class="last"><a href="<?php echo $this->getUrl('inventorydropship/supplier/dropship') ?>" ><?php echo $this->__('Drop Ship') ?></a></li>            
            <?php endif ?>
            <?php if($activeTab == 'supplier_info'): ?>
                <li class="current"><strong><?php echo $this->__('Supplier Information') ?></strong></li>
            <?php else: ?>
                <li class=""><a href="<?php echo $this->getUrl('inventorydropship/supplier/index') ?>"><?php echo $this->__('Supplier Information') ?></a></li>
            <?php endif ?>
            <li class=" "><a href="<?php echo $this->getUrl('inventorydropship/supplier/logout') ?>" title="<?php echo $this->__('Log Out') ?>"><?php echo $this->__('Log Out') ?></a></li>
        </ul>
        <hr style = "opacity:0.3; margin-top: 20px">
    </div>
</div>
