<div class="account-login">
    <div class="page-title">
        <h1><?php echo $this->__('Supplier Login') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>        
    <form action="<?php echo $this->getUrl('inventorydropship/supplier/loginpost') ?>" method="post" id="login-form">
        <div class="col2-set">            
            <div class="registered-users col-1">
                <div class="content" style="">                                        
                    <ul class="form-list">
                        <li>
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" name="username" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="password" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>                        
                    </ul>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                </div>
            </div>
        </div>
        <div class="col2-set">
            <div class="col-1 new-users">               
            </div>
            <div class="registered-users">
                <div class="buttons-set">
                    <a href="<?php echo $this->getUrl('inventorydropship/supplier/forgotpassword') ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                    <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                </div>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
