<?php $supplier = Mage::getModel('inventorypurchasing/supplier')->load(Mage::getSingleton('inventorydropship/session')->getSupplier()->getId()) ?>
<div class="page-title">
    <h1><?php echo $this->__('Edit Supplier Information') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('inventorydropship/supplier/editPost') ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Supplier Information') ?></h2>
        <ul class="form-list">
            <li>                
                <div class="field">
                    <label for="supplier_name" class="required"><em>*</em><?php echo $this->__('Supplier Name') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Supplier Name') ?>" value="<?php echo $supplier->getSupplierName() ?>" class="input-text required-entry" name="name" id="name" />
                    </div>
                </div>
                <div class="field">
                    <label for="contact_name" class="required"><em>*</em><?php echo $this->__('Contact Person') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Contact Person') ?>" value="<?php echo $supplier->getContactName() ?>" class="input-text required-entry" name="contact_name" id="contact_name" />
                    </div>
                </div>
            </li>
            <li>                
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Email') ?>" value="<?php echo $supplier->getSupplierEmail() ?>" class="input-text required-entry validate-email" name="email" id="email" />
                    </div>
                </div>
                <div class="field">
                    <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Telephone') ?>" value="<?php echo $supplier->getTelephone() ?>" class="input-text required-entry" name="telephone" id="telephone" />
                    </div>
                </div>
            </li>                        
            <li class="wide">
                <label for="street" class="required"><em>*</em><?php echo $this->__('Street') ?></label>
                <div class="input-box">
                    <input type="text" name="street" value="<?php echo $supplier->getStreet() ?>" title="<?php echo $this->__('Street Address') ?>" id="street" class="input-text " />
                </div>
            </li>
            
            <li class="fields">
                <div class="field">
                    <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                    <div class="input-box">
                        <input type="text" name="city" value="<?php echo $supplier->getCity() ?>"  title="<?php echo $this->__('City') ?>" class="input-text" id="city" />
                    </div>
                </div>
                <div class="field">
                    <label for="state_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                    <div class="input-box">
                        <select id="state_id" name="state_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                           <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                        //<![CDATA[
                            $('state_id').setAttribute('defaultValue',  "<?php echo $supplier->getStateId() ?>");
                        //]]>
                        </script>
                        <input type="text" id="state" name="state" value="<?php echo $supplier->getState() ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" />
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                    <div class="input-box">
                        <input type="text" name="postcode" value="<?php echo $supplier->getPostcode() ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="postcode" class="input-text validate-zip-international" />
                    </div>
                </div>
                <div class="field">
                    <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                    <div class="input-box">
                        <?php echo $this->getCountryHtmlSelect() ?>
                    </div>
                </div>
            </li>
             <li class="fields">
                <div class="field">
                    <label for="website" class=""><?php echo $this->__('Website') ?></label>
                    <div class="input-box">
                        <input type="text" name="website" value="<?php echo $supplier->getWebsite() ?>" title="<?php echo $this->__('website') ?>" id="website" class="input-text" />
                    </div>
                </div>
             </li>
            <li class="control">
                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>" class="checkbox" /><label for="change_password"><?php echo $this->__('Change Password') ?></label>
            </li>
        </ul>
    </div>
    <div class="fieldset" style="display:none;">
        <h2 class="legend"><?php echo $this->__('Change Password') ?></h2>
        <ul class="form-list">
            <li>
                <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
                <div class="input-box">
                    <input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }
//]]>
</script>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    new RegionUpdater('country_id', 'state', 'state_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'postcode');
//]]>
</script>
