<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php 
	$meigee_blacknwhite_general = MAGE::helper('ThemeOptionsBlacknwhite')->getThemeOptionsBlacknwhite('meigee_blacknwhite_general');
	$loginAjaxStatus = $meigee_blacknwhite_general['loginajax']['status'];
?>
<p class="text-login"><a class="opc-link-login" href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo $this->__('LOGIN')?></a></p>
<?php if($loginAjaxStatus): ?>
	<script type="text/javascript">
		/* Login ajax */
		jQuery('.opc-link-login').on('click', function(){
			<?php if (Mage::app()->getStore()->isCurrentlySecure()): ?>
			ajaxLogin("<?php echo $this->getUrl('meigeeactions/login/', array('_secure'=>true)) ?>", false);
			<?php else : ?>
			ajaxLogin("<?php echo $this->getUrl('meigeeactions/login/', array('_secure'=>false)) ?>", false);
			<?php endif; ?>
			return false;
		});
	</script>
<?php endif; ?>