<?php
$columnNumber = $this->getColumnNumber();
$colunnSize = $this->getColumnSize();
$featuredWidth = 0;
if ($this->hasFeaturedProducts()) {
    $featuredWidth = '220';
    $featuredProduct = $this->getOneFeaturedProduct();
} elseif ($this->hasFeaturedCategories()) {
    $featuredWidth = '220';
    $featuredCategory = $this->getOneFeaturedCategory();
}
$size = '100% !important';
if ($columnNumber && $colunnSize)
    $size = floatval(($columnNumber - 1) * $colunnSize + 70 + $columnNumber * 15 + $featuredWidth) . 'px !important';
$i = 0;
?>
<div class="grid-categories-megamenu sub-menu" style="border:<?php echo $this->getCustomStyle('border_size') ?>px solid #<?php echo $this->getCustomStyle('border_color') ?> !important;background:#<?php echo $this->getCustomStyle('background_color') ?> !important;width: <?php echo $size; ?>;" >
<?php if (count($this->getCategories())): ?>
        <ul class="level0-megamenu">
            <h1 style="color:#<?php echo $this->getCustomStyle('text_color'); ?>;font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px;">
    <?php echo $this->getTemplateBlock($this->getHeaderContent()) ?>
            </h1>
                <?php foreach ($this->getCategories() as $category): ?>
                <?php $children = $this->getChildrenCollection($category); ?>
                <?php $i++; ?>
                <li class="level1-megamenu" style="<?php if ($colunnSize) echo 'width:' . $colunnSize . 'px !important'; ?>;<?php if ($i == $columnNumber): ?>border-right:none !important<?php endif; ?>">
                    <div class="level1-title">
                        <h2 style="color:#<?php echo $this->getCustomStyle('subtitle_color'); ?>;font-size:<?php echo $this->getCustomStyle('subtitle_font_size'); ?>px;">
        <?php echo $category->getName() ?>
                        </h2>
                        <label style="color:#<?php echo $this->getCustomStyle('text_color'); ?>;font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px;">
        <?php echo $category->getDescription(); ?>
                        </label>
                    </div>
                    <ol class="level2-megamenu" >
        <?php if (count($children)): ?>
                            <?php foreach ($children as $child): ?>
                                <li>
                                    <a style="color:#<?php echo $this->getCustomStyle('link_color'); ?> !important;font-size:<?php echo $this->getCustomStyle('link_font_size'); ?>px !important;" href="<?php echo $child->getUrl(); ?>">
                                        <span><?php echo $child->getName() ?></span>
                                    </a>
                                </li>
            <?php endforeach; ?>
                        <?php endif; ?>
                    </ol>
                </li>
        <?php
        if ($this->hasFeaturedProducts()) {
            if ($featuredProduct->getId())
                if ($i == ($columnNumber - 1))
                    break;
                else
                if ($i == $columnNumber)
                    break;
        }elseif ($this->hasFeaturedCategories()) {
            if ($featuredCategory->getId())
                if ($i == ($columnNumber - 1))
                    break;
                else
                if ($i == $columnNumber)
                    break;
        }
        ?>
    <?php endforeach; ?>
    <?php if ($this->hasFeaturedProducts() && $featuredProduct->getId()): ?>
                <li class="level1-megamenu featured" style="<?php echo 'width:' . $featuredWidth . 'px !important'; ?>">
                    <div class="level1-title">
                        <h2 style="color:#<?php echo $this->getCustomStyle('subtitle_color'); ?>;font-size:<?php echo $this->getCustomStyle('subtitle_font_size'); ?>px;"><?php echo $this->__('Featured Product') ?></h2>
                        <label style="color:#<?php echo $this->getCustomStyle('text_color'); ?>;font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px;"><?php echo $featuredProduct->getShortDescription(); ?></label>
                    </div>
                    <div class="level1-content">
                        <a class="product-image" href="<?php echo $featuredProduct->getProductUrl(); ?>">
                            <img title="<?php echo Mage::helper('megamenu')->htmlEscape($featuredProduct->getName()); ?>"src="<?php echo $this->helper('catalog/image')->init($featuredProduct, 'small_image')->resize(194) ?>" width="110"/>
                        </a>
                        <div class="product-shop">
                            <a href="<?php echo $featuredProduct->getProductUrl(); ?>">
                                <h1 class="product-name" style="font-size:<?php echo $this->getCustomStyle('link_font_size'); ?>px;color:#<?php echo $this->getCustomStyle('link_color'); ?>;"><?php echo $featuredProduct->getName(); ?></h1>
                            </a>
        <?php echo Mage::getBlockSingleton('catalog/product')->getPriceHtml($featuredProduct, true) ?>
                            <button class="button" onclick="window.location.href = '<?php echo $featuredProduct->getProductUrl(); ?>'"><?php echo $this->__('View Detail') ?></button>
                        </div>
                    </div>
                </li>
    <?php elseif ($this->hasFeaturedCategories() && $featuredCategory->getId()): ?>
                <li class="level1-megamenu featured" style="<?php echo 'width:' . $featuredWidth . 'px !important'; ?>">
                    <div class="level1-title">
                        <h2 style="color:#<?php echo $this->getCustomStyle('subtitle_color'); ?>;font-size:<?php echo $this->getCustomStyle('subtitle_font_size'); ?>px;"><?php echo $this->__('Featured Category') ?></h2>
                        <label style="color:#<?php echo $this->getCustomStyle('text_color'); ?>;font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px;"><?php echo $featuredCategory->getDescription(); ?></label>
                    </div>
                    <div class="level1-content">
                        <a class="product-image" href="<?php echo $featuredCategory->getUrl(); ?>">
                            <img title="<?php echo Mage::helper('megamenu')->htmlEscape($featuredCategory->getName()); ?>"src="<?php echo $featuredCategory->getImageUrl(); ?>" width="110"/>
                        </a>
                        <div class="product-shop">
                            <a href="<?php echo $featuredCategory->getUrl(); ?>">
                                <h1 class="product-name" style="font-size:<?php echo $this->getCustomStyle('link_font_size'); ?>px;color:#<?php echo $this->getCustomStyle('link_color'); ?>;"><?php echo $featuredCategory->getName(); ?></h1>
                            </a>
        <?php //echo Mage::getBlockSingleton('catalog/product')->getPriceHtml($featuredProduct, true) ?>
                            <button class="button" onclick="window.location.href = '<?php echo $featuredCategory->getUrl(); ?>'"><?php echo $this->__('View Detail') ?></button>
                        </div>
                    </div>
                </li>
        <?php endif; ?>
        </ul>
<?php endif; ?>
</div>


<?php echo $this->getFooterContent() ?>	
<?php
$_template_map = '<a href="#toggleheader">';
$_template_map .='<div id ="layout_header">';
$_template_map .='<span>Header Content</span>';
$_template_map .='</div></a>';
$_template_map .='<div id ="layout_main">';
$_template_map .='<a href="#megamenu_maincontent">';
$_template_map .='<div id="layout_main_content">';
$_template_map .='<span>Main Content</span>';
$_template_map .='</div></a>';
$_template_map .= '<a href="#megamenu_featuredcategories">';
$_template_map .='<div id="layout_feature">';
$_template_map .='<span>Featured Content</span>';
$_template_map .='</div></a></div>';
$_template_map .='<a href="#togglefooter">';
$_template_map .='<div id="layout_footer">';
$_template_map .='<span>Footer Content</span>';
$_template_map .='</div></a>';
?>
<?php
$header = 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.';
$footer = '';
$this->setDefaultHeaderFooter($header, $footer);
$this->setDefaultGeneralStyle('#ffffff', '#000000', 1); // (background_color, border_color, title_font, title_font_size)
$this->setDefaultTitleStyle('#000000', '#000000', '#ffffff', 'Arial,Helmet,Freesans,sans-serif'); // (title_color, title_background_color, title_font, title_font_size)
$this->setDefaultSubtitleStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 11); // (subtitle_color, subtitle_font, subtitle_font_size)
$this->setDefaultLinkStyle('#000000', '#3f58a3', 'Arial,Helmet,Freesans,sans-serif', 11); // (link_color, hover_color, link_font, link_font_size)
$this->setDefaultTextStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 12); // (text_color, text_font, text_font_size)
/* add title */
$this->addTitle('Categories');
/* add map */
$this->setTemplateMap($_template_map)
?>
