<div class="megamenu-item <?php echo $this->getData('menu_item_id')?>">
	<div class="megamenu-item-header">
		<?php echo $this->getHeaderContent() ?>
	</div>
	<div class="megamenu-item-main">
		<div class="megamenu-item-title" style="color:<?php echo $this->getSubtitleColor()?>">
			<?php echo $this->tranlateTitle('Categories')?>
		</div>
		<div class="megamenu-item-categories">
			<?php if(count($this->getCategories())):?>
				<ul>
				<?php foreach($this->getCategories() as $_category): ?>
					<li><a href="<?php echo $_category->getUrl()?>"><?php echo $_category->getName() ?></a></li>
				<?php endforeach; ?>
				</ul>
			<?php endif; ?>
		</div>
	</div>
	<div class="megamenu-item-footer">
		<?php echo $this->getFooterContent() ?>
	</div>	
</div>
<?php 
	$_template_map = '<a href="#toggleheader">';
$_template_map .='<div id ="layout_header">';
$_template_map .='<span>Header Content</span>';
$_template_map .='</div></a>';
$_template_map .='<div id ="layout_main">';
$_template_map .='<a href="#megamenu_maincontent">';
$_template_map .='<div id="layout_main_content">';
$_template_map .='<span>Main Content</span>';
$_template_map .='</div></a>';
$_template_map .= '<a href="#megamenu_featuredcategories">';
$_template_map .='<div id="layout_feature">';
$_template_map .='<span>Featured Content</span>';
$_template_map .='</div></a></div>';
$_template_map .='<a href="#togglefooter">';
$_template_map .='<div id="layout_footer">';
$_template_map .='<span>Footer Content</span>';
$_template_map .='</div></a>';
?>
<?php
    $header = 'Header';
    $footer = 'Footer';
    $this->setDefaultHeaderFooter($header, $footer);
    $this->setDefaultGeneralStyle('#ffffff', '#000000', 1); // (background_color, border_color, title_font, title_font_size)
$this->setDefaultTitleStyle('#000000', '#000000', '#ffffff', 'Arial,Helmet,Freesans,sans-serif'); // (title_color, title_background_color, title_font, title_font_size)
$this->setDefaultSubtitleStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 11); // (subtitle_color, subtitle_font, subtitle_font_size)
$this->setDefaultLinkStyle('#000000', '#3f58a3', 'Arial,Helmet,Freesans,sans-serif', 11); // (link_color, hover_color, link_font, link_font_size)
$this->setDefaultTextStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 12); // (text_color, text_font, text_font_size)
$this->setDefaultContentGeneral(600,4,150);// megamenu_size,column_number,column_size    
/*add title*/
    $this->addTitle('Categories');
    /*add map*/
    $this->setTemplateMap($_template_map)
?>
