<?php
    $columnNumber = $this->getColumnNumber();
    $colunnSize = $this->getColumnSize();

    if (count($this->getParentCategories()) < $columnNumber) {
        $columnNumber = count($this->getParentCategories());
    }
?>

<style>
    .megamenu #nav-toggle .list-categories-megamenu ul.level0-megamenu {
        width: 100% !important;
        padding: 10px 1% !important;
    }
    .megamenu #nav-toggle .list-categories-megamenu ul.level0-megamenu ul.level1-megamenu {
        /*border-left: 1px solid #d5d5d5 !important;*/
        border-right: none !important;
        width: 100% !important;
    }
    .megamenu #nav-toggle .list-categories-megamenu ul.level0-megamenu ul.level1-megamenu li {
        min-width: <?php if ($colunnSize) echo $colunnSize . 'px !important'; else  echo '200px !important'; ?>;
        float: left;
        padding-right: 10px;
    }
    .megamenu #nav-toggle .list-categories-megamenu ul.level0-megamenu ul.level1-megamenu li div.level1-title {
        padding-right: 15px;
    }    
    .megamenu #nav-toggle .list-categories-megamenu h1.block-title {
        border-top: none !important;
    }
    .megamenu #nav-toggle .list-categories-megamenu ul.level0-megamenu .header-megamenu {
        border-bottom: 1px dashed #d5d5d5;
        padding-bottom: 5px;
    }
    .megamenu #nav-toggle .list-categories-megamenu ul.level0-megamenu .footer-megamenu {
        margin-top: 10px;
    }
</style>

<div class="list-categories-megamenu sub-menu" 
     style="border:<?php echo $this->getCustomStyle('border_size') ?>px solid #<?php echo $this->getCustomStyle('border_color') ?> !important;
     background:#<?php echo $this->getCustomStyle('background_color') ?> !important;
     width: 100% !important" >
    <?php if (count($this->getParentCategories())): ?>
        <ul class="level0-megamenu">
            <div class="header-megamenu" 
                 style="color:#<?php echo $this->getCustomStyle('text_color'); ?> !important;
                        font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px !important;
                        font-family: <?php echo $this->getCustomStyle('text_font'); ?> !important;
                        /*edit by Sally*/
                        <?php if(!$this->getTemplateBlock($this->getHeaderContent())):?>border-bottom:none !important;<?php endif;?>">
                <?php echo $this->getTemplateBlock($this->getHeaderContent()) ?>
            </div>
            <ul class="level1-megamenu">
                <?php foreach ($this->getParentCategories() as $category): ?>
                    <?php $children = $this->getChildrenCollection($category); ?>
                <li <?php if ($columnNumber) echo 'style="width:'.(float)100/$columnNumber.'%;"'?>>
                        <div class="level1-title">
                            <a href="<?php echo $category->getUrl(); ?>">
                                <h2 style=" color:#<?php echo $this->getCustomStyle('subtitle_color'); ?> !important;
                                            font-size:<?php echo $this->getCustomStyle('subtitle_font_size'); ?>px !important;
                                            font-family: <?php echo $this->getCustomStyle('subtitle_font'); ?> !important;
                                            <?php if (!count($children)):?>border-bottom:none !important;<?php endif;?>">
                                    <?php echo $category->getName(); ?>
                                </h2>					
                            </a>
                        </div>
                        <ol  class="level2-megamenu">
                            <?php if (count($children)): ?>
                                <?php foreach ($children as $child): ?>
                                    <li>
                                        <a style="  color:#<?php echo $this->getCustomStyle('link_color'); ?> !important;
                                                    font-size:<?php echo $this->getCustomStyle('link_font_size'); ?>px !important;
                                                    font-family: <?php echo $this->getCustomStyle('link_font'); ?> !important;" 
                                           href="<?php echo $child->getUrl(); ?>"
                                           onmouseover="mm(this).attr('style', 'color: #<?php echo $this->getCustomStyle('hover_color'); ?> !important; font-size:<?php echo $this->getCustomStyle('link_font_size'); ?>px !important; font-family: <?php echo $this->getCustomStyle('link_font'); ?> !important;')" 
                                           onmouseout= "mm(this).attr('style', 'color: #<?php echo $this->getCustomStyle('link_color'); ?> !important; font-size:<?php echo $this->getCustomStyle('link_font_size'); ?>px !important; font-family: <?php echo $this->getCustomStyle('link_font'); ?> !important;')"
                                        >
                                            <span><?php echo $child->getName() ?></span>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </ol>
                    </li>
                <?php endforeach;?>
            </ul>  
            <div class="footer-megamenu" 
                 style="color:#<?php echo $this->getCustomStyle('text_color'); ?> !important;;
                        font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px !important;;
                        font-family: <?php echo $this->getCustomStyle('text_font'); ?> !important;">
                <?php echo $this->getTemplateBlock($this->getFooterContent()) ?>
            </div>
        </ul>
    <?php endif; ?>
</div>
<?php
$_template_map = '<div class="megamenu-template-map">';
$_template_map .= '<div class="layout-nav">';
$_template_map .= '</div>';
$_template_map .= '<div class="megamenu-template-map-header">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#buttonsheader">Header</a>';
$_template_map .= '<div>&nbsp;</div></div>';
$_template_map .= '<div class="megamenu-template-map-main">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#categories">Main Content</a>';
$_template_map .= '<div>&nbsp;</div></div>';
//$_template_map .='<div id="layout_feature">';
//$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#featured_type">';
//$_template_map .='<span>Featured Content</span>';
//$_template_map .='</a><div>&nbsp;</div></div>';
$_template_map .= '<div class="megamenu-template-map-footer">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#buttonsfooter">Footer</a>';
$_template_map .= '<div>&nbsp;</div></div>';
$_template_map .= '</div>';
?>
<?php
$header = 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.';
$footer = '';
$this->setDefaultHeaderFooter($header, $footer);
$this->setDefaultGeneralStyle('#ffffff', '#D5D5D5', 1); // (background_color, border_color,border_size)
$this->setDefaultTitleStyle('#ffffff', '#000000', 'Arial,Helmet,Freesans,sans-serif', '11'); // (title_color, title_background_color, title_font, title_font_size)
$this->setDefaultSubtitleStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 11); // (subtitle_color, subtitle_font, subtitle_font_size)
$this->setDefaultLinkStyle('#666666', '#3f58a3', 'Arial,Helmet,Freesans,sans-serif', 11); // (link_color, hover_color, link_font, link_font_size)
$this->setDefaultTextStyle('#666666', 'Arial,Helmet,Freesans,sans-serif', 11); // (text_color, text_font, text_font_size)
$this->setDefaultContentGeneral(600, 4, 180); // megamenu_size,column_number,column_size
/* add title */
$this->addTitle('Categories');
/* add map */
$this->setTemplateMap($_template_map);
$this->setTemplateFileName('responsive_categories_template_2');
?>
