
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') . 'prototype/prototype.js' ?>"></script>

<style>
    body {
        font-family: Segoe UI, Calibri, Arial, Helvetica;
        font-size: 12px;
        color: #111;
        margin: 8px;
    }

    .footer {
        text-align: center;
        margin-top: 40px;
    }

    form, .header {
        display: block;
        margin: auto;
        width: 60%;
        min-width: 600px;
        max-width: 700px;
        position: relative;
    }

    input, select {
        margin: 0;
    }

    input[type=text], input[type=number], select {
        border: 1px solid #ababab;
        padding: 2px;
    }

    select {
        padding-top: 1px;
        padding-bottom: 1px;
    }

    ul {
        margin: 0;
        padding: 0;
        list-style: none;
    }

    section {
        margin-bottom: 24px;
    }

    h1 {
        /* display: none;*/
    }

    h2 {
        margin: 14px 0 8px 0;
        font-weight: normal;
        font-size: 20px;
    }

    h3 {
        font-size: 16px;
        font-weight: normal;
        font-style: italic;
        padding-bottom: 4px;
        border-bottom: 1px solid #c8c8c8;
        margin: 0 0 14px 0;
    }

    .logo {
        margin-top: 8px;
    }

    nav {
        float: right;
        position: absolute;
        top: 34px;
        right: 0;
    }

    nav label {
        display: block;
    }

    nav select {
        margin: 2px 0;
        margin-left: 0;
    }

    table {
        table-layout: fixed;
        border-collapse: collapse;
        width: 100%;
    }

    table td {
        padding: 3px 25px 1px 4px;
        vertical-align: top;
        height: 26px; /* This act as a min-height */
        /* line-height: 30px; */
        width: 350px;
    }

    table tr.odd {
        background-color: #eee;
    }

    table tr.even {
    }

    table .col1 {
        width: 180px;
    }

    table .info {
        position: absolute;
        dtop: 0;
        dright: 5px;
        line-height: 34px;
    }

    .info img {
        border: 0;
        vertical-align: text-bottom;
    }

    .generate {
        float: left;
    }

    .possiblechars {
        float: right;
        position: relative;
    }

    #dpiUnavailable {
        display: none;
        padding-left: 8px;
    }

    div.configurations select {
        min-width: 70px;
    }

    div.configurations input[type=number] {
        width: 70px;
    }

    /* Moved section by script */
    #explanation, #dpiExplain, #validCharacters {
        display: none;
        max-width: 450px;
    }

    #explanation ul {
        list-style: disc;
        margin-left: 20px;
    }

    #specificOptions {
        display: none;
    }

    #validCharacters input[type=button] {
        width: 25px;
        padding: 1px 6px;
    }

    .BCGcode128 #validCharacters input[type=button],
    .BCGcode39extended #validCharacters input[type=button],
    .BCGcode93 #validCharacters input[type=button],
    .BCGgs1128 #validCharacters input[type=button],
    .BCGaztec #validCharacters input[type=button],
    .BCGdatamatrix #validCharacters input[type=button],
    .BCGmaxicode #validCharacters input[type=button],
    .BCGqrcode #validCharacters input[type=button],
    .BCGpdf417 #validCharacters input[type=button] {
        width: 39px;
    }

    .bubble {
        display: none;
    }

    .bubble.visible {
        display: block !important;
        position: absolute;
        background-color: #f8f8f8;
        border: 2px solid #ddd;
        padding: 16px;
    }

    .gs1128_id {
        width: 40px;
        text-align: center;
    }

    .gs1128_value {
        width: 295px;
    }

    .gs1128_delete img {
        border: 0;
        margin-left: 5px;
        vertical-align: text-bottom;
    }

    #identifierContainer {
        margin-top: 4px;
    }
    @media print {
        #printbarcode_form{
            display: none;		
        }
        h3{
            display: none;		
        }
        button{
            display: none;		
        }
        .output{
            display: none;
        }        
    }
</style>

<?php $barcode = Mage::getModel('inventorybarcode/barcode')->load($this->getRequest()->getParam('barcode')); ?>
<form id="printbarcode_form" action="<?php echo Mage::helper("adminhtml")->getUrl('inventorybarcodeadmin/adminhtml_printbarcode/printBarcode/'); ?>" name="printbarcode_form" method="post">
    <input type="hidden" name="form_key" value="<?php echo $this->getFormKey() ?>" />
    <input type="hidden" name="barcodeId" value="<?php echo $this->getRequest()->getParam('barcode') ?>" />
    <input type="hidden" id="image_width" name="image_width" value="" />
    <h1><?php echo $this->__('Barcode Generator') ?></h1>
    <h2><?php echo Mage::helper('inventorybarcode')->__('Barcode:') . ' ' . '<b>'.$barcode->getBarcode().'</b>'; ?></h2>
    <!--<h3><?php echo Mage::helper('inventorybarcode')->__('Barcode type: ') . ' ' . Mage::helper('inventorybarcode')->getBarcodeName(); ?></h3>-->
    <div class="configurations">
        <section class="configurations">
            <h3>Configurations</h3>
            <table>
                <colgroup>
                    <col class="col1" />
                    <col class="col2" />
                </colgroup>
                <tbody>
                    <tr class="odd">
                        <td><label for="symbology"><?php echo $this->__('Symbology') ?></label></td>
                        <?php 
                            $barcodeTypes = Mage::getModel('inventorybarcode/barcodetypes')->toOptionArray();
                            $defaultBarcodeType = Mage::getStoreConfig('inventoryplus/barcode/barcode_type',Mage::app()->getStore()->getStoreId());
                        ?>                        
                        <td><select size="1" id="type" name="type">
                                <?php foreach($barcodeTypes as $value):?>
                                <option <?php if($value['value']==$defaultBarcodeType) echo 'selected'?> value="<?php echo $value['value']?>"><?php echo $value['label']?></option>                               
                                <?php endforeach;?>
                            </select>
                        </td>
                    </tr>
                   
                    <tr class="odd" style="display:none">
                        <td><label for="font_family"><?php echo $this->__('Font') ?></label></td>
                        <td> <?php echo Mage::getModel('inventorybarcode/printbarcode_function')->getInputTextHtml('font_size', 10, array('type' => 'number', 'min' => 1, 'max' => 30)); ?></td>
                    </tr>
                    <tr class="odd">
                        <td><label for="font_family"><?php echo $this->__('Barcode Qty') ?></label></td>
                        <td><input type="text" name="number_of_barcode" id="number_of_barcode" value="1"/></td>
                    </tr>
                    <tr class="odd">
                        <td><label for="font_family"><?php echo $this->__('Paper Size') ?></label></td>
                        <td>
                            <select id="printing_format" name="printing_format">
                                <option value="A4" selected=""><?php echo $this->__('A4')?></option>
                                <option value="A5"><?php echo $this->__('A5')?></option>
                                <option value="A6"><?php echo $this->__('A6')?></option>
                                <option value="A7"><?php echo $this->__('A7')?></option>
                                <option value="A8"><?php echo $this->__('A8')?></option>
                            </select>
                        </td>
                    </tr>
                    <!--
                    <tr class="odd">
                        <td><label for="font_family"><?php echo $this->__('Show border') ?></label></td>
                        <td><input type="checkbox" name="border" id="border" value="1"/></td>
                    </tr>
                    -->
                    <tr class="odd">
                        <td><label for="font_family"><?php echo $this->__('Select Template') ?></label></td>
                        <td>
                            <div style="float:left;">
                            <label><?php echo $this->__('Select barcode template: ') ?></label>
                            <?php 
                                $barcodeTemplates = Mage::getModel('inventorybarcode/barcodetemplate')
                                                            ->getCollection()
                                                            ->addFieldToFilter('status',1);
                            ?>
                            <select name="barcode_template" id="barcode_template" onchange="showDetaitl(this)">                        
                                <?php foreach($barcodeTemplates as $barcodeTemplate): ?>
                                    <option value="<?php echo $barcodeTemplate->getId() ?>"><?php echo $barcodeTemplate->getData('barcode_template_name') ?></option>                            
                                <?php endforeach ?>
                            </select>
                            <?php foreach($barcodeTemplates as $barcodeTemplate): ?>
                                <div style="display:none" id="template_id_<?php echo $barcodeTemplate->getId() ?>">
                                    <?php $processor =  Mage::helper('cms')->getBlockTemplateProcessor();?>
                                    <?php echo $html = $processor->filter($barcodeTemplate->getHtml()); ?>

                                </div>
                            <?php endforeach; ?>
                           
                        </div>
                        </td>
                    </tr>
                    <tr class="odd">
                        <td><label for="font_family"><?php echo $this->__('Customize') ?></label></td>
                        <td><input type="checkbox" name="customize" onclick="customizeBarcode()" id="customize" value="1"/></td>
                    </tr>
                   
                    <tr class="odd" id="tr_heigth_barcode" style="display:none">
                        <td><label for="font_family"><?php echo $this->__('Height of Barcode (pixel)') ?></label></td>
                        <td><input type="text" name="heigth_barcode" id="heigth_barcode" value="70"/></td>
                    </tr>
                    <tr style="display:none">
                       
                        <td><input type="file" name="image_file" id="image_file" value="70"/></td>
                    </tr>
                    
                    <tr class="odd">
                        <td><label for="text"></label></td>
                        <td>
                            <div class="generate" style="float: left"><?php echo Mage::getModel('inventorybarcode/printbarcode_function')->getInputTextHtml('text', $barcode->getBarcode(), array('hidden' => 'text', 'required' => 'required')); ?> <input type="button" onclick="getImage()" value="<?php echo $this->__('Generate') ?>" /></div>

                        </td>
                    </tr>
                </tbody>
            </table>
        </section>
    </div>
</form>

    <div class="output" id="output" style="display:none">
        <section class="output">
            <h3><?php echo $this->__('Output') ?></h3>
            <button onclick="printstore()" type="button"><?php echo $this->__('Print') ?></button>
          
        </section>
    </div>

<div id="print_content">
                <div id="imageOutput" style="margin: auto; float: left">

                </div>
        </div>

<?php $product = Mage::getModel('catalog/product')->load($barcode->getProductEntityId());?>

<script type="text/javascript">
    function customizeBarcode() {
        if ($('customize').checked) {
            $('tr_heigth_barcode').show();           
        } else {
            $('tr_heigth_barcode').hide();           
        }
    }
   
    
    function getImage() {
        $('output').show();
        if($('barcode_template').value==4){
//            $('font_family').value = 0;
        }else{
//            $('font_family').value = 'Arial.ttf';
        }
//        var url = '<?php  echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'barcode.jpg';?>';
        var url = '<?php echo Mage::helper("adminhtml")->getUrl('inventorybarcodeadmin/adminhtml_printbarcode/getimage/'); ?>?' + $('printbarcode_form').serialize();
    
        var html = '';
        var image = '';
        var border = '';
//        if ($('border').checked) {
//            border = 'border: 1px dashed;';
//        }
        
            for (var i = 0; i < $('number_of_barcode').value; i++) {                
               image +=  '<div style="float:left; margin: 5px;overflow: hidden; padding: 5px;' + border + '">';
                if($('barcode_template').value==2){
                    image += '<span style="display:block; width: 100%; font-size: '+$('font_size').value+'px; text-align: left;"><?php echo $barcode->getProductName()?></span>';                    
                }
                if($('barcode_template').value==3){
                    image += '<div style="width: 100%; float: left; text-align: left;">';
                }
                if($('barcode_template').value==4){
                    image += '<div style="width:100%; text-align: center; display:block; overflow: hidden;vertical-align: middle;"><span style="float: left; font-size: 12px; text-align: left; width: 70%;"><?php echo $product->getName()?></span><span style="font-size: 17px; float: left; text-align: left;"><?php echo Mage::helper('core')->currency($product->getPrice())?></span></div>';
                   
                }
                
                image += '<img name="barcode_images" src="'+url+'" />';   
                <?php if($product->offsetExists('shirt_size') && $product->offsetExists('color') ): ?>
                if($('barcode_template').value==3){
                    var fontsize = parseFloat($('font_size').value)+parseFloat(10);
                    image += '<ul style="font-size: '+$('font_size').value+'px; list-style: outside none none; margin: 0; font-size: 12px; padding:0">';
                    image += '<li><?php echo $product->getName()?></li>';
                    image += '<li><?php echo $this->__('Size: ')?><?php if($product->getResource()->getAttribute('shirt_size')->getFrontend()->getValue($product) && $product->getResource()->getAttribute('shirt_size')->getFrontend()->getValue($product)!='No'){echo $product->getResource()->getAttribute('shirt_size')->getFrontend()->getValue($product);}?><?php if($product->getResource()->getAttribute('shoe_size')->getFrontend()->getValue($product) && $product->getResource()->getAttribute('shoe_size')->getFrontend()->getValue($product)!='No'){echo $product->getResource()->getAttribute('shoe_size')->getFrontend()->getValue($product);}?><?php if($product->getResource()->getAttribute('ram_size')->getFrontend()->getValue($product) && $product->getResource()->getAttribute('ram_size')->getFrontend()->getValue($product)!='No'){echo $product->getResource()->getAttribute('ram_size')->getFrontend()->getValue($product);}?></li>';
                    image += '<li><?php echo $this->__('Color: ')?><?php echo $product->getResource()->getAttribute('color')->getFrontend()->getValue($product)?><span style="margin-left:10px; font-size:'+fontsize+'px;"><?php echo Mage::helper('core')->currency($product->getPrice())?></span></div></li>';
                   
                }
				<?php endif; ?>
                image += '</div>';
                
            }
       var width = 0;
       if($('printing_format').value == 'A4'){
            width = 8.3;
       }
       if($('printing_format').value == 'A5'){
            width = 5.8;
       }
       if($('printing_format').value == 'A6'){
            width = 4.1;
       }
       if($('printing_format').value == 'A7'){
            width = 2.9;
       }
       if($('printing_format').value == 'A8'){
            width = 2.0;
       }
        $('imageOutput').style.width = width + 'in';
        $('imageOutput').innerHTML = image;
  
    }

    function printstore() {   
     var width = document.getElementsByName('barcode_images')[0].width;
        $('image_width').value = width;
//            window.print();   
        $('printbarcode_form').submit();
    }
    
    function showDetaitl(element) {
        for(var i = 1;i<5;i++){
            $('template_id_'+i).hide();
        }
        $('template_id_'+element.value).show();
    }
    $('template_id_1').show();
</script>