<?php
    $categories = $this->getCategories();
    $columnNumber = $this->getColumnNumber();
    $colunnSize = $this->getColumnSize();
    
    if (count($categories) < $columnNumber) {
        $columnNumber = count($categories);
    }
    $condition = count($categories);
?>

<style>
    .megamenu #nav-toggle .grop-megamenu ul.level0-megamenu {
        width: 100% !important;
        padding: 10px 1% !important;
    }
    .megamenu #nav-toggle .grop-megamenu h1.block-title {
        border-top: none !important;
    }
    .megamenu #nav-toggle .grop-megamenu ul.level0-megamenu .header-megamenu {
        border-bottom: 1px dashed #d5d5d5;
        padding-bottom: 5px;
    }
    .megamenu #nav-toggle .grop-megamenu ul.level0-megamenu .footer-megamenu {
        margin-top: 10px;
    }
    .megamenu #nav-toggle .grop-megamenu ul.level0-megamenu li.level1-megamenu {
        min-width: <?php echo $colunnSize."px"?> !important;
        width: <?php echo (float) 100/$columnNumber;?>% !important;
        border-right: none !important;
       // border-left: 1px solid #d5d5d5 !important;
        margin: 13px 0 0 !important;
        padding: 0 5px !important;
    }
</style>

<div class="list-categories-megamenu sub-menu grop-megamenu" 
     style="border:<?php echo $this->getCustomStyle('border_size') ?>px solid #<?php echo $this->getCustomStyle('border_color') ?> !important;
            background:#<?php echo $this->getCustomStyle('background_color') ?> !important;
            width: 100% !important;" >
    <?php if ($this->getHeaderContent()) :?>
    <div class = "header-megamenu" 
         style="color:#<?php echo $this->getCustomStyle('text_color'); ?>;
                font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px; 
                font-family: <?php echo $this->getCustomStyle('text_font'); ?> !important;">			
        <?php
        $text = $this->getTemplateBlock($this->getHeaderContent());
//        $newtext = $this->limitString($text, 200);
        echo $text;
        ?>
    </div>
    <?php endif;?>
    <?php if (count($this->getCategories())): ?>
        <ul class="level0-megamenu group-category" 
            id="group-category-<?php echo $this->getItem()->getId(); ?>">
            <?php foreach ($this->getCategories() as $category): ?>
            <li class="level1-megamenu">
                <?php $children = $this->getAllChildrenOfGroup($category); ?>
                <div class="level1-title">
                    <a href="<?php echo $category->getUrl(); ?>">
                        <strong style="color:#<?php echo $this->getCustomStyle('subtitle_color'); ?>;
                                    font-size:<?php echo $this->getCustomStyle('subtitle_font_size'); ?>px;
                                    font-family: <?php echo $this->getCustomStyle('subtitle_font'); ?> !important;
                                    text-transform: upercase !important;
                                    <?php if(!count($children)):?>border-bottom:none !important<?php endif;?>">
                            <?php echo $category->getName() ?>
                        </strong>
                    </a>
                </div>
                <ol  class="level3-megamenu" style="padding-left: 10px !important;">
                    <?php if (count($children)): ?>
                        <?php foreach ($children as $child): ?>
                            <li id="subcat-<?php echo $child->getId(); ?>">
                                <?php //echo $child->getName(); ?>
                                <a style="  color:#<?php echo $this->getCustomStyle('link_color'); ?> !important;
                                            font-size:<?php echo $this->getCustomStyle('link_font_size'); ?>px !important;
                                            font-family: <?php echo $this->getCustomStyle('link_font'); ?> !important;" 
                                   href="<?php echo $child->getUrl(); ?>"
                                   onmouseover="mm(this).attr('style', 'color: #<?php echo $this->getCustomStyle('hover_color'); ?> !important; font-size:<?php echo $this->getCustomStyle('link_font_size'); ?>px !important; font-family: <?php echo $this->getCustomStyle('link_font'); ?> !important;')" 
                                   onmouseout= "mm(this).attr('style', 'color: #<?php echo $this->getCustomStyle('link_color'); ?> !important; font-size:<?php echo $this->getCustomStyle('link_font_size'); ?>px !important; font-family: <?php echo $this->getCustomStyle('link_font'); ?> !important;')"
                                >
                                    <span><?php echo $child->getName() ?></span>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </ol>
            </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    
    <?php if ($this->getFooterContent()) :?>
    <div class="footer-megamenu" 
         style="color:#<?php echo $this->getCustomStyle('text_color'); ?>;
                font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px;
                font-family: <?php echo $this->getCustomStyle('text_font'); ?> !important;">
        <?php echo $this->getTemplateBlock($this->getFooterContent()) ?>
    </div>
    <?php endif; ?>
</div>


<?php
$_template_map = '<div class="group-category">';
$_template_map .= '<div class="layout-nav">';
$_template_map .= '</div>';
$_template_map .= '<div class="megamenu-template-map-header">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#buttonsheader">Header</a>';
$_template_map .= '<div>&nbsp;</div></div>';
$_template_map .= '<div class="megamenu-template-map-main">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#categories">Main Content</a>';
$_template_map .= '<div>&nbsp;</div></div>';
$_template_map .= '<div class="megamenu-template-map-footer">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#buttonsfooter">Footer</a>';
$_template_map .= '<div>&nbsp;</div></div>';
$_template_map .= '</div>';
?>
<?php
$header = 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.';
$footer = '';
$this->setDefaultHeaderFooter($header, $footer);
$this->setDefaultGeneralStyle('#ffffff', '#D5D5D5', 1); // (background_color, border_color,border_size)
$this->setDefaultTitleStyle('#ffffff', '#000000', 'Arial,Helmet,Freesans,sans-serif', '11'); // (title_color, title_background_color, title_font, title_font_size)
$this->setDefaultSubtitleStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 11); // (subtitle_color, subtitle_font, subtitle_font_size)
$this->setDefaultLinkStyle('#666666', '#3f58a3', 'Arial,Helmet,Freesans,sans-serif', 11); // (link_color, hover_color, link_font, link_font_size)
$this->setDefaultTextStyle('#666666', 'Arial,Helmet,Freesans,sans-serif', 11); // (text_color, text_font, text_font_size)
$this->setDefaultContentGeneral(600, 4, 180); // megamenu_size,column_number,column_size
/* add title */
$this->addTitle('Categories');
/* add map */
$this->setTemplateMap($_template_map)
?>

<script>
    mm('.grop-megamenu').parent().parent().mouseenter(function() {
        var gm_min_col_size = <?php echo $colunnSize;?>;
        var gm_max_cols = <?php echo $columnNumber;?>;
        var gm_1_col_width = 96/gm_max_cols;
        var gm_menu_width = mm('.topmenu').innerWidth();
            gm_menu_width *= 0.96;
            
        if (gm_menu_width/gm_max_cols >= gm_min_col_size) {
            mm('.level1-megamenu').css("cssText", mm('.level1-megamenu').attr('style')+"width:"+gm_1_col_width+"% !important;");
        } else {
            var gm_real_cols = Math.floor(gm_menu_width/gm_min_col_size);
            if (gm_real_cols < 2) gm_real_cols = 1;
            gm_1_col_width = 96/gm_real_cols;
            mm('.level1-megamenu').css("cssText", mm('.level1-megamenu').attr('style')+"width:"+gm_1_col_width+"% !important;");
        }
        
        var height = mm(this).attr('id');
        var max_height = 0;
        mm.each(mm('#' + height + ' .level1-megamenu'), function() {
            if (max_height < mm(this).height()) {
                max_height = mm(this).height();
            }
        });
        mm('#' + height + ' .level1-megamenu').height('auto');
        
    });
</script>