<?php
/**
 * BelVG LLC.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 *
 *******************************************************************
 * @category   Belvg
 * @package    Belvg_Sizes
 * @copyright  Copyright (c) 2010 - 2014 BelVG LLC. (http://www.belvg.com)
 * @license    http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 */
?>
<?php $helper = Mage::helper('sizes'); ?>
<ul id="sizes-tabs" class="<?php echo $helper->isChartsTab()?'tabs3':'tabs2'; ?>">
    <li class="sizes_tab selected" id="sizes-form-tab" onclick="sizesTabActive('sizes-form', this);">
        <?php echo $this->__('Your Sizes'); ?>
    </li>
    <li class="sizes_tab disabled" id="sizes-result-tab" onclick="sizesTabActive('sizes-result', this);">
        <?php echo $this->__('Results'); ?>
    </li>
    <?php if ($helper->isChartsTab()): ?>
    <li class="sizes_tab" id="sizes-charts-tab" onclick="sizesTabActive('sizes-charts', this);">
        <?php echo $this->__('Size Charts'); ?>
    </li>
    <?php endif; ?>
</ul>
<div id="sizes-content">
    <div id="sizes-form" class="content">
        <?php echo $this->getChildHtml('form_sizes'); ?>
    </div>
    <div id="sizes-result" class="content">
        <?php echo $this->getChildHtml('result_sizes'); ?>
    </div>
    <?php if ($helper->isChartsTab()): ?>
    <div id="sizes-charts" class="content">
        <?php echo $this->getChildHtml('charts_sizes'); ?>
    </div>
    <?php endif; ?>
</div>
<script type="text/javascript">
refreshSizepopup();
function sizesTabActive(selector, obj)
{  
    if (!jQblvg(obj).hasClass('disabled') 
    && !jQblvg(obj).hasClass('selected')) {
        jQblvg('#sizes-tabs .sizes_tab').removeClass('selected');
        jQblvg('#sizes-tabs #'+selector+'-tab').addClass('selected').removeClass('disabled');
        jQblvg('#sizes-content .content').slideUp('slow');
        jQblvg('#'+selector).slideDown('slow');
    }
}

</script>