<style>
    .highcharts-container {
        width: 100% !important;
    }  
</style>
<div class="entry-edit" id="test">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Chart Report') ?></h4>
    </div>
    <!DOCTYPE HTML>
    <div>
        <div style="width: 100%; float: left;">
          
            <?php
            $adjustStockCollection = Mage::getModel('inventoryplus/adjuststock')->getCollection()
                                    ->addFieldToFilter('status','1')
                                    ->setPageSize(10);
    $categories = '[';
    $series['item']['name'] = $this->__('Number of Products');
    $series['item']['data'] = '[';    
    $series['qty']['name'] = $this->__('Total Qty of Products');
    $series['qty']['data'] = '[';    
    $i = 0;
    $resource = Mage::getSingleton('core/resource');        
    $readConnection = $resource->getConnection('core_read');
    foreach($adjustStockCollection as $adjustStock){
        $results = '';
        $sql = 'SELECT count(`adjuststock_id`) as `totalproduct`, sum(`adjust_qty`) as `totalqty` from '.$resource->getTableName('erp_inventory_adjuststock_product').' WHERE 
                                            (`adjuststock_id` = \''.$adjustStock->getId().'\')
                                        group by `adjuststock_id`';         
        $results = $readConnection->query($sql);        
        $items = 0;
        $qties = 0;
        if($results){
            foreach($results as $result){
                $items += $result['totalproduct'];
                $qties += $result['totalqty'];
            }
        }
        if($i != 0){
            $categories .= ',';            
            $series['item']['data'] .= ',';
            $series['qty']['data'] .= ',';
        }
        $categories .= '\''.date('M d',  strtotime($adjustStock->getCreatedAt())).'\'';        
        $series['item']['data'] .= $items;     
        $series['qty']['data'] .= $qties;     
        $i++;        
    }
    $categories .= ']';    
    $series['item']['data'] .= ']';
    $series['qty']['data'] .= ']'; 
            ?>
            <script type="text/javascript">
                $(function () {
                    $_('#container').highcharts({
                        chart: {
                            type: 'column'
                        },
                        title: {
                            text: '<?php echo $this->__('The last 10 stock adjustments') ?>'
                        },
                        subtitle: {
                            text: ''
                        },
                        xAxis: {
                            categories: <?php echo $categories ?>
                        },
                        yAxis: {
                            min: 0,
                            title: {
                                text: ''
                            }
                        },
                        tooltip: {
                            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                                '<td style="padding:0"><b>{point.y:.0f} </b></td></tr>',
                            footerFormat: '</table>',
                            shared: true,
                            useHTML: true
                        },
                        plotOptions: {
                            column: {
                                pointPadding: 0.2,
                                borderWidth: 0
                            }
                        },
                        series: [
<?php $count = 0; ?>
    
<?php foreach ($series as $serie): ?>
    <?php if (!$count == 0) echo ','; ?>
    <?php $count++; ?>    
                            {
                                name: '<?php echo $serie['name']; ?>',
                                data: <?php echo $serie['data']; ?>
                            }
<?php endforeach; ?>
                ]
            });
        });
            </script>


            <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
        </div>
       
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/_JSSettings.js"></script>
<script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/js_002"></script>
<script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/dashboards"></script>

<script type="text/javascript">
    var saveViewPositions = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/saveviewposition') ?>';
    var saveTabPositions = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/savetabposition') ?>';
    var form_key_dashboard = '<?php echo $this->getFormKey() ?>';
</script>
<script type="text/javascript">
    var $sd = new InventoryDashboard.Views.Dashboards();
    $sd.isShare = false;
    $sd.backgroundColour = '#808080';
    $sd.init();
</script>