<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2010-2014 MeigeeTeam. (http://www.meigeeteam.com)
 */
 $meigee_blacknwhite_general = MAGE::helper('ThemeOptionsBlacknwhite')->getThemeOptionsBlacknwhite('meigee_blacknwhite_general');
 $footer_status = $meigee_blacknwhite_general['footer']['footer_status'];
 $footer_static = $meigee_blacknwhite_general['footer']['footer_static'];
?>
<footer id="footer"<?php if ($footer_status == 0): ?> class="default-footer"<?php endif; ?>>
	<div class="block_newsletter">
		<div class="container_12">
			<div class="grid_3">
			<strong>
				BEAUTYZONE
			</strong>
			</div>
			<div class="grid_6">
				<div class="form_kid">
					<!-- Begin MailChimp Signup Form -->
					<div id="mc_embed_signup">
					<form action="//beautyzone.us8.list-manage.com/subscribe/post?u=ec1eb7ec170bd22f0ca3a8d1d&amp;id=e5d2b09f85" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
					    <div id="mc_embed_signup_scroll">
						<div class="mc-field-group">
							<input type="email" value="" name="EMAIL" class="required email input-text" id="mce-EMAIL" place-hoder= "NHẬP ĐỊA CHỈ EMAIL" />
							<input type="submit" value="Gửi" name="subscribe" id="mc-embedded-subscribe" class="button btn-send" />
						</div>
							<div id="mce-responses" class="clear">
								<div class="response" id="mce-error-response" style="display:none"></div>
								<div class="response" id="mce-success-response" style="display:none"></div>
							</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
						    <div style="position: absolute; left: -5000px;"><input type="text" name="b_ec1eb7ec170bd22f0ca3a8d1d_e5d2b09f85" tabindex="-1" value=""></div>
						    <div class="clear"></div>
					    </div>
					</form>
					</div>
					<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
					<!--End mc_embed_signup-->
				</div>
				<div class="form_men" style="display: none;">
					<!-- Begin MailChimp Signup Form -->
					<div id="mc_embed_signup">
					<form action="//beautyzone.us8.list-manage.com/subscribe/post?u=ec1eb7ec170bd22f0ca3a8d1d&amp;id=e5d2b09f85" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
					    <div id="mc_embed_signup_scroll">
						<div class="mc-field-group">
							<input type="email" value="" name="EMAIL" class="required email input-text" id="mce-EMAIL" place-hoder= "NHẬP ĐỊA CHỈ EMAIL" />
							<input type="submit" value="Gửi" name="subscribe" id="mc-embedded-subscribe" class="button btn-send" />
						</div>
							<div id="mce-responses" class="clear">
								<div class="response" id="mce-error-response" style="display:none"></div>
								<div class="response" id="mce-success-response" style="display:none"></div>
							</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
						    <div style="position: absolute; left: -5000px;"><input type="text" name="b_ec1eb7ec170bd22f0ca3a8d1d_e5d2b09f85" tabindex="-1" value=""></div>
						    <div class="clear"></div>
					    </div>
					</form>
					</div>
					<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
					<!--End mc_embed_signup-->
				</div>
				<div class="form_women" style="display: none;">
					<!-- Begin MailChimp Signup Form -->
					<div id="mc_embed_signup">
					<form action="//beautyzone.us8.list-manage.com/subscribe/post?u=ec1eb7ec170bd22f0ca3a8d1d&amp;id=e5d2b09f85" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
					    <div id="mc_embed_signup_scroll">
						<div class="mc-field-group">
							<input type="email" value="" name="EMAIL" class="required email input-text" id="mce-EMAIL" place-hoder= "NHẬP ĐỊA CHỈ EMAIL" />
							<input type="submit" value="Gửi" name="subscribe" id="mc-embedded-subscribe" class="button btn-send" />
						</div>
							<div id="mce-responses" class="clear">
								<div class="response" id="mce-error-response" style="display:none"></div>
								<div class="response" id="mce-success-response" style="display:none"></div>
							</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
						    <div style="position: absolute; left: -5000px;"><input type="text" name="b_ec1eb7ec170bd22f0ca3a8d1d_e5d2b09f85" tabindex="-1" value=""></div>
						    <div class="clear"></div>
					    </div>
					</form>
					</div>
					<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
					<!--End mc_embed_signup-->
				</div>
				<ul class="form-list">
					<li class="radio">
					    <label>
					      <input type="radio" name="signup" id="signup-kid" value="kid" checked="checked">
					      Kid
					    </label>
					</li>
					<li class="radio">
					    <label>
					      <input type="radio" name="signup" id="signup-men" value="men">
					      Men
					    </label>
					</li>
					<li class="radio">
					    <label>
					      <input type="radio" name="signup" id="signup-women" value="women">
					      Women
					    </label>
					</li>
				</ul>
				
				<script type="application/javascript">
				    jQuery(document).ready(function() {
				        jQuery('input[type=radio][name=signup]').change(function() {
				            if (this.value == 'kid') {
				                jQuery('.form_kid').fadeIn();
				                jQuery('.form_men').fadeOut();
				                jQuery('.form_women').fadeOut();
				            }
				            else {
				            	if (this.value == 'men') {
				                jQuery('.form_kid').fadeOut();
				                jQuery('.form_men').fadeIn();
				                jQuery('.form_women').fadeOut();
				            	}
				                else if (this.value == 'women') {
					                jQuery('.form_kid').fadeOut();
					                jQuery('.form_men').fadeOut();
					                jQuery('.form_women').fadeIn();
					            }
				            
				            }
				        });
				    });

				</script>
			</div>
			<div class="grid_3">
				<span>
					ĐĂNG KÝ EMAIL ĐỂ CẬP NHẬT ƯU ĐÃI VÀ SẢN PHẨM MỚI HÀNG NGÀY TỪ  BEAUTYZONE.VN
				</span>
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<?php if ($footer_status == 1): ?>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($footer_static)->toHtml() ?>
	<?php else: ?>
		<div class="footer-bottom-wrapper">
			<div class="container_12">
				<div class="row clearfix">
					<div class="grid_12">
						<address><?php echo $this->getCopyright(); ?></address>
					</div>
					<div class="clear"></div>
				</div>
			</div>
		</div>
	<?php endif; ?>
</footer>