<link href="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/reports/lib/css.css" rel="stylesheet">
<link href="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/reports/lib/dark.css" rel="stylesheet">
<link href="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/reports/lib/blue.css" rel="stylesheet">    
<script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/reports/lib/js"></script>
<script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/reports/lib/js_003"></script>        

<!-- charts -->
<script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/reports/lib/charts/highcharts.js"></script>
<script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/reports/lib/charts/highcharts-3d.js"></script>
<script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/reports/lib/charts/modules/exporting.js"></script>
