
<div class="block-megamenu sub-menu" style="border:<?php echo $this->getCustomStyle('border_size')?>px solid #<?php echo $this->getCustomStyle('border_color')?> !important;background:#<?php if($this->getCustomStyle('background_color')){ echo $this->getCustomStyle('background_color'); }else{echo 'ffffff';}?> !important;width:100%"  id="menu1"  >
    <?php if($this->getTemplateBlock($this->getHeaderContent())== '') { ?>
        <div>
        </div>
    <?php } else { ?>
    <div class="header-megamenu" style="color:#<?php echo $this->getCustomStyle('text_color'); ?>;font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px;">
        <?php echo $this->getTemplateBlock($this->getHeaderContent()) ?>
    </div>
    <?php } ?>
    <div class = "footer-megamenu" style = "color:#<?php echo $this->getCustomStyle('text_color'); ?>;font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px;"><?php echo $this->getTemplateBlock($this->getFooterContent()) ?></div>
</div>

<?php
$_template_map = '<div class="content-only">';
$_template_map .= '<div class="megamenu-template-map-content-only">';
$_template_map .= '<div class="layout-nav">';
$_template_map .= '</div>';
$_template_map .= '<div class="megamenu-template-map-header-content-only">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#buttonsheader"><span>Header</span></a>';
$_template_map .= '<div>&nbsp;</div></div>';
$_template_map .= '<div class="megamenu-template-map-footer-content-only">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#buttonsfooter"><span>Footer</span></a>';
$_template_map .= '<div>&nbsp;</div></div>';
$_template_map .= '</div></div>';
?>
<?php
$header = '<ul class="block-home">
						<li class="first" style="border-color:#d5d5d5;width:320px !important">
							<label style="font-size:11px;color:#000;border-bottom-color:#d5d5d5;">Picture</label>
							<img  src="{{media url="megamenu/home.png"}}"  width="310" height="195" />
						</li>
						<li class="last" style="width:515px !important">
							<label style="font-size:11px;color:#000;border-bottom-color:#d5d5d5;">About us</label>
							<span style="color:#666;font-size:12px;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span>
							<button class="button">View Detail</button>
						</li>
					</ul>';
$footer = '';
$this->setDefaultHeaderFooter($header, $footer);
$this->setDefaultGeneralStyle('#ffffff', '#D5D5D5', 1); // (background_color, border_color, title_font, title_font_size)
$this->setDefaultTitleStyle('#ffffff', '#000000','Arial,Helmet,Freesans,sans-serif',11); // (title_color, title_background_color, title_font, title_font_size)
$this->setDefaultSubtitleStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 11); // (subtitle_color, subtitle_font, subtitle_font_size)
$this->setDefaultLinkStyle('#000000', '#3f58a3', 'Arial,Helmet,Freesans,sans-serif', 11); // (link_color, hover_color, link_font, link_font_size)
$this->setDefaultTextStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 12); // (text_color, text_font, text_font_size)
$this->setDefaultContentGeneral(940,0,0);// megamenu_size,column_number,column_size
/* add title */
$this->addTitle('Categories');
/* add map */
$this->setTemplateMap($_template_map)
?>
