<div class="block-megamenu sub-menu" style="border:<?php echo $this->getCustomStyle('border_size')?>px solid #<?php echo $this->getCustomStyle('border_color')?> !important;background:#<?php if($this->getCustomStyle('background_color')){ echo $this->getCustomStyle('background_color'); }else{echo 'ffffff';}?> !important;width:<?php if ($this->getMegamenuSize()){echo $this->getMegamenuSize();}else{ echo '750';}?>px !important"  id="menu1"  >
    <?php echo $this->getTemplateBlock($this->getHeaderContent()) ?>
     <?php echo $this->getTemplateBlock($this->getFooterContent()) ?>
</div>
<?php
$_template_map = '<div class="megamenu-template-map-content-only news-content">';
$_template_map .= '<div class="layout-nav">';
$_template_map .= '</div>';
$_template_map .= '<div class="megamenu-template-map-header-content-only">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#buttonsheader"><span>Header</span></a>';
$_template_map .= '<div>&nbsp;</div></div>';
$_template_map .= '<div class="megamenu-template-map-footer-content-only">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#buttonsfooter"><span>Footer</span></a>';
$_template_map .= '<div>&nbsp;</div></div>';
$_template_map .= '</div>';
?>
<?php
$header = '<ul class="whatnew">
            <li>
            <h1>Womens Lastest</h1>
            <ol>
                <li><a href="#"><span>New Arrival</span></a></li>
                <li><a href="#"><span>Online Exclusives<br /></span></a></li>
                <li><a href="#"><span>Pacsun vip card<br /></span></a></li>
                <li><a href="#"><span>Great deal</span></a></li>
                <li><a href="#"><span>Buyer ashley picks</span></a></li>
                <li><a href="#"><span>top 20 under $20</span></a></li>
                <li><a href="#"><span>360 look book<br /></span></a></li>
            </ol></li>
            <li>
            <h1>Womens new offer</h1>
            <ol>
                <li><a href="#"><span>Apparel</span></a></li>
                <li><a href="#"><span>Buy 1 get 1 50%</span></a></li>
                <li><a href="#"><span>Accessorier and foot wear<br /></span></a></li>
                <li><a href="#"><span>Buy 1 get 1 50%</span></a></li>
                <li><a href="#"><span>Shop all</span></a></li>
                <li><a href="#"><span>Buy 1 get 1 50%</span></a></li>
            </ol></li>
            <li>
                <h1>Mens Lastest</h1>
                <ol>
                    <li><a href="#"><span>New&nbsp; Arrival</span></a></li>
                    <li><a href="#"><span>Online Exclusives<br /></span></a></li>
                    <li><a href="#"><span>Pacsun vip card</span></a></li>
                    <li><a href="#"><span>Great deal</span></a></li>
                    <li><a href="#"><span>Swim shop</span></a></li>
                    <li><a href="#"><span>Sandal</span></a></li>
                    <li><a href="#"><span>Snap back</span></a></li>
                </ol>
            </li>
            <li>
            <h1>Mens New offer</h1>
            <ol>
                <li><a href="#"><span>Apparel</span></a></li>
                <li><a href="#"><span>Buy 1 get 1 50%</span></a></li>
                <li><a href="#"><span>Accessorier and foot wear<br /></span></a></li>
                <li><a href="#"><span>Buy 1 get 1 50%</span></a></li>
                <li><a href="#"><span>Shop all</span></a></li>
                <li><a href="#"><span>Buy 1 get 1 50%</span></a></li>
            </ol></li>
            <li>
            <h1>Check it out</h1>
            <a href="#"><img src="{{media url=\"Check-it-out.gif\"}}" alt="" /></a></li>
        </ul>';
$footer = '';
$this->setDefaultHeaderFooter($header,$footer);
$this->setDefaultGeneralStyle('#ffffff', '#D5D5D5', 1); // (background_color, border_color, title_font, title_font_size)
$this->setDefaultTitleStyle('#ffffff', '#000000','Arial,Helmet,Freesans,sans-serif',11); // (title_color, title_background_color, title_font, title_font_size)
$this->setDefaultSubtitleStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 11); // (subtitle_color, subtitle_font, subtitle_font_size)
$this->setDefaultLinkStyle('#000000', '#3f58a3', 'Arial,Helmet,Freesans,sans-serif', 11); // (link_color, hover_color, link_font, link_font_size)
$this->setDefaultTextStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 12); // (text_color, text_font, text_font_size)
$this->setDefaultContentGeneral(750,0,0);// megamenu_size,column_number,column_size
/* add title */
$this->addTitle('Categories');
/* add map */
$this->setTemplateMap($_template_map)
?>
<style type="text/css">
    .megamenu #nav  ul.whatnew{
	width:100% !important;
	float:left !important;
	position:static !important;
	background:#fff !important;
	}
.megamenu #nav  ul.whatnew li{
	float:left !important;
	max-width:175px !important;
	padding:5px !important;
	width:25% !important;	
	}
.megamenu #nav  ul.whatnew ol {
	float:left !important;
	border-right:1px solid #d6d6d6 !important;
	height:185px !important;
	overflow:hidden !important;
	width:100% !important;
	}
.megamenu #nav  ul.whatnew ol li{
	float:left !important;
	width:100% !important;
	padding:5px  0 0 !important;
}
.megamenu #nav ul.whatnew li h1{
	font-size:11px !important;
	font-weight:bold !important;
	border-bottom:1px dashed #ded7d3 !important;
	text-transform:uppercase !important;
	padding:0 0 5px 2px !important;
	float:left !important;
	width:95% !important;
}
.megamenu #nav ul.whatnew li  a{
	float:left !important;
	line-height:normal !important;
	padding:0 !important;
	}
</style>
