<?php
$requestData = Mage::helper('adminhtml')->prepareFilterString($this->getRequest()->getParam('top_filter'));
$warehouseId = $supplierId = $datefrom = $dateto = '';
if (isset($requestData['warehouse_select']))
    $warehouseId = $requestData['warehouse_select'];
if (isset($requestData['supplier_select']))
    $supplierId = $requestData['supplier_select'];
if (isset($requestData['date_from']))
    $datefrom = $requestData['date_from'];
if (isset($requestData['date_to']))
    $dateto = $requestData['date_to'];
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>

<form method="POST" id="supplyneeds_form_submit" action="<?php echo Mage::helper("adminhtml")->getUrl('inventorypurchasingadmin/adminhtml_purchaseorder/new', array('_current' => true)) ?>"
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Select criteria to forecast supply needs') ?></h4>
        </div>
        <div id="date_picker_form" class="fieldset ">
            <div  class="input-box">
                <table cellspacing="0">
                    <tr>
                        <td><label><?php echo $this->__('To:') ?></label>
                            &nbsp; &nbsp;
                            <input name="date_to" id="date_to" type="text" onchange="checkDateTo()" size="30" value="<?php echo $dateto; ?>">
                            <img title="Date to" id="btn-date-to" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'adminhtml/default/default/images/grid-cal.gif'; ?>" class="v-middle">
                            &nbsp; &nbsp;
                        </td>
                        <td>&nbsp;<label style="font-size:13px"><?php echo $this->__('Warehouse') ?></label></td>
                        <td>&nbsp;<label style="font-size:13px"><?php echo $this->__('') ?></label>&nbsp;</td>
                        <td>
                            <select name="warehouse_select" id="warehouse_select" style="width: 120px" onchange="filterForm();return false;">
                                <option value=""><?php $this->__('All') ?></option>
                                <?php
                                $warehouses = Mage::helper('inventorypurchasing/purchaseorder')->getWarehouseOption();
                                if($warehouses)
                                    foreach ($warehouses as $warehouse) {
                                        if ($warehouse['value'] == $warehouseId):
                                            ?>
                                            <option selected value="<?php echo $warehouse['value'] ?>"><?php echo $warehouse['label']; ?></option>
                                        <?php else: ?>
                                            <option value="<?php echo $warehouse['value'] ?>"><?php echo $warehouse['label']; ?></option>   
                                        <?php endif; ?>
                                    <?php } ?>

                            </select>
                            &nbsp; &nbsp;
                        </td>

                        <td>&nbsp;<label style="font-size:13px"><?php echo $this->__('Supplier') ?></label></td>
                        <td>&nbsp;<label style="font-size:13px"><?php echo $this->__('') ?></label>&nbsp;</td>
                        <td>
                            <select name="supplier_select" id="supplier_select" style="width: 120px" onchange="filterForm();return false;">
                                <option value=""><?php $this->__('All') ?></option>
                                <?php
                                $model = Mage::getModel('inventorypurchasing/supplier');
                                $collection = $model->getCollection();
                                foreach ($collection as $supplier) {
                                    if ($supplier->getId() == $supplierId):
                                        ?>  
                                        <option selected value="<?php echo $supplier->getId() ?>"><?php echo $supplier->getSupplierName(); ?></option>
                                    <?php else: ?>
                                        <option value="<?php echo $supplier->getId() ?>"><?php echo $supplier->getSupplierName(); ?></option>
                                    <?php endif; ?>
                                <?php } ?>

                            </select>
                            <input type="hidden" name="product_list" id="product_list" value="" />
                            <button onclick="filterForm();return false;" ><?php echo $this->__('Show Supply Needs'); ?></button>
                            <input id="form_key" name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>">
                        </td>

                    </tr>
                </table>
            </div>
        </div>
        
        <?php //currency for purchase order ?>
        <?php if($warehouses): ?>
            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Select currency when create Purchase Order') ?></h4>
            </div>
            <div id="date_picker_form" class="fieldset ">
                <div  class="input-box">
                    <table cellspacing="0">
                        <tr>
                            <td style="padding-right:15px;">
                                <label><?php echo $this->__('Currency:') ?><span class="required">*</span></label>                                                        
                                <select class="required-entry select" name="currency" id="currency">
                                    <?php foreach(Mage::app()->getLocale()->getOptionCurrencies() as $currency): ?>
                                    <option value="<?php echo $currency['value'] ?>"><?php echo $currency['label'] ?></option>
                                    <?php endforeach ?>
                                </select>     
                                <script type="text/javascript">
                                    if($('currency'))
                                        $('currency').value = '<?php echo Mage::app()->getStore()->getBaseCurrencyCode() ?>';
                                </script>
                            </td>
                            <td>
                                <label><?php echo $this->__('Currency Exchange Rate:') ?><span class="required">*</span></label>                            
                                <input type="text" class="required-entry input-text required-entry" value="" name="change_rate" id="change_rate">                            
                                <div id="change_rate_comment" style="font-weight: bold;"></div>
                                <script type="text/javascript">
                                    var base_currency = '<?php echo Mage::app()->getStore()->getBaseCurrencyCode() ?>';
                                    var select_currency = $('currency').value;
                                    var change_rate = $('change_rate').value;
                                    if(!change_rate){
                                        $('change_rate').value = 1;
                                    }
                                    var comment = '(1 '+ base_currency +' = '+ $('change_rate').value +' '+select_currency +')';
                                    $('change_rate_comment').innerHTML = comment;
                                </script>
                            </td>                        
                        </tr>
                        <script type="text/javascript">
                            Event.observe('currency', 'change', function() {
                                var base_currency = '<?php echo Mage::app()->getStore()->getBaseCurrencyCode() ?>';
                                var select_currency = $('currency').value;
                                var change_rate = $('change_rate').value;
                                var comment = '(1 '+ base_currency +' = ' + change_rate +' ' +select_currency +')';
                                $('change_rate_comment').innerHTML = comment;					
                            });	

                            Event.observe('change_rate', 'change', function() {
                                var base_currency = '<?php echo Mage::app()->getStore()->getBaseCurrencyCode() ?>';
                                var select_currency = $('currency').value;
                                var change_rate = $('change_rate').value;
                                var comment = '(1 '+ base_currency +' = ' + change_rate +' ' +select_currency +')';
                                $('change_rate_comment').innerHTML = comment;					
                            });		
                        </script>
                    </table>
                </div>
            </div>
        <?php endif ?>
    </div>
</form>

<div>
    <?php echo $this->getGridHtml() ?>
</div>

<script type="text/javascript">
    //<![CDATA[
Calendar.setup({
    inputField : 'date_to',
    ifFormat : "%d-%m-%Y",
    daFormat : "%d-%m-%Y",
    button : 'btn-date-to',
    align : 'Bl',
    singleClick : true,
    disableFunc: function(date) {
        var now= new Date();
        if(date.getFullYear()<now.getFullYear())
        {
            return true;
        }
        if(date.getFullYear()==now.getFullYear())
        {
            if(date.getMonth()<now.getMonth())
            {
                return true;
            }
        }
        if(date.getMonth()==now.getMonth())
        {
            if(date.getDate()<now.getDate()-1)
            {
                return true;
            }
        }
    }
});
    
function filterForm() {
    var filters = new Array();
    filters[1] = $('date_to');
    filters[2] = $('warehouse_select');
    filters[3] = $('supplier_select');
    var elements = [];
    for(var i in filters){
        if(filters[i].value && filters[i].value.length && !filters[i].disabled) elements.push(filters[i]);
    }
    var validator  = new Validation('supplyneeds_form_submit');
    if (validator.validate()) {
        window.location.href = '<?php echo $this->getUrl('inventorysupplyneedsadmin/adminhtml_inventorysupplyneeds/index'); ?>top_filter/'+encode_base64(Form.serializeElements(elements))+'/';
    }
    return;
}
    
function createPurchaseOrder(){
    if($('supplier_select').value == ''){
        alert('<?php echo $this->__('Please select a supplier before creating a new purchase order.') ?>');
        return false;
    }
    //url = '<?php echo Mage::helper("adminhtml")->getUrl('inventorypurchasingadmin/adminhtml_purchaseorders/new'); ?>';
    url = '<?php echo Mage::helper("adminhtml")->getUrl('inventorysupplyneedsadmin/adminhtml_inventorysupplyneeds/createpurchase'); ?>';
    $('supplyneeds_form_submit').action = url;
    supplyNeedsGrid.storeLogInTargetInput();    
    if($('product_list').value){
        if($('currency'))
            if(!$('currency').value){
                alert('<?php echo $this->__('Please select Currency to create Purchase Order') ?>');
                return false;
            }
        if($('change_rate'))
            if(!$('change_rate').value){
                alert('<?php echo $this->__('Please fill Currency Exchange Rate to create Purchase Order') ?>')
                return false;
            }
        if($('loading-mask'))
            $('loading-mask').style.display = 'block';
        $('supplyneeds_form_submit').submit();
    }else{
        alert('<?php echo $this->__('Please enter Qty. needed purchasing for 1 product at least!') ?>');
        return false;
    }
}
    
function exportCsv(){
    url = $('supplyneeds_form_submit').action+'export/1';
    $('supplyneeds_form_submit').action = url;
    supplyNeedsGrid.storeLogInTargetInput();
    if($('product_list').value){
        $('supplyneeds_form_submit').submit();
    }else{
        alert('<?php echo $this->__('Please enter QTY for 1 product at least!') ?>');
    }       
}
    
function checkDateFrom(){
    var now = new Date();
    var picked = $('date_from').value;
    var data = picked.split("-");
    var newdate = data[2] + "-" + data[1] + '-' +data[0];
    var pick = new Date(newdate);
    if(pick.getFullYear()<now.getFullYear())
    {
        alert('Wrong date picked');
        $('date_from').value = '';
    }
    if(pick.getFullYear()==now.getFullYear())
    {
        if(pick.getMonth()<now.getMonth())
        {
            alert('<?php echo $this->__('Invalid selected time. Please choose a current or future date.') ?>');
            $('date_from').value = '';
        }
    }
    if(pick.getMonth()==now.getMonth())
    {
        if(pick.getDate()<now.getDate()-1)
        {
            alert('<?php echo $this->__('Wrong date picked') ?>');
            $('date_from').value = '';
        }
    }
}
    
function checkDateTo(){
    var now = new Date();
    var picked = $('date_to').value;
    var data = picked.split("-");
    var newdate = data[2] + "-" + data[1] + '-' +data[0];
    var pick = new Date(newdate);
    if(pick.getFullYear()<now.getFullYear())
    {
        alert('<?php echo $this->__('Wrong date picked') ?>');
        $('date_to').value = '';
    }
    if(pick.getFullYear()==now.getFullYear())
    {
        if(pick.getMonth()<now.getMonth())
        {
            alert('<?php echo $this->__('Wrong date picked') ?>');
            $('date_to').value = '';
        }
    }
    if(pick.getMonth()==now.getMonth())
    {
        if(pick.getDate()<now.getDate()-1)
        {
            alert('<?php echo $this->__('Wrong date picked') ?>');
            $('date_to').value = '';
        }
    }
}
</script>