<style>
    .megamenu #nav-toggle ul.block-contact{
        width: 98% !important;
        padding: 10px 1% !important;
    }
    .megamenu #nav-toggle ul.block-contact li{
        width: 100% !important;
        padding: 0px !important;
    }
    .megamenu #nav-toggle ul.block-contact li form#contactForm{
        width: 100%;
        padding: 0px !important;
    }
    .megamenu #nav-toggle ul.block-contact h1.block-title {
        border-top: none !important;
    }
</style>

<div class="block-megamenu sub-menu" 
     style="width:100% !important;
     border:<?php echo $this->getCustomStyle('border_size')?>px solid #<?php echo $this->getCustomStyle('border_color')?> !important;
     background:#<?php if($this->getCustomStyle('background_color')){ echo $this->getCustomStyle('background_color'); }else{echo 'ffffff';}?> !important;"  id="menu1"  >
    <ul class="block-contact">
        <li class="last">
            <h1 class="block-title" style="color:#000;font-size:11px;">Contact Form</h1>
            <div class="header-megamenu" 
                style=" color:#<?php echo $this->getCustomStyle('text_color'); ?> !important;
                        font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px !important;
                        font-family: <?php echo $this->getCustomStyle('text_font'); ?> !important;">
                <?php echo $this->getTemplateBlock($this->getHeaderContent()) ?>
            </div>
            <form action="<?php echo $this->getUrl('contacts/index/post') ?>" id="contactForm" method="post">
                <div class="contact-form">								
                    <div class="input-box">
                        <div class="input">
                            <label style="color:#000;font-size:11px;">Your name</label>
                            <input type="text" class="required-entry"  name="name" id="name" value="" title="Your name" />
                        </div>
                        <div class="input">
                            <label style="color:#000;font-size:11px;">Your email</label>
                            <input type="email" class="validate-email" value="" name="email" id="email" title="Your email" />
                        </div> 
                        <div class="input">
                            <label style="color:#000;font-size:11px;">Telephone</label>
                            <input type="" class="validate-number" value="" title="Telephone" name="telephone" id="telephone"/>
                        </div>
                    </div>
                    <div class="comment">
                        <label style="color:#000;font-size:11px;">Comment</label>
                        <textarea  type="text" value="" name="comment" value="comment"></textarea>
                        <div class="button-set">
                            <button class="button" type="submit">Submit</button>
                        </div>
                    </div>
                </div>
            </form>
            <div class="footer-megamenu" 
                 style="color:#<?php echo $this->getCustomStyle('text_color'); ?> !important;;
                       font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px !important;;
                       font-family: <?php echo $this->getCustomStyle('text_font'); ?> !important;">
                <?php echo $this->getTemplateBlock($this->getFooterContent()) ?>
           </div>
        </li>
    </ul>
</div>
<script type="text/javascript">
//< ![CDATA[
var contactForm = new VarienForm('contactForm');
//]]>
</script>
<?php
$_template_map = '<div class="megamenu-template-contact">';
$_template_map .= '<div class="layout-nav">';
$_template_map .= '</div>';
$_template_map .= '<div id="layout_header">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#buttonsheader">Header</a>';
$_template_map .= '<div>&nbsp;</div></div>';
$_template_map .= '<div class="megamenu-template-map-main-content-only">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href=""><span>Main Content</span></a>';
$_template_map .= '<div>&nbsp;</div></div>';
$_template_map .= '<div class="megamenu-template-map-footer-content-only">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#buttonsfooter"><span>Footer</span></a>';
$_template_map .= '<div>&nbsp;</div></div>';
$_template_map .= '</div>';
?>
<?php
$header = 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.';
$footer = 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.';
$this->setDefaultGeneralStyle('#ffffff', '#D5D5D5', 1); // (background_color, border_color, title_font, title_font_size)
$this->setDefaultTitleStyle('#ffffff', '#000000','Arial,Helmet,Freesans,sans-serif',11); // (title_color, title_background_color, title_font, title_font_size)
$this->setDefaultSubtitleStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 11); // (subtitle_color, subtitle_font, subtitle_font_size)
$this->setDefaultLinkStyle('#000000', '#3f58a3', 'Arial,Helmet,Freesans,sans-serif', 11); // (link_color, hover_color, link_font, link_font_size)
$this->setDefaultTextStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 12); // (text_color, text_font, text_font_size)
//$this->setDefaultContentGeneral(660,0,0);// megamenu_size,column_number,column_size
/* add title */
$this->addTitle('Categories');
/* add map */
$this->setTemplateMap($_template_map)
?>
