<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<?php
	echo $this->getDesignStyles();
	$package = Mage::getDesign()->getPackageName();
	$theme = Mage::getDesign()->getTheme('frontend');
?>
<div class="opc-wrapper-opc design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">
	<div class="page-title">
		<h2 class="opc-title"><?php echo $this->__('Checkout')?></h2>
	</div>
	<div class="opc-menu">
		<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
			<?php echo $this->getChildHtml('login');?>
		<?php endif;?> 
		<?php echo $this->getChildHtml('paypal.button')?>
	   <div class="clear move-columns"></div>
	</div>
	<div class="clear"></div>
	<div class="opc-col-left">
		<div class="indent">
			<form id="opc-address-form-billing" method="post">
				<?php echo $this->getChildHtml('billing')?>
			</form>
			<form id="opc-address-form-shipping" class="hidden" method="post">
			<?php echo $this->getChildHtml('shipping')?>
			</form>
		</div>
	</div>
	<div class="opc-col-center">
		<div class="indent">
			<?php if (!$this->getOnepage()->getQuote()->isVirtual()):?>
			<div class="shipping-block">
				<div class="opc-block-title">
					<h3><?php echo $this->__('Shipping Method')?></h3>
				</div>
				<div id="shipping-block-methods">
					<?php echo $this->getChildHtml('shipping_method');//$this->_getShippingMethodsHtml();?>
				</div>
			</div>
			<?php endif;?>
			<div class="payment-block <?php if ($this->getOnepage()->getQuote()->isVirtual()):?>clear-margin<?php endif;?>">
				<div class="opc-block-title">
					<h3><?php echo $this->__('Payment Method')?></h3>
				</div>
				<?php echo $this->getChildHtml('payment')//$this->_getPaymentMethodsHtml();?>
			</div>
			<?php if(Mage::helper('opc')->isShowDiscount()):?>
				<div class="discount-block">
					<div class="opc-block-title">
						<h3><?php echo $this->__('Discount Codes')?></h3>
					</div>
					<?php echo $this->getChildhtml('coupon');?>
				</div>
			<?php endif;?>
			<?php if(Mage::helper('opc')->isShowComment()):?>
				<?php echo $this->getChildhtml('customer.comment');?>
			<?php endif;?>
			<?php if (Mage::getConfig()->getModuleConfig('IWD_OnepageCheckoutSignature')->is('active', 'true')): ?>
				<div class="signature-block">
					<div class="opc-block-title">
						<h3><?php echo $this->__('Signature')?></h3>
					</div>
					<?php echo $this->getChildhtml('opcsignature');?>
				</div>
			<?php endif;?>
		</div>
	</div>
	<div class="opc-col-right">
		<div class="indent">
			<div class="opc-block-title">
				<h3><?php echo $this->__('Review Your Order')?></h3>
			</div>
			<div id="opc-review-block">
				<?php echo $this->_getReviewHtml()?>
			</div>
			<div class="opc-review-actions" id="checkout-review-submit">
				<?php echo $this->getChildHtml('agreements')?>
				<?php echo $this->getChildHtml('opc.newsletters');?>
				<button type="button" title="<?php echo $this->__('Place Order Now') ?>" class="button btn-checkout opc-btn-checkout"><span><span><?php echo $this->__('Place Order Now') ?></span></span></button>
			</div>
		</div>
	</div>
</div>
<script>
	var vopc = '<?php echo Mage::getConfig()->getModuleConfig("IWD_Opc")->version;?>';
	IWD.OPC.Checkout.config = '<?php echo $this->getJsonConfig()?>';
	<?php if ($this->getOnepage()->getQuote()->isVirtual()):?>
	IWD.OPC.Checkout.isVirtual = true;
	<?php endif;?>	 
</script>
<div id="agree_error" style="display:none !important;"><?php echo $this->__('Please agree to all the terms and conditions before placing the order.');?></div>
<div id="pssm_msg" style="display:none !important;"><?php echo $this->__('Please specify shipping method');?></div>
<div class="opc-ajax-loader">
	<div id="floatingCirclesG"><img src="<?php echo $this->getSkinUrl('images/fancybox/fancybox_loading.gif') ?>" alt="" /></div>
</div>
<div class="opc-message-wrapper design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">
	<div class="opc-messages">
		<a class="close-message-wrapper"></a>
		<div class="opc-message-container"></div>
		<div class="opc-messages-action"><button class="button"><span><span><?php echo $this->__('Close')?></span></span></button></div>
	</div>
</div>