<?php
$series = array();
$requestData = Mage::helper('adminhtml')->prepareFilterString($this->getRequest()->getParam('top_filter'));
if (empty($requestData)) {
    $requestData = Mage::Helper('inventoryreports')->getDefaultOptionsWarehouse();
}
$name = 'All Warehouses';
if ($requestData['warehouse_select'] > 0) {
    $name = Mage::helper('inventoryreports')->getWarehouseName($requestData['warehouse_select']);
}
$gettime = Mage::Helper('inventoryreports')->getTimeSelected($requestData);
$warehouse_name = array();
$item_shipped = array();
$resource = Mage::getSingleton('core/resource');
$readConnection = $resource->getConnection('core_read');
$installer = Mage::getModel('core/resource');
if (isset($requestData['warehouse_select']) && $requestData['warehouse_select'] > 0) {
    $is_warehouse = 1;
    $warehouse_collection = Mage::getModel('inventoryplus/warehouse')->load($requestData['warehouse_select']);
    $sql = 'SELECT w.warehouse_name, w.product_id, sum(w.qty_shipped) AS item_shipped, f.created_at
            FROM ' . $installer->getTableName("erp_inventory_warehouse_shipment w") . '
            INNER JOIN ' . $installer->getTableName("sales_flat_shipment f") . '
            ON w.order_id = f.order_id
            WHERE w.warehouse_id > 0 AND w.warehouse_name = "' . $warehouse_collection->getWarehouseName() . '" AND f.created_at BETWEEN "' . $gettime['date_from'] . '" AND "' . $gettime['date_to'] . '"
            GROUP BY w.product_id
            ORDER BY item_shipped DESC 
            ';
} else {
    $is_warehouse = 0;
    $sql = 'SELECT w.warehouse_name, SUM(w.qty_shipped) AS item_shipped, f.created_at
            FROM ' . $installer->getTableName("erp_inventory_warehouse_shipment w") . '
            INNER JOIN ' . $installer->getTableName("sales_flat_shipment f") . '
            ON w.order_id = f.order_id
            WHERE w.warehouse_id > 0 AND f.created_at BETWEEN "' . $gettime['date_from'] . '" AND "' . $gettime['date_to'] . '"
            GROUP BY w.warehouse_name
            ORDER BY item_shipped DESC ';
}
$results = $readConnection->fetchAll($sql);
if (isset($requestData['warehouse_select']) && $requestData['warehouse_select'] > 0) {
    $checkResult = 0;
    foreach ($results as $result) {
        if ($checkResult > 10) {
            $limit = 10;
            break;
        }
        if ($result['item_shipped'] == NULL || $result['item_shipped'] <= 0) {
            $limit = $checkResult;
            continue;
        }
        $checkResult++;
    }
    if (isset($limit)) {
        $sql .= 'LIMIT ' . $limit . '';
        $results = $readConnection->fetchAll($sql);
    }
}
if ($is_warehouse == 0) {
    foreach ($results as $result) {
        $warehouse_name[] = $result['warehouse_name'];
        $item_shipped[] = $result['item_shipped'];
    }
} else {
    foreach ($results as $result) {
        $warehouse_name[] = Mage::getModel('catalog/product')->load($result['product_id'])->getName();
        $item_shipped[] = $result['item_shipped'];
    }
}
$i = 0;
$categories = '[';
foreach ($warehouse_name as $name_value) {
    if ($i != 0) {
        $categories .= ',';
    }
    $categories .= '"' . $name_value . '"';
    $i++;
}
$categories .= ']';
//            Zend_debug::dump($categories);
$j = 0;
$series['inventory_warehouse']['name'] = $this->__('Item Shipped by Warehouse');
$series['inventory_warehouse']['data'] = '[';
foreach ($item_shipped as $number_value) {
    if ($j != 0) {
        $series['inventory_warehouse']['data'] .= ',';
    }
    $series['inventory_warehouse']['data'] .= $number_value;
    $j++;
}
$series['inventory_warehouse']['data'] .= ']';
//            Zend_debug::dump($series);    
?>
<?php if (count($results) > 0): ?>
    <div class="entry-edit" id="test">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Chart Report') ?></h4>
        </div>
        <!DOCTYPE HTML>
        <div>
            <div style="width: 99%; float: left;">
                <script type="text/javascript">
                    $(function () {
                        $_('#inventorybywarehouse_column').highcharts({
                        chart: {
                        type: 'column',
                                margin: 70,
                                options3d: {
                                enabled: true,
                                        alpha: 20,
                                        beta: 1,
                                        depth: 50
                                }
                        },
                                legend:{
                                enabled:false,
                                },
                                title: {
                                text: '<?php echo $this->__('Item Shipped by Warehouse: "' . $name . '"') ?>'
                                },
                                plotOptions: {
                                column: {
                                depth: 30
                                }
                                },
                                xAxis: {
                                categories: <?php echo $categories ?>
                                },
                                yAxis: {
                                opposite: true
                                },
                                series: [
    <?php $count = 0; ?>
    <?php foreach ($series as $serie): ?>
        <?php if (!$count == 0) echo ','; ?>
        <?php $count++; ?>
                                    {
                                        name: '<?php echo $serie['name']; ?>',
                                                data: <?php echo $serie['data']; ?>
                                        }
    <?php endforeach; ?>
                                    ]
                        }
                        );
                    });
                </script>

                <div id="inventorybywarehouse_column" style="min-width: 900px; height: 450px; margin: 0 auto"></div>
            </div>


            <!-- report by warehouse pie -->
            <div style="width: 99%; float: left;">
                <?php
                $series = '';
                $i = 0;
                if ($is_warehouse == 0) {
                    foreach ($results as $result) {
                        if ($i != 0)
                            $series .= ',';
                        $series .= '[\'' .$result['warehouse_name'] . '(' . $result['item_shipped'] . ' items shipped)\',' . $result['item_shipped'] . ']';
                        $i++;
                    }
                }
                else {
                    foreach ($results as $result) {
                        if ($i != 0)
                            $series .= ',';
                        $series .= '[\'' . substr(Mage::getModel('catalog/product')->load($result['product_id'])->getName(), 0, 11) . '(' . $result['item_shipped'] . ' items shipped)\',' . $result['item_shipped'] . ']';
                        $i++;
                    }
                }
                ?>

                <script type="text/javascript">
                    $(function () {
                        $_('#inventorybywarehouse_pie').highcharts({
                            chart: {
                                type: 'pie',
                                options3d: {
                                    enabled: true,
                                    alpha: 50
                                }
                            },
                            title: {
                                text: '<?php echo $this->__('Item Shipped by Warehouse: "' . $name . '"') ?>',
                            },
                            plotOptions: {
                                pie: {
                                    depth: 30
                                }
                            },
                            series: [{
                                    data: [
    <?php echo $series; ?>
                                    ]
                                }]
                        });
                    });
                </script>
                <div id="inventorybywarehouse_pie" style="min-width: 900px; max-height: 450px; margin: 0 auto"></div>
            </div>
        </div>          
    </div>
<?php endif; ?>




<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/_JSSettings.js"></script>
<script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/js_002"></script>
<script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/dashboards"></script>

<script type="text/javascript">
                var saveViewPositions = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/saveviewposition') ?>';
                var saveTabPositions = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/savetabposition') ?>';
                var form_key_dashboard = '<?php echo $this->getFormKey() ?>';</script>
<script type="text/javascript">
    var $sd = new InventoryDashboard.Views.Dashboards();
    $sd.isShare = false;
    $sd.backgroundColour = '#808080';
    $sd.init();
</script>