<?php
$series = array();
$requestData = Mage::helper('adminhtml')->prepareFilterString($this->getRequest()->getParam('top_filter'));
if (empty($requestData)) {
    $requestData = Mage::Helper('inventoryreports')->getDefaultOptionsWarehouse();
}
$name = 'All Warehouses';
if ($requestData['warehouse_select'] > 0) {
    $name = Mage::helper('inventoryreports')->getWarehouseName($requestData['warehouse_select']);
}
$gettime = Mage::Helper('inventoryreports')->getTimeSelected($requestData);
$warehouse_name = array();
$total_adjust = array();
$resource = Mage::getSingleton('core/resource');
$readConnection = $resource->getConnection('core_read');
$installer = Mage::getModel('core/resource');
if (isset($requestData['warehouse_select']) && $requestData['warehouse_select'] > 0) {
    $is_warehouse = 1;
    $prodNameAttrId = Mage::getModel('eav/entity_attribute')
            ->loadByCode('4', 'name')
            ->getAttributeId();
    $warehouse_collection = Mage::getModel('inventoryplus/warehouse')->load($requestData['warehouse_select']);
    $sql = 'SELECT f.value as warehouse_name, SUM(p.adjust_qty) AS total_adjust
            FROM ' . $installer->getTableName("erp_inventory_adjuststock a ") . '
            LEFT JOIN ' . $installer->getTableName("erp_inventory_adjuststock_product p ") . '
            ON a.adjuststock_id = p.adjuststock_id
            LEFT JOIN ' . $installer->getTableName("catalog_product_entity_varchar f") . '
            ON p.product_id = f.entity_id AND f.attribute_id=' . $prodNameAttrId . '
            WHERE a.warehouse_id = "' . $requestData['warehouse_select'] . '" AND a.status = 1 AND a.confirmed_at BETWEEN "' . $gettime['date_from'] . '" AND "' . $gettime['date_to'] . '" AND a.warehouse_id = ' . $requestData['warehouse_select'] . '
            GROUP BY p.product_id
            ORDER BY SUM(p.adjust_qty) DESC
            ';
} else {
    $is_warehouse = 0;
    $sql = 'SELECT a.warehouse_name, SUM(p.adjust_qty) AS total_adjust
            FROM ' . $installer->getTableName("erp_inventory_adjuststock a ") . '
            INNER JOIN ' . $installer->getTableName("erp_inventory_adjuststock_product p ") . '
            ON a.adjuststock_id = p.adjuststock_id
            WHERE a.status = 1 AND a.confirmed_at BETWEEN "' . $gettime['date_from'] . '" AND "' . $gettime['date_to'] . '"
            GROUP BY a.warehouse_name
            ORDER BY SUM(p.adjust_qty) DESC
            ';
}
$results = $readConnection->fetchAll($sql);
if (isset($requestData['warehouse_select']) && $requestData['warehouse_select'] > 0) {
    $checkResult = 0;
    foreach ($results as $result) {
        if ($checkResult > 10) {
            $limit = 10;
            break;
        }
        if ($result['total_adjust'] == NULL || $result['total_adjust'] <= 0) {
            $limit = $checkResult;
            continue;
        }
        $checkResult++;
    }
    if (isset($limit)) {
        $sql .= 'LIMIT ' . $limit . '';
        $results = $readConnection->fetchAll($sql);
    }
}

foreach ($results as $result) {
    $warehouse_name[] = $result['warehouse_name'];
    $total_adjust[] = $result['total_adjust'];
}
$i = 0;
$categories = '[';
foreach ($warehouse_name as $name_value) {
    if ($i != 0) {
        $categories .= ',';
    }
    $categories .= '"' . $name_value . '"';
    $i++;
}
$categories .= ']';
//            Zend_debug::dump($categories);
$j = 0;
$series['inventory_warehouse']['name'] = $this->__('Total Qty Adjuststock');
$series['inventory_warehouse']['data'] = '[';
foreach ($total_adjust as $adjust_value) {
    if ($adjust_value > 0) {
        if ($j != 0) {
            $series['inventory_warehouse']['data'] .= ',';
        }
        $series['inventory_warehouse']['data'] .= $adjust_value;
        $j++;
    }
}
$series['inventory_warehouse']['data'] .= ']';
//    Zend_debug::dump($series);die();    
?>
<?php if (count($results) > 0): ?>
    <div class="entry-edit" id="test">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Chart Report') ?></h4>
        </div>
        <!DOCTYPE HTML>
        <div>
            <div style="width: 99%; float: left;">
                <script type="text/javascript">
                    $(function () {
                    $_('#inventorybywarehouse_column').highcharts({
                    chart: {
                    type: 'column',
                            margin: 70,
                            options3d: {
                            enabled: true,
                                    alpha: 20,
                                    beta: 1,
                                    depth: 50
                            }
                    },
                            legend:{
                            enabled:false,
                            },
                            title: {
                            text: '<?php echo $this->__('Total Qty Adjuststock by Warehouse: "' . $name . '"') ?>'
                            },
                            plotOptions: {
                            column: {
                            depth: 30
                            }
                            },
                            xAxis: {
                            categories: <?php echo $categories ?>
                            },
                            yAxis: {
                            opposite: true
                            },
                            series: [
    <?php $count = 0; ?>
    <?php foreach ($series as $serie): ?>
        <?php if (!$count == 0) echo ','; ?>
        <?php $count++; ?>
                                {
                                name: '<?php echo $serie['name']; ?>',
                                        data: <?php echo $serie['data']; ?>
                                }
    <?php endforeach; ?>
                            ]
                    }
                    );
                    });</script>
                <div id="inventorybywarehouse_column" style="min-width: 900px; height: 450px; margin: 0 auto"></div>
            </div>


            <!-- report by warehouse pie -->
            <div style="width: 99%; float: left;">
                <?php
                $series = '';
                $i = 0;
                foreach ($results as $result) {
                    if ($result['total_adjust'] > 0) {
                        if ($i != 0)
                            $series .= ',';
                        $series .= '[\'' . $result['warehouse_name'] . '(' . $result['total_adjust'] . ' items)\',' . $result['total_adjust'] . ']';
                        $i++;
                    }
                }
                ?>

                <script type="text/javascript">
                            $(function () {
                            $_('#inventorybywarehouse_pie').highcharts({
                            chart: {
                            type: 'pie',
                                    options3d: {
                                    enabled: true,
                                            alpha: 50
                                    }
                            },
                                    title: {
                                    text: '<?php echo $this->__('Total Qty Adjuststock by Warehouse: "' . $name . '"') ?>'
                                    },
                                    plotOptions: {
                                    pie: {
                                            depth: 30
                                    }
                                    },
                                    series: [{
                                            data: [
    <?php echo $series; ?>
                                            ]
                                    }]
                            });
                            });</script>
                <div id="inventorybywarehouse_pie" style="min-width: 900px; max-height: 450px; margin: 0 auto"></div>
            </div>
        </div>          
    </div>
<?php endif; ?>
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/_JSSettings.js"></script>
<script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/js_002"></script>
<script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/dashboards"></script>

<script type="text/javascript">
                        var saveViewPositions = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/saveviewposition') ?>';
                        var saveTabPositions = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/savetabposition') ?>';
                        var form_key_dashboard = '<?php echo $this->getFormKey() ?>';</script>
<script type="text/javascript">
            var $sd = new InventoryDashboard.Views.Dashboards();
            $sd.isShare = false;
            $sd.backgroundColour = '#808080';
            $sd.init();
</script>