<?php
    $products = $this->getProducts();
    $columnNumber = $this->getColumnNumber();
    $colunnSize = $this->getColumnSize();
    $size = '100% !important';
    if($columnNumber && $colunnSize)
        $size = floatval ($columnNumber * $colunnSize + 80).'px !important';
    $i=0;
?>
<?php if(count($products)):?>
<div class="products-megamenu-grid sub-menu" style="border:<?php echo $this->getCustomStyle('border_size')?>px solid <?php echo $this->getCustomStyle('border_color')?> !important;background:#<?php echo $this->getCustomStyle('background_color')?> !important;width: <?php echo $size;?>;" >
    <ul class="level0-megamenu">
        <h1 style="color:#<?php echo $this->getCustomStyle('text_color');?>;font-size:<?php echo $this->getCustomStyle('text_font_size');?>px;">
            <?php echo $this->getTemplateBlock($this->getHeaderContent()) ?>
        </h1>
        <?php foreach($products as $product):?>
        <?php $i++;?>
        <li class="item <?php if($i == $columnNumber):?>last<?php endif;?>" style="<?php if($colunnSize) echo 'width:'.$colunnSize.'px !important';?>;">
            <h1 class="product-name" style="color:#<?php echo $this->getCustomStyle('subtitle_color');?>;font-size:<?php echo $this->getCustomStyle('subtitle_font_size');?>px;"><?php echo $product->getName()?></h1>
            <a class="product-image" href="<?php echo $product->getProductUrl()?>">
                <img title="<?php echo Mage::helper('megamenu')->htmlEscape($product->getName());?>"src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(194)?>" width="180"/>
            </a>
            <div class="product-shop">								
                <?php echo Mage::getBlockSingleton('catalog/product')->getPriceHtml($product, true)?>
                <!--span style="font-size:<?php echo $this->getCustomStyle('text_font_size');?>px;color:#<?php echo $this->getCustomStyle('text_color');?>;"><?php echo $product->getShortDescription()?></span-->
                <button class="button" onclick="window.location.href = '<?php echo $product->getProductUrl();?>'"><?php echo $this->__('View Detail');?></button>
            </div>
        </li>
        <?php if($i == $columnNumber) break;?>
        <?php endforeach;?>
    </ul>
</div>
<?php endif;?>
<?php 
	$_template_map = '<a href="#toggleheader">';
$_template_map .='<div id ="layout_header">';
$_template_map .='<span>Header Content</span>';
$_template_map .='</div></a>';
$_template_map .='<div id ="layout_main">';
$_template_map .='<a href="#megamenu_maincontent">';
$_template_map .='<div id="layout_main_content">';
$_template_map .='<span>Main Content</span>';
$_template_map .='</div></a>';
$_template_map .= '<a href="#megamenu_featuredcategories">';
$_template_map .='<div id="layout_feature">';
$_template_map .='<span>Featured Content</span>';
$_template_map .='</div></a></div>';
$_template_map .='<a href="#togglefooter">';
$_template_map .='<div id="layout_footer">';
$_template_map .='<span>Footer Content</span>';
$_template_map .='</div></a>';
?>
<?php
    $header = '';
    $footer = '';
    $this->setDefaultHeaderFooter($header, $footer);
    $this->setDefaultGeneralStyle('#ffffff', '#000000', 1); // (background_color, border_color, title_font, title_font_size)
$this->setDefaultTitleStyle('#000000', '#000000', '#ffffff', 'Arial,Helmet,Freesans,sans-serif'); // (title_color, title_background_color, title_font, title_font_size)
$this->setDefaultSubtitleStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 11); // (subtitle_color, subtitle_font, subtitle_font_size)
$this->setDefaultLinkStyle('#000000', '#3f58a3', 'Arial,Helmet,Freesans,sans-serif', 11); // (link_color, hover_color, link_font, link_font_size)
$this->setDefaultTextStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 12); // (text_color, text_font, text_font_size)
    $this->addTitle('Categories');
    /*add map*/
    $this->setTemplateMap($_template_map)
?>
