<?php
    $products = $this->getProducts();
    $columnNumber = $this->getColumnNumber();
    $colunnSize = $this->getColumnSize();
    
    if(count($products) < $columnNumber){
        $columnNumber = count($products);
    }
?>
<?php if(count($products)):?>
<div class="products-megamenu-grid sub-menu" 
     style="border:<?php echo $this->getCustomStyle('border_size')?>px solid  #<?php echo $this->getCustomStyle('border_color')?> !important;
            background:#<?php echo $this->getCustomStyle('background_color') ?> !important;
            width: 100% !important;">
    <?php if ($this->getHeaderContent()) :?>
    <div class = "header-megamenu" 
         style="color:#<?php echo $this->getCustomStyle('text_color'); ?>;
                font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px; 
                font-family: <?php echo $this->getCustomStyle('text_font'); ?> !important;">			
        <?php
        $text = $this->getTemplateBlock($this->getHeaderContent());
//        $newtext = $this->limitString($text, 200);
        echo $text;
        ?>
    </div>
    <?php endif;?>
    <ul class="level0-megamenu" id="grid-product-<?php echo $this->getItem()->getId()?>"
        style="width: 100% !important;">
        <?php foreach($products as $product):?>
        <li class="item">
            <strong class="product-name" 
                    style="color:#<?php echo $this->getCustomStyle('subtitle_color');?>;
                           font-size:<?php echo $this->getCustomStyle('subtitle_font_size');?>px;
                           font-family: <?php echo $this->getCustomStyle('subtitle_font'); ?> !important;">
                <?php echo $product->getName()?>
            </strong>
            <a class="product-image" href="<?php echo $product->getProductUrl()?>">
                <img title="<?php echo Mage::helper('megamenu')->htmlEscape($product->getName());?>" src="<?php echo $this->getImagePath($product, $colunnSize);?>" width="100%"/>
            </a>
            <div class="product-shop">								
                <?php echo Mage::getBlockSingleton('catalog/product_price')->getPriceHtml($product, true)?>
                <button class="button" onclick="window.location.href = '<?php echo $product->getProductUrl();?>'"><?php echo $this->__('View Detail');?></button>
            </div>
        </li>
        <?php endforeach;?>
    </ul>
    <?php if ($this->getFooterContent()) :?>
    <div class="footer-megamenu" 
         style="color:#<?php echo $this->getCustomStyle('text_color'); ?>;
                font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px;
                font-family: <?php echo $this->getCustomStyle('text_font'); ?> !important;">
        <?php echo $this->getTemplateBlock($this->getFooterContent()) ?>
    </div>
    <?php endif; ?>
</div>
<?php endif;?>
<?php 
$_template_map = '<div class="product-detail">';
$_template_map .= '<div class="layout-nav">';
$_template_map .= '</div>';
$_template_map .='<div id ="layout_header">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#toggleheader">';
$_template_map .='<span>Header Content</span>';
$_template_map .='</a><div>&nbsp;</div></div>';
$_template_map .='<div id="layout_main_content">';
$_template_map .='<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#megamenu_maincontent">';
$_template_map .='<span>Main Content</span>';
$_template_map .='</a><div>&nbsp;</div></div>';
$_template_map .='<div id="layout_footer">';
$_template_map .='<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#togglefooter">';
$_template_map .='<span>Footer Content</span>';
$_template_map .='</a><div>&nbsp;</div></div></div>';
?>
<?php
    $header = '';
    $footer = '';
    $this->setDefaultHeaderFooter($header, $footer);
   $this->setDefaultGeneralStyle('#ffffff', '#D5D5D5', 1); // (background_color, border_color,border_size)
$this->setDefaultTitleStyle('#ffffff', '#000000', 'Arial,Helmet,Freesans,sans-serif',11); // (title_color, title_background_color, title_font, title_font_size)
$this->setDefaultSubtitleStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 11); // (subtitle_color, subtitle_font, subtitle_font_size)
$this->setDefaultLinkStyle('#666666', '#3f58a3', 'Arial,Helmet,Freesans,sans-serif', 11); // (link_color, hover_color, link_font, link_font_size)
$this->setDefaultTextStyle('#666666', 'Arial,Helmet,Freesans,sans-serif', 11); // (text_color, text_font, text_font_size)
$this->setDefaultContentGeneral(600,4,180);// megamenu_size,column_number,column_size   
$this->addTitle('Categories');
    /*add map*/
    $this->setTemplateMap($_template_map);
    $this->setTemplateFileName('product_listing_01');
?>

<script>
    mm('.products-megamenu-grid').parent().parent().mouseenter(function() {
        var dp_min_col_size = <?php echo $colunnSize;?>;
        var dp_max_cols = <?php echo $columnNumber;?>;
        var dp_1_col_width = 96/dp_max_cols;
        var dp_menu_width = mm('.topmenu').innerWidth();
            dp_menu_width *= 0.96;
            
        if (dp_menu_width/dp_max_cols >= dp_min_col_size) {
            mm('.level0-megamenu .item').css("cssText", mm('.level0-megamenu .item').attr('style')+"width:"+dp_1_col_width+"% !important;");
        } else {
            var dp_real_cols = Math.floor(dp_menu_width/dp_min_col_size);
            if (dp_real_cols < 2) dp_real_cols = 1;
            dp_1_col_width = 96/dp_real_cols;
            mm('.level0-megamenu .item').css("cssText", mm('.level0-megamenu .item').attr('style')+"width:"+dp_1_col_width+"% !important;");
        }
    });
</script>