<?php
    $products = $this->getProducts();
    $columnNumber = $this->getColumnNumber();
    $colunnSize = $this->getColumnSize();
    $hasFeatured = 0;
    $size = 0;
    if ($this->hasFeaturedProducts()) {
        $hasFeatured = 1;
        $featuredProducts = $this->getFeaturedProducts();
    }elseif($this->hasFeaturedCategories()) {
        $hasFeatured = 1;
        $featuredCategories = $this->getFeaturedCategories();
    }
    
    if (count($products) < $columnNumber) {
        if ($hasFeatured) {
            $columnNumber = count($products) + 1;
        } else {
            $columnNumber = count($products);
        }
        
    }
?>
<?php if (count($products)): ?>
    <div class="products-megamenu-list sub-menu" 
         style="border:<?php echo $this->getCustomStyle('border_size') ?>px solid #<?php echo $this->getCustomStyle('border_color') ?> !important;
                background:#<?php echo $this->getCustomStyle('background_color') ?> !important;
                width: 100%" >
        <?php if ($this->getHeaderContent()) :?>
        <div class = "header-megamenu" 
             style="color:#<?php echo $this->getCustomStyle('text_color'); ?>;
                    font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px; 
                    font-family: <?php echo $this->getCustomStyle('text_font'); ?> !important;">			
            <?php
            $text = $this->getTemplateBlock($this->getHeaderContent());
            $newtext = $this->limitString($text, 200);
            echo $newtext;
            ?>
        </div>
        <?php endif;?>
        <ul class="level0-megamenu" style="width: 100% !important">
            <div class="gp-product-box" style="float:left;">
                <li class="level1-megamenu">
                    <div class="level1-title">
                        <strong style="color:#<?php echo $this->getCustomStyle('subtitle_color') ?>;
                                font-size:<?php echo $this->getCustomStyle('subtitle_font_size') ?>px;
                                font-family: <?php echo $this->getCustomStyle('subtitle_font'); ?> !important;
                                text-transform: uppercase;
                                border-bottom: 1px dashed #d5d5d5 !important;
                                width: 100%;">
                            <?php echo $this->getItem()->getProductsBoxTitle(); ?>
                        </strong>  
                    </div>
                    <ul class="level2-megamenu">
                        <?php foreach ($products as $product): ?>
                        <li class="mm-product-link">
                            <a style="color:#<?php echo $this->getCustomStyle('link_color') ?> !important;
                                    font-size:<?php echo $this->getCustomStyle('link_font_size') ?>px;
                                    font-family: <?php echo $this->getCustomStyle('link_font'); ?> !important;" 
                                href="<?php echo $product->getProductUrl();?>"
                                onmouseover="mm(this).attr('style', 'color: #<?php echo $this->getCustomStyle('hover_color'); ?> !important; font-size:<?php echo $this->getCustomStyle('link_font_size'); ?>px !important; font-family: <?php echo $this->getCustomStyle('link_font'); ?> !important;')" 
                                onmouseout= "mm(this).attr('style', 'color: #<?php echo $this->getCustomStyle('link_color'); ?> !important; font-size:<?php echo $this->getCustomStyle('link_font_size'); ?>px !important; font-family: <?php echo $this->getCustomStyle('link_font'); ?> !important;')"
                            >
                                <span><?php echo $product->getName(); ?></span>
                            </a>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
            </div>
            <?php $max = 0;?>
            <?php if($this->hasFeaturedProducts() && count($featuredProducts)):?>
            <div class="gp-featured-box" style="float:right;">
            <li class="level1-megamenu featured" style="width:100% !important">
                <div class="level1-title">
                    <strong style="color:#<?php echo $this->getCustomStyle('subtitle_color');?>;
                        font-size:<?php echo $this->getCustomStyle('subtitle_font_size');?>px;
                        font-family: <?php echo $this->getCustomStyle('subtitle_font'); ?> !important;">
                        <?php echo $this->__('Featured Products');?>
                    </strong>					
                </div>
                <ul class="level2-megamenu">
                    <?php foreach($featuredProducts as $featuredProduct):?>
                    <?php $max++;?>
                    <li class="product-item">
                        <a class="product-image" href="<?php echo $featuredProduct->getProductUrl();?>">
                            <img title="<?php echo Mage::helper('megamenu')->htmlEscape($featuredProduct->getName());?>"src="<?php echo $this->getImagePath($featuredProduct, 110);?>" width="110"/>
                        </a>
                        <div class="product-shop">
                            <a href="<?php echo $featuredProduct->getProductUrl();?>">
                                <h1 class="product-name"style="font-size:<?php echo $this->getCustomStyle('link_font_size');?>px;color:#<?php echo $this->getCustomStyle('link_color');?>;">
                                    <?php echo $featuredProduct->getName();?>
                                </h1>
                            </a>
                            <?php echo Mage::getBlockSingleton('catalog/product')->setArea('frontend')->getPriceHtml($featuredProduct, true)?>
                            <button class="button" onclick="window.location.href = '<?php echo $featuredProduct->getProductUrl();?>'"><?php echo $this->__('View Detail');?></button>
                        </div>
                    </li>
                    <?php if($max == 2) break;?>
                    <?php endforeach;?>
                </ul>
            </li>
            <?php elseif($this->hasFeaturedCategories() && count($featuredCategories)):?>
            <li class="level1-megamenu featured" style="width:100% !important">
                <div class="level1-title">
                    <strong style="color:#<?php echo $this->getCustomStyle('subtitle_color');?>;
                            font-size:<?php echo $this->getCustomStyle('subtitle_font_size');?>px;
                            font-family: <?php echo $this->getCustomStyle('subtitle_font'); ?> !important;">
                        <?php echo $this->__('Featured Categories');?>
                    </strong>					
                </div>
                <ul class="level2-megamenu">
                    <?php foreach($featuredCategories as $featuredCategory):?>
                    <?php $max++;?>
                    <li class="product-item">
                        <a class="product-image" href="<?php echo $featuredCategory->getUrl();?>">
                            <img title="<?php echo Mage::helper('megamenu')->htmlEscape($featuredCategory->getName());?>"src="<?php echo $featuredCategory->getImageUrl();?>" width="110"/>
                        </a>
                        <div class="product-shop">
                            <a href="<?php echo $featuredCategory->getUrl();?>">
                                <h1 class="product-name"style="font-size:<?php echo $this->getCustomStyle('link_font_size');?>px;color:#<?php echo $this->getCustomStyle('link_color');?>;">
                                    <?php echo $featuredCategory->getName();?>
                                </h1>
                            </a>
                            <?php //echo Mage::getBlockSingleton('catalog/product')->getPriceHtml($featuredProduct, true)?>
                            <button class="button" onclick="window.location.href = '<?php echo $featuredCategory->getUrl();?>'"><?php echo $this->__('View Detail');?></button>
                        </div>
                    </li>
                    <?php if($max == 2) break;?>
                    <?php endforeach;?>
                </ul>
            </li>
            </div>
            <?php endif;?>
        </ul>
        <?php if ($this->getFooterContent()) :?>
        <div class="footer-megamenu" 
             style="color:#<?php echo $this->getCustomStyle('text_color'); ?>;
                    font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px;
                    font-family: <?php echo $this->getCustomStyle('text_font'); ?> !important;">
            <?php echo $this->getTemplateBlock($this->getFooterContent()) ?>
        </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
<?php
$_template_map = '<div class="product-list">';
$_template_map .= '<div class="layout-nav">';
$_template_map .= '</div>';
$_template_map .='<div id ="layout_header">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#toggleheader">';
$_template_map .='<span>Header Content</span>';
$_template_map .='</a><div>&nbsp;</div></div>';
$_template_map .='<div id="layout_main_content">';
$_template_map .='<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#megamenu_maincontent">';
$_template_map .='<span>Main Content</span>';
$_template_map .='</a><div>&nbsp;</div></div>';
$_template_map .='<div id="layout_feature">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#megamenu_featuredcategories">';
$_template_map .='<span>Featured Content</span>';
$_template_map .='</a><div>&nbsp;</div></div>';
$_template_map .='<div id="layout_footer">';
$_template_map .='<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#togglefooter">';
$_template_map .='<span>Footer Content</span>';
$_template_map .='</a><div>&nbsp;</div></div></div>';
?>
<?php
$header = '';
$footer = '';
$this->setDefaultHeaderFooter($header, $footer);
$this->setDefaultGeneralStyle('#ffffff', '#D5D5D5', 1); // (background_color, border_color,border_size)
$this->setDefaultTitleStyle('#ffffff', '#000000', 'Arial,Helmet,Freesans,sans-serif',11); // (title_color, title_background_color, title_font, title_font_size)
$this->setDefaultSubtitleStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 11); // (subtitle_color, subtitle_font, subtitle_font_size)
$this->setDefaultLinkStyle('#666666', '#3f58a3', 'Arial,Helmet,Freesans,sans-serif', 11); // (link_color, hover_color, link_font, link_font_size)
$this->setDefaultTextStyle('#666666', 'Arial,Helmet,Freesans,sans-serif', 11); // (text_color, text_font, text_font_size)
$this->setDefaultContentGeneral(600,4,180);// megamenu_size,column_number,column_size
/* add title */
$this->addTitle('Categories');
/* add map */
$this->setTemplateMap($_template_map);
$this->setTemplateFileName('product_listing_02');
?>
<script>
    mm('.sub-menu').parent().parent().mouseenter(function() {
//        var gc = jQuery.noConflict();
        var gp_min_col_size = <?php echo $colunnSize;?>;
        var gp_has_featured = <?php echo $hasFeatured;?>;
        var gp_max_cols = <?php echo $columnNumber;?>;
        var gp_1_col_width = 96/gp_max_cols;
        var gp_menu_width = mm('.topmenu').innerWidth();
            gp_menu_width *= 0.96;
            
        if (gp_menu_width/gp_max_cols >= gp_min_col_size) {
            if (gp_has_featured) {
                mm('.gp-featured-box').css('width', gp_1_col_width+"%");
                mm('.gp-product-box').css('width', 96-gp_1_col_width+"%");
                mm('.level1-megamenu').css("cssText", mm('.level1-megamenu').attr('style')+"width:"+100/(gp_max_cols-1)+"% !important;");
                mm('.featured').css("cssText", mm('.level1-megamenu').attr('style')+"width:100% !important;");
                mm('.gp-featured-box').show();
            } else {
                mm('.gp-product-box').css('width', "96%");
//                mm('.level1-megamenu').css("cssText", mm('.level1-megamenu').attr('style')+"width:"+100/(gp_max_cols)+"%; !important");
            }
        } else {
            var gp_real_cols = Math.floor(gp_menu_width/gp_min_col_size);
            if (gp_real_cols < 2) gp_real_cols = 1;
            gp_1_col_width = 96/gp_real_cols;
            if (gp_has_featured) {
                mm('.gp-featured-box').css('width', gp_1_col_width+"%");
                mm('.gp-product-box').css('width', 96-gp_1_col_width+"%");
                mm('.level1-megamenu').css("cssText", "width:100% !important;");
                mm('.mm-product-link').css("cssText", "width:"+100/(gp_max_cols-1)+"% !important;");
                mm('.featured').css("cssText", mm('.level1-megamenu').attr('style')+"width:100% !important;");
                mm('.gp-featured-box').show();
            } else {
                mm('.gp-product-box').css('width', "96%");
                mm('.level1-megamenu').css("cssText", "width:100% !important;");
                mm('.mm-product-link').css("cssText", "width:"+100/(gp_real_cols)+"%; !important");
            }
            if (gp_real_cols == 1) {
                mm('.gp-featured-box').hide();
                mm('.gp-product-box').css('width', "96%");
                mm('.level1-megamenu').css("cssText","width: 100% !important;");
                mm('.mm-product-link').css("cssText", "width:"+100/(gp_real_cols)+"%; !important");
            } else {
                mm('.gp-featured-box').show();
            }
        }
    });
</script>