<?php
$products = $this->getProducts();
$featuredProducts = $this->getFeaturedProducts();
$columnNumber = $this->getColumnNumber();
$colunnSize = $this->getColumnSize();
$featuredWidth = 0;
$size = 0;
if ($this->hasFeaturedProducts()) {
    $featuredWidth = 220;
    $line = round(count($products) / ($columnNumber - 1));
    if ($columnNumber && $colunnSize)
        $size = floatval(($columnNumber - 1) * $colunnSize + $featuredWidth + 110) . 'px !important';
}else {
    $line = round(count($products) / $columnNumber);
    if ($columnNumber && $colunnSize)
        $size = floatval($columnNumber * $colunnSize + 80) . 'px !important';
}
$i = 0;
?>
<?php if (count($products)): ?>
    <div class="products-megamenu-list sub-menu" style="border:<?php echo $this->getCustomStyle('border_size') ?>px solid <?php echo $this->getCustomStyle('border_color') ?> !important;background:#<?php echo $this->getCustomStyle('background_color') ?> !important;width:100%" >
        <ul class="level0-megamenu">
            <li class="level1-megamenu">
                <h4 style="color:#<?php echo $this->getCustomStyle('subtitle_color') ?>;font-size:<?php echo $this->getCustomStyle('subtitle_font_size') ?>px;"><?php echo $this->__('Products'); ?></h4>
                <ul class="level2-megamenu" style="width:<?php echo $colunnSize; ?>px !important">
                    <?php foreach ($products as $product): ?>
                        <?php $i++; ?>
                        <li>
                            <a style="color:#<?php echo $this->getCustomStyle('link_color') ?> !important;font-size:11px !important;" href="<?php echo $product->getProductUrl(); ?>">
                                <span><?php echo $product->getName(); ?></span>
                            </a>
                        </li>	
                        <?php if ($i % $line == 0): ?>
                        </ul>
                        <ul class="level2-megamenu" style="width:<?php echo $colunnSize; ?>px !important">
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </li>
            <li class="level1-megamenu featured">
                <div class="level1-title">
                    <h2 style="color:#<?php echo $this->getCustomStyle('subtitle_color') ?>;font-size:<?php echo $this->getCustomStyle('subtitle_font_size') ?>px;"><?php echo $this->__('Featured Products'); ?></h2>					
                </div>
                <ul>
                    <?php foreach ($featuredProducts as $featuredProduct): ?>
                        <li class="product-item">
                            <a class="product-image">
                                <img title="<?php echo Mage::helper('megamenu')->htmlEscape($featuredProduct->getName()); ?>"src="<?php echo $this->helper('catalog/image')->init($featuredProduct, 'small_image')->resize(194) ?>" width="110"/>
                            </a>
                            <div class="product-shop">
                                <a href="<?php echo $featuredProduct->getProductUrl(); ?>">
                                    <h1 class="product-name"><?php echo $featuredProduct->getName(); ?></h1>
                                </a>
                                <!--span>With buttons, VoiceOver, and playlists.</span-->
                                <?php echo Mage::getBlockSingleton('catalog/product')->getPriceHtml($featuredProduct, true) ?>
                                <button class="button" onclick="window.location.href = '<?php echo $featuredProduct->getProductUrl(); ?>'"><?php echo $this->__('View Detail'); ?></button>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </li>
        </ul>
    </div>
<?php endif; ?>
<?php
$_template_map = '<a href="#toggleheader">';
$_template_map .='<div id ="layout_header">';
$_template_map .='<span>Header Content</span>';
$_template_map .='</div></a>';
$_template_map .='<div id ="layout_main">';
$_template_map .='<a href="#megamenu_maincontent">';
$_template_map .='<div id="layout_main_content">';
$_template_map .='<span>Main Content</span>';
$_template_map .='</div></a>';
$_template_map .= '<a href="#megamenu_featuredcategories">';
$_template_map .='<div id="layout_feature">';
$_template_map .='<span>Featured Content</span>';
$_template_map .='</div></a></div>';
$_template_map .='<a href="#togglefooter">';
$_template_map .='<div id="layout_footer">';
$_template_map .='<span>Footer Content</span>';
$_template_map .='</div></a>';
?>
<?php
$header = '';
$footer = '';
$this->setDefaultHeaderFooter($header, $footer);
$this->setDefaultGeneralStyle('#ffffff', '#000000', 1); // (background_color, border_color, title_font, title_font_size)
$this->setDefaultTitleStyle('#000000', '#000000', '#ffffff', 'Arial,Helmet,Freesans,sans-serif'); // (title_color, title_background_color, title_font, title_font_size)
$this->setDefaultSubtitleStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 11); // (subtitle_color, subtitle_font, subtitle_font_size)
$this->setDefaultLinkStyle('#000000', '#3f58a3', 'Arial,Helmet,Freesans,sans-serif', 11); // (link_color, hover_color, link_font, link_font_size)
$this->setDefaultTextStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 12); // (text_color, text_font, text_font_size)
/* add title */
$this->addTitle('Categories');
/* add map */
$this->setTemplateMap($_template_map)
?>
