<?php
    $products = $this->getProducts();
    $columnNumber = $this->getColumnNumber();
    $colunnSize = $this->getColumnSize();
    if(count($products) < $columnNumber){
        $columnNumber = count($products);
    }
?>

<style>
    .megamenu #nav-toggle .products-megamenu-grid ul.level0-megamenu {
        width: 100%;
        padding: 10px 1%;
    }
    .megamenu #nav-toggle .products-megamenu-grid ul.level0-megamenu .header-megamenu {
        border-bottom: 1px dashed #d5d5d5;
        padding-bottom: 5px;
        margin-bottom: 5px;
    }
    .megamenu #nav-toggle .products-megamenu-grid ul.level0-megamenu .footer-megamenu {
        margin-top: 10px;
    }
    .megamenu #nav-toggle .products-megamenu-grid li.item {
        padding: 5px;
        min-width: <?php if ($colunnSize) echo $colunnSize . 'px !important'; else  echo '150px !important'; ?>;
        text-align: center;
       // border-left: 1px dashed #d5d5d5;
        border-right: none;
    }
    .megamenu #nav-toggle .products-megamenu-grid li.item.first{
        border-left: none;
    }
    .megamenu #nav-toggle .products-megamenu-grid li.item a.product-image {
        background: none;
        /*border: none;*/
    }
    .megamenu #nav-toggle .products-megamenu-grid li.item a.product-image img{
        margin: auto;
        width: <?php if ($colunnSize) echo $colunnSize-20 . 'px !important'; else  echo '130px !important'; ?>;
    }
    .megamenu #nav-toggle .products-megamenu-grid li.item h1.product-name {
        margin: 0px 0px 5px 0px;
        padding:  0px 0px 5px 0px;
        width: 100%;
    }
    .megamenu #nav-toggle .products-megamenu-grid li.item .product-shop {
        width: 100%;
    }
</style>

<?php if(count($products)):?>
<div class="products-megamenu-grid sub-menu" 
     style="border:<?php echo $this->getCustomStyle('border_size')?>px solid  #<?php echo $this->getCustomStyle('border_color')?> !important;
     background:#<?php echo $this->getCustomStyle('background_color')?> !important;
     width: 100% !important;" >
    <ul class="level0-megamenu" 
        id="grid-product-<?php echo $this->getItem()->getId()?>" 
        style="width:<?php echo $size-20;?>px !important">
        <div class="header-megamenu" 
            style=" color:#<?php echo $this->getCustomStyle('text_color'); ?> !important;
                    font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px !important;
                    font-family: <?php echo $this->getCustomStyle('text_font'); ?> !important;
                     <?php if(!$this->getTemplateBlock($this->getHeaderContent())):?>border-bottom:none !important;<?php endif;?>">
            <?php echo $this->getTemplateBlock($this->getHeaderContent()) ?>
        </div>
        <?php $i=0; foreach($products as $product):?>
        <li class="item <?php if($i==0):?>first<?php endif;$i++; ?>" >
                <h1 class="product-name" 
                    style=" color:#<?php echo $this->getCustomStyle('subtitle_color'); ?> !important;
                            font-size:<?php echo $this->getCustomStyle('subtitle_font_size'); ?>px !important;
                            font-family: <?php echo $this->getCustomStyle('subtitle_font'); ?> !important;">
                    <?php echo $product->getName()?>
                </h1>
                <a class="product-image" 
                   href="<?php echo $product->getProductUrl()?>">
                    <img title="<?php echo Mage::helper('megamenu')->htmlEscape($product->getName());?>" 
                         src="<?php echo $this->getImagePath($product, $colunnSize);?>" />
                </a>
                <div class="product-shop">
                    <div class="price-info">
                        <?php echo Mage::helper('core')->currency($product->getPrice());?>
                    </div>
                    <button class="button" 
                            onclick="window.location.href = '<?php echo $product->getProductUrl();?>'">
                        <span><span><?php echo $this->__('View Detail');?></span></span>
                    </button>
                </div>
            </li>
        <?php endforeach;?>
        <div class="footer-megamenu" 
             style="color:#<?php echo $this->getCustomStyle('text_color'); ?> !important;;
                    font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px !important;;
                    font-family: <?php echo $this->getCustomStyle('text_font'); ?> !important;">
            <?php echo $this->getTemplateBlock($this->getFooterContent()) ?>
        </div>
    </ul>
</div>
<?php endif;?>
<?php 
$_template_map = '<div class="product-detail">';
$_template_map .= '<div class="layout-nav">';
$_template_map .= '</div>';
$_template_map .='<div id ="layout_header">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#toggleheader">';
$_template_map .='<span>Header Content</span>';
$_template_map .='</a><div>&nbsp;</div></div>';
$_template_map .='<div id="layout_main_content">';
$_template_map .='<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#megamenu_maincontent">';
$_template_map .='<span>Main Content</span>';
$_template_map .='</a><div>&nbsp;</div></div>';
$_template_map .='<div id="layout_footer">';
$_template_map .='<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#togglefooter">';
$_template_map .='<span>Footer Content</span>';
$_template_map .='</a><div>&nbsp;</div></div></div>';
?>
<?php
    $header = '';
    $footer = '';
    $this->setDefaultHeaderFooter($header, $footer);
   $this->setDefaultGeneralStyle('#ffffff', '#D5D5D5', 1); // (background_color, border_color,border_size)
$this->setDefaultTitleStyle('#ffffff', '#000000', 'Arial,Helmet,Freesans,sans-serif',11); // (title_color, title_background_color, title_font, title_font_size)
$this->setDefaultSubtitleStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 11); // (subtitle_color, subtitle_font, subtitle_font_size)
$this->setDefaultLinkStyle('#666666', '#3f58a3', 'Arial,Helmet,Freesans,sans-serif', 11); // (link_color, hover_color, link_font, link_font_size)
$this->setDefaultTextStyle('#666666', 'Arial,Helmet,Freesans,sans-serif', 11); // (text_color, text_font, text_font_size)
$this->setDefaultContentGeneral(600,4,180);// megamenu_size,column_number,column_size   
$this->addTitle('Categories');
    /*add map*/
    $this->setTemplateMap($_template_map);
    $this->setTemplateFileName('responsive_product_listing');
?>

<?php if ($columnNumber):?>
    <?php if (!$colunnSize) $colunnSize = 150;?>
    <style>
        .megamenu #nav-toggle .products-megamenu-grid li.item {
            width: <?php echo (float) 100/$columnNumber;?>%;
        }
    </style>
<?php endif;?>