<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('General Instructions') ?></h4>
    </div>    
    <div id="stocktransfering_form" class="fieldset ">
        <?php echo $this->__('You can request stock for one of your warehouses from any other sources.') ?><br />
        <?php echo $this->__('- If you request stock for a warehouse from another one, the stock transfer will be auto-completed. The Qty. transferred is updated instantly in both warehouses while the total Qty. in your system remains unchanged.') ?><br />
        <?php echo $this->__('- If you request stock from other sources besides your warehouses, the total Qty. in your system will be increased correspondingly.') ?><br />
    </div>
</div>   