<?php // Zend_Debug::dump(Mage::helper('inventorydashboard')->getDefaultChartType());    ?>
<!-- dashboard tabs -->
<?php
$check = Mage::helper('inventoryplus')->isInstallData();
?>
<?php if (!$check) : ?>
    <script src="<?php echo $this->getJsUrl() ?>mage/adminhtml/loader.js" type="text/javascript"></script>

    <div id="loading-mask" style="left: -2px; top: 0px; width: 100%; height: 100%;">
        <p class="loader" id="loading_mask_loader">
            <img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>" alt="Loading..."/>
            <br/>
            <?php
            echo Mage::helper('inventoryplus')->__('Installing data...');
            echo '<br/>';
            echo Mage::helper('inventoryplus')->__('Please do not close this window');
            ?>
        </p>
    </div>
    <script>
        var reloadurl = '<?php echo Mage::helper('adminhtml')->getUrl('inventoryplusadmin/adminhtml_dashboard/importdata') ?>';
        $('loading-mask').show();
        new Ajax.Request(reloadurl, {
            method: 'post',
            onComplete: function (transport) {
                if (transport.responseText == 1) {
                    location.reload();
                }
            }
        });
    </script>

<?php else : ?>
    <div class="section-head screen">
        <ul class="ui-sortable" id="ulTabs">
            <?php
            $tabs = Mage::getModel('inventorydashboard/tabs')->getCollection()
                    ->setOrder('position', 'ASC');
            $tabId = '';
            ?>
            <?php if ($tabs->getSize()): ?>
                <?php $i = 0 ?>
                <?php foreach ($tabs as $tab): ?>
                    <?php $selected = '' ?>
                    <?php if ($this->getRequest()->getParam('tab_id')): ?>
                        <?php if ($tab->getId() == $this->getRequest()->getParam('tab_id')): ?>
                            <?php $selected = 'selected' ?>
                            <?php $tabId = $tab->getId() ?>
                        <?php endif ?>
                    <?php else: ?>
                        <?php if ($i == 0): ?>
                            <?php $selected = 'selected' ?>
                            <?php $tabId = $tab->getId() ?> 
                        <?php endif ?>
                    <?php endif ?>
                    <?php $i++ ?>
                    <li class="<?php echo $selected ?>" data-item-id="<?php echo $tab->getId() ?>" title="<?php echo $tab->getName() ?>">                    
                        <b></b>
                        <?php if ($selected): ?>
                            <a><?php echo $tab->getName() ?></a>
                        <?php else: ?>
                            <a href="<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/index', array('tab_id' => $tab->getId())) ?>">
                                <?php echo $tab->getName() ?>
                            </a>
                        <?php endif ?>                        
                    </li>

                <?php endforeach ?>    
            <?php endif ?>

            <li class="add"><a href="#" onclick="addDashboard();
                    return false;" class="add-dash gradient" title="<?php echo $this->__('Create new dashboard') ?>"><i class="add-dash-icon"></i></a></li>
            <li id="" class="" style="float:right;">
                <a onclick="editDashboard();
                        return false;" title="<?php echo $this->__('Edit this dashboard') ?>" data-ajax="true" data-ajax-method="GET" data-ajax-mode="replace" data-ajax-success="" data-ajax-update="#dvSettings" href="javascript:void(0)">
                    <span style="background-position: -58px -1540px; float: left; height: 18px; width: 18px; display: block;" class="sprite"></span>
                </a>
            </li>
            <?php if ($tabId): ?>
                <li class="add" style="float:right;"><a href="javascript:void(0)" onclick="addDashboardChart();
                        return false;" class="" style="background-color:#90da25;" title="<?php echo $this->__('Add a new chart to this dashboard') ?>" style="float:right;"><i class="add-dash-icon"></i><b><?php echo $this->__('Add New Chart') ?></b></a></li>
                                                    <?php endif ?>
            <br class="clear">
        </ul>
        <script type="text/javascript">
            function addDashboard()
            {
                if ($('add_tab')) {
                    if (document.getElementById('add_tab').style.display == 'none') {
    //                    document.getElementById('add_tab').style.display='block'; 
                        $_('#add_tab').fadeIn(20);
                        if ($('add_tab_chart')) {
                            if (document.getElementById('add_tab_chart').style.display == 'block'
                                    || document.getElementById('add_tab_chart').style.display == '') {
    //                            document.getElementById('add_tab_chart').style.display='none'; 
                                $_('#add_tab_chart').fadeOut(20);
                            }
                        }
                        if ($('edit_tab')) {
                            if (document.getElementById('edit_tab').style.display == 'block'
                                    || document.getElementById('edit_tab').style.display == '') {
    //                            document.getElementById('edit_tab').style.display='none'; 
                                $_('#edit_tab').fadeOut(20);
                            }
                        }
                        if ($('edit_item_form')) {
                            $('edit_item_form').innerHTML = '';
                        }
                    } else {
    //                    document.getElementById('add_tab').style.display='none'; 
                        $_('#add_tab').fadeOut(20);
                    }
                }
            }
            function addDashboardChart()
            {
                if ($('add_tab_chart')) {
                    if (document.getElementById('add_tab_chart').style.display == 'none') {
    //                    document.getElementById('add_tab_chart').style.display='block';
                        $_('#add_tab_chart').fadeIn(20);
                        if ($('edit_item_form')) {
                            if (document.getElementById('edit_item_form').style.display == 'block'
                                    || document.getElementById('edit_item_form').style.display == '') {
    //                            document.getElementById('add_tab_chart').style.display='none';
                                $_('#edit_item_form').fadeOut(20);
                            }
                        }
                        if ($('add_tab')) {
                            if (document.getElementById('add_tab').style.display == 'block'
                                    || ocument.getElementById('add_tab').style.display == '') {
    //                            document.getElementById('add_tab').style.display='none'; 
                                $_('#add_tab').fadeOut(20);
                            }
                        }
                        if ($('edit_tab')) {
                            if (document.getElementById('edit_tab').style.display == 'block'
                                    || document.getElementById('edit_tab').style.display == '') {
    //                            document.getElementById('edit_tab').style.display='none'; 
                                $_('#edit_tab').fadeOut(20);
                            }
                        }
                        if ($('edit_item_form')) {
                            $('edit_item_form').innerHTML = '';
                        }
                    } else {
    //                    document.getElementById('add_tab_chart').style.display='none';
                        $_('#add_tab_chart').fadeOut(20);
                    }
                }
            }

            function editDashboard()
            {
                if ($('edit_tab')) {
                    if (document.getElementById('edit_tab').style.display == 'none') {
    //                    document.getElementById('edit_tab').style.display='block';
                        $_('#edit_tab').fadeIn(20);
                        if ($('add_tab_chart')) {
                            if (document.getElementById('add_tab_chart').style.display == 'block'
                                    || document.getElementById('add_tab_chart').style.display == '') {
    //                            document.getElementById('add_tab_chart').style.display='none';
                                $_('#add_tab_chart').fadeOut(20);
                            }
                        }
                        if ($('add_tab')) {
                            if (document.getElementById('add_tab').style.display == 'block'
                                    || document.getElementById('add_tab').style.display == '') {
    //                            document.getElementById('add_tab').style.display='none';
                                $_('#add_tab').fadeOut(20);
                            }
                        }
                        if ($('edit_item_form')) {
                            $('edit_item_form').innerHTML = '';
                        }
                    } else {
    //                    document.getElementById('edit_tab').style.display='none';
                        $_('#edit_tab').fadeOut(20);
                    }
                }
            }
        </script>
    </div>
    <div class="clear"></div>
    <!-- add new dashboard form -->
    <div class="form-dropdown screen" id="add_tab" style="display:none;">
        <form method="post" id="add_tab_form" action="<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/savetab') ?>">
            <input type="hidden" name="form_key" value="<?php echo $this->getFormKey() ?>" />
            <div class="field-table">
                <div class="field-row">
                    <label style="width:210px;"></label>
                    <h3><?php echo $this->__('New Dashboard Information') ?></h3>
                </div>
                <div class="field-row">
                    <label for="DashboardName"><?php echo $this->__('Dashboard name') ?>&nbsp;<span class="required">*</span></label>
                    <div>
                        <input class="required-entry" type="text" value="" style="width:410px; margin-bottom:3px;" name="dashboard_name" maxlength="50" id="dashboard_name" />
                        <div style="display:none;padding-top:1px" class="validation-advice" id="advice-required-entry-add-dashboard-name"><?php echo $this->__('This is a required field.') ?></div>
                    </div>
                </div>            
                <div class="submit-row">
                    <label></label>
                    <div>
                        <button type="button" onclick="submitAddTabForm(this);" style="width:80px;height:32px;float:left; margin-right: 14px;" class="" value="Add">
                            <span><?php echo $this->__('Add') ?></span>
                        </button>
                        <a class="button-grey cancel" onclick="addDashboard();
                                return false;"><?php echo $this->__('Cancel') ?></a>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                function submitAddTabForm(element) {
                    if (!$('dashboard_name') || !$('dashboard_name').value || $('dashboard_name').value == '' || $('dashboard_name').value == '') {
                        $('advice-required-entry-add-dashboard-name').style.display = 'block';
                    } else {
                        if ($('advice-required-entry-add-dashboard-name').style.display == 'block') {
                            $('advice-required-entry-add-dashboard-name').style.display = 'none';
                        }
                        element.addClassName('button-grey');
                        element.disable();
                        $('add_tab_form').submit();
                    }
                }
            </script>
        </form>
    </div>
    <!-- end dashboards tab -->

    <!-- add new chart -->
    <div class="form-dropdown screen" id="add_tab_chart" style="display:none;">
        <form method="post" id="add_chart_form" action="<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/savechart', array('tab_id' => $tabId)) ?>">        
            <input type="hidden" name="form_key" value="<?php echo $this->getFormKey() ?>" />
            <div class="field-table" style="background-color: #efefef;">
                <div style="padding-left:100px;">
                    <ul class="field-row">
                        <label style="width:210px;font-size: 15px;"></label>
                        <h3><?php echo $this->__('New Chart Information') ?></h3>
                    </ul>
                    <br/>
                    <ul class="field-row clear">
                        <li>
                            <label for="chartName" style="font-size: 15px;"><?php echo $this->__('Chart Name') ?>&nbsp;<span class="required">*</span></label>
                        </li>
                        <li>
                            <input class="required-entry input-text required-entry" type="text" value="" style="width:410px;" name="chart_name" maxlength="50" id="chart_name" placeholder="<?php echo $this->__('50 characters max') ?>" />
                        </li>
                    </ul>          
                    <br/>
                    <ul class="field-row clear">
                        <li>
                            <label for="chartName" style="font-size: 15px;"><?php echo $this->__('Report Type') ?>&nbsp;<span class="required">*</span></label>
                        </li>                
                        <li>
                            <select name="group_type" id="group_type" onchange="return changeSelectGroupType(this);" class="required-entry required-entry select">
                                <?php $groupTypes = Mage::helper('inventorydashboard')->getGroupType(); ?>
                                <!--<option value=""><?php // echo $this->__('Please select a group type')    ?></option>-->
                                <?php if ($groupTypes): ?>
                                    <?php foreach ($groupTypes as $groupType): ?>
                                        <option value="<?php echo $groupType['type'] ?>" ><?php echo $this->__($groupType['title']) ?></option>
                                    <?php endforeach; ?>
                                <?php endif ?>
                            </select>
                        </li>
                    </ul>
                    <ul class="field-row clear">
                        <li>
                            <!--<br/><br/>-->
                            <select name="sales_report" id="sales_report" onchange="changeSalesChartType();" class="required-entry required-entry select" style="display:">
                                <?php $reportTypes = Mage::helper('inventorydashboard')->getReportType('sales'); ?>
                                <!--<option value=""><?php // echo $this->__('Please select')     ?></option>-->
                                <?php if ($reportTypes): ?>
                                    <?php $option_selected = 1; ?>
                                    <?php foreach ($reportTypes as $reportType): ?>
                                        <option value="<?php echo $reportType['report_code'] ?>" <?php if ($option_selected == 1) echo 'selected' ?>><?php echo $this->__($reportType['name']) ?></option>
                                        <?php $option_selected++ ?>
                                        <?php
                                    endforeach;
                                    unset($option_selected);
                                    ?>
                                <?php endif ?>
                            </select>
                            <select name="warehouse_report" id="warehouse_report" onchange="changeWarehouseChartType();" class="" style="display:none">
                                <?php $reportTypes = Mage::helper('inventorydashboard')->getReportType('warehouse'); ?>
                                <!--<option value=""><?php // echo $this->__('Please select')  ?></option>-->
                                <?php if ($reportTypes): ?>
                                    <?php ?>
                                    <?php foreach ($reportTypes as $reportType): ?>
                                        <option value="<?php echo $reportType['report_code'] ?>"><?php echo $this->__($reportType['name']) ?></option>
                                    <?php endforeach; ?>
                                <?php endif ?>
                            </select>
                            <select name="product_report" id="product_report" onchange="changeProductChartType();" class="" style="display:none">
                                <?php $reportTypes = Mage::helper('inventorydashboard')->getReportType('product'); ?>
                                <!--<option value=""><?php // echo $this->__('Please select')  ?></option>-->
                                <?php if ($reportTypes): ?>
                                    <?php foreach ($reportTypes as $reportType): ?>
                                        <option value="<?php echo $reportType['report_code'] ?>"><?php echo $this->__($reportType['name']) ?></option>
                                    <?php endforeach; ?>
                                <?php endif ?>
                            </select>
                            <select name="supplier_report" id="supplier_report" onchange="changeSupplierChartType();" class="" style="display:none">
                                <?php $reportTypes = Mage::helper('inventorydashboard')->getReportType('supplier'); ?>
                                <!--<option value=""><?php // echo $this->__('Please select')  ?></option>-->
                                <?php if ($reportTypes): ?>
                                    <?php foreach ($reportTypes as $reportType): ?>
                                        <option value="<?php echo $reportType['report_code'] ?>"><?php echo $this->__($reportType['name']) ?></option>
                                    <?php endforeach; ?>
                                <?php endif ?>
                            </select>
                            <select name="report_type" id="report_type" onchange="changeSelectChartType();" class="" style="display:none">
                                <?php $reportTypes = Mage::helper('inventorydashboard')->getReportType('unknown'); ?>
                                <!--<option value=""><?php // echo $this->__('Please select')  ?></option>-->
                                <?php if ($reportTypes): ?>
                                    <?php foreach ($reportTypes as $reportType): ?>
                                        <option value="<?php echo $reportType['report_code'] ?>"><?php echo $this->__($reportType['name']) ?></option>
                                    <?php endforeach; ?>
                                <?php endif ?>
                            </select>

                        </li>
                    </ul>
                    <ul class="field-row clear">
                        <li>
                            <select name="attribute_sales_report" id="attribute_sales_report" onchange="" class="" style="display:none">
                                <?php
                                $report = Mage::getModel('inventoryreports/reporttype');
                                $attributes = $report->getOrderAttributeOptions();
                                ?>
                                <!--<option value=""><?php // echo $this->__('Please select an Attribute')  ?></option>-->
                                <?php if ($attributes): ?>
                                    <?php foreach ($attributes as $key => $attribute): ?>
                                        <option value="<?php echo $key ?>"><?php echo $this->__($attribute) ?></option>
                                    <?php endforeach; ?>
                                <?php endif ?>
                            </select>
                        </li>
                    </ul>
                    <br/>
                    <ul class="field-row clear">
                        <li>
                            <label for="chartName" style="font-size: 15px;"><?php echo $this->__('Chart Type') ?>&nbsp;<span class="required">*</span></label>
                        </li>
                        <li>
                            <ul id="select_chart_type">
                                <?php echo $this->__('Please select a report type first.') ?>
                            </ul>                    
                        </li>
                        <div id="default_chart_type">
                            <li>
                                <?php echo Mage::helper('inventorydashboard')->getDefaultChartType(); ?>
                            </li>
                        </div>
                    </ul>        
                    <br/>
                    <ul class="submit-row clear">
                        <label></label>
                        <li>
                            <button type="button" onclick="submitAddChartForm();" style="width:80px;height:32px;float:left; margin-right: 14px;" class="" value="Add">
                                <span><?php echo $this->__('Add') ?></span>
                            </button>
                            <a class="button-grey cancel" onclick="addDashboardChart();
                                    return false;"><?php echo $this->__('Cancel') ?></a>
                        </li>
                    </ul>
                    <script type="text/javascript">
                        function changeSelectGroupType(id) {
                            if (id.value == "sales") {
                                $('sales_report').style.display = "inline-block";
                            }
                            else {
                                $("sales_report").style.display = "none";
                                $("sales_report").className = "";
                            }
                            if (id.value == 'warehouse') {
                                $("warehouse_report").style.display = "inline-block";
                                $("warehouse_report").className = "required-entry required-entry select";
                                $("attribute_sales_report").style.display = "none";
                                $("attribute_sales_report").className = "";
                            }
                            else {
                                $("warehouse_report").style.display = "none";
                                $("warehouse_report").className = "";
                            }
                            if (id.value == 'product') {
                                $("product_report").style.display = "inline-block";
                                $("product_report").className = "required-entry required-entry select";
                                $("attribute_sales_report").style.display = "none";
                                $("attribute_sales_report").className = "";
                            }
                            else {
                                $("product_report").style.display = "none";
                                $("product_report").className = "";
                            }
                            if (id.value == 'supplier') {
                                $("supplier_report").style.display = "inline-block";
                                $("supplier_report").className = "required-entry required-entry select";
                                $("attribute_sales_report").style.display = "none";
                                $("attribute_sales_report").className = "";
                            }
                            else {
                                $("supplier_report").style.display = "none";
                                $("supplier_report").className = "";
                            }
                            if (id.value == 'unknown') {
                                $("report_type").style.display = "inline-block";
                                $("report_type").className = "required-entry required-entry select";
                                $("attribute_sales_report").style.display = "none";
                                $("attribute_sales_report").className = "";
                            }
                            else {
                                $("report_type").style.display = "none";
                                $("report_type").className = "";
                            }
                        }

                        function changeSelectChartType() {
                            if ($("report_type") && $("report_type").value) {
                                $("default_chart_type").style.display = "none";
                                $("default_chart_type").checked = false;
                                var reportType = $('report_type').value;
                                var changeSelectChartTypeUrl = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/changecharttype', array('_secure' => true)) ?>';
                                changeSelectChartTypeUrl += 'report_code/' + reportType;
                                new Ajax.Request(changeSelectChartTypeUrl, {
                                    method: 'get',
                                    parameters: '',
                                    onFailure: '',
                                    onSuccess: function (transport) {
                                        if (transport.status == 200) {
                                            var stringre = transport.responseText;
                                            if ($('select_chart_type'))
                                                $('select_chart_type').innerHTML = stringre;
                                        }
                                    }
                                });
                            }
                        }
                        function changeSalesChartType() {
                            if ($("sales_report") && $("sales_report").value) {
                                $("default_chart_type").style.display = "none";
                                $("default_chart_type").checked = false;
                                if ($('sales_report').value == 'order_attribute') {
                                    $('attribute_sales_report').style.display = "inline-block";
                                    $('attribute_sales_report').className = "required-entry required-entry select";
                                }
                                else {
                                    $('attribute_sales_report').style.display = "none";
                                    $("attribute_sales_report").className = "";
                                }
                                var reportType = $('sales_report').value;
                                var changeSelectChartTypeUrl = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/changecharttype', array('_secure' => true)) ?>';
                                changeSelectChartTypeUrl += 'report_code/' + reportType;
                                new Ajax.Request(changeSelectChartTypeUrl, {
                                    method: 'get',
                                    parameters: '',
                                    onFailure: '',
                                    onSuccess: function (transport) {
                                        if (transport.status == 200) {
                                            var stringre = transport.responseText;
                                            if ($('select_chart_type'))
                                                $('select_chart_type').innerHTML = stringre;
                                        }
                                    }
                                });
                            }
                        }
                        function changeWarehouseChartType() {
                            if ($("warehouse_report") && $("warehouse_report").value) {
                                $("default_chart_type").style.display = "none";
                                $("default_chart_type").checked = false;
                                var reportType = $('warehouse_report').value;
                                var changeSelectChartTypeUrl = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/changecharttype', array('_secure' => true)) ?>';
                                changeSelectChartTypeUrl += 'report_code/' + reportType;
                                new Ajax.Request(changeSelectChartTypeUrl, {
                                    method: 'get',
                                    parameters: '',
                                    onFailure: '',
                                    onSuccess: function (transport) {
                                        if (transport.status == 200) {
                                            var stringre = transport.responseText;
                                            if ($('select_chart_type'))
                                                $('select_chart_type').innerHTML = stringre;
                                        }
                                    }
                                });
                            }
                        }
                        function changeProductChartType() {
                            if ($("product_report") && $("product_report").value) {
                                $("default_chart_type").style.display = "none";
                                $("default_chart_type").checked = false;
                                var reportType = $('product_report').value;
                                var changeSelectChartTypeUrl = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/changecharttype', array('_secure' => true)) ?>';
                                changeSelectChartTypeUrl += 'report_code/' + reportType;
                                new Ajax.Request(changeSelectChartTypeUrl, {
                                    method: 'get',
                                    parameters: '',
                                    onFailure: '',
                                    onSuccess: function (transport) {
                                        if (transport.status == 200) {
                                            var stringre = transport.responseText;
                                            if ($('select_chart_type'))
                                                $('select_chart_type').innerHTML = stringre;
                                        }
                                    }
                                });
                            }
                        }
                        function changeSupplierChartType() {
                            if ($("supplier_report") && $("supplier_report").value) {
                                $("default_chart_type").style.display = "none";
                                $("default_chart_type").checked = false;
                                var reportType = $('supplier_report').value;
                                var changeSelectChartTypeUrl = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/changecharttype', array('_secure' => true)) ?>';
                                changeSelectChartTypeUrl += 'report_code/' + reportType;
                                new Ajax.Request(changeSelectChartTypeUrl, {
                                    method: 'get',
                                    parameters: '',
                                    onFailure: '',
                                    onSuccess: function (transport) {
                                        if (transport.status == 200) {
                                            var stringre = transport.responseText;
                                            if ($('select_chart_type'))
                                                $('select_chart_type').innerHTML = stringre;
                                        }
                                    }
                                });
                            }
                        }
    //                    changeSelectChartType();
                    </script>           
                </div>
            </div>
            <script type="text/javascript">
                function submitAddChartForm() {
                    var add_chart_form = new varienForm('add_chart_form', '');
                    if (add_chart_form.validate()) {
                        $('add_chart_form').submit();
                    } else {

                    }
                }
            </script>
        </form>
    </div>

    <!-- end new chart -->

    <!-- edit dashboard form -->    
    <?php if ($tabId): ?>    
        <?php $dashboardTab = Mage::getModel('inventorydashboard/tabs')->load($tabId) ?>    
        <?php if ($dashboardTab && $dashboardTab->getId()): ?>
            <div class="form-dropdown screen" id="edit_tab" style="display:none;">            
                <form method="post" id="edit_tab_form" action="<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/savetab', array('tab_id' => $tabId)) ?>">                
                    <input type="hidden" name="form_key" value="<?php echo $this->getFormKey() ?>" />
                    <div class="field-table">
                        <div class="field-row">
                            <label style="width:210px;"></label>
                            <h3><?php echo $this->__('Edit dashboard "%s"', $dashboardTab->getName()) ?></h3>
                        </div>
                        <div class="field-row">
                            <label for="DashboardName"><?php echo $this->__('Dashboard Name') ?>&nbsp;<span class="required">*</span></label>
                            <div>
                                <input type="text" value="<?php echo $dashboardTab->getName() ?>" style="width:410px;margin-bottom:3px;" name="dashboard_name" maxlength="50" id="edit_dashboard_name" />
                                <div style="display:none;padding-top:1px" class="validation-advice" id="advice-required-entry-edit-dashboard-name"><?php echo $this->__('This is a required field.') ?></div>
                            </div>
                        </div>            
                        <div class="submit-row">
                            <label></label>
                            <div>
                                <button type="button" onclick="submitEditTabForm();" style="width:80px;height:32px;float:left; margin-right: 14px;" class="" value="Add">
                                    <span><?php echo $this->__('Save') ?></span>
                                </button>
                                <a class="button-grey cancel" onclick="editDashboard();
                                        return false;"><?php echo $this->__('Cancel') ?></a>
                                <a onclick="deleteDashboard();
                                        return false;" style="clear:both;line-height:50px;display:block;width: 200px;" href="#" data-ajax-update="#" class="delete">
                                    [<?php echo $this->__('Delete this dashboard') ?>]
                                </a>
                            </div>
                        </div>
                    </div>
                    <script type="text/javascript">
                        function submitEditTabForm() {
                            if (!$('edit_dashboard_name') || !$('edit_dashboard_name').value || $('edit_dashboard_name').value == '' || $('edit_dashboard_name').value == '') {
                                $('advice-required-entry-edit-dashboard-name').style.display = 'block';
                            } else {
                                if ($('advice-required-entry-edit-dashboard-name').style.display == 'block') {
                                    $('advice-required-entry-edit-dashboard-name').style.display = 'none';
                                }
                                $('edit_tab_form').submit();
                            }
                        }

                        function deleteDashboard() {
                            var r = confirm('<?php echo $this->__('Are you sure you want to delete this dashboard?') ?>');
                            if (r == true) {
                                setLocation('<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/deletetab', array('tab_id' => $tabId)) ?>');
                            }
                        }
                    </script>
                </form>
            </div>
        <?php endif ?>
    <?php endif ?>
    <!-- end edit dashboard form -->


    <!-- end edit item form -->
    <div id="edit_item_form"></div>
    <!-- edit item form -->


    <!-- items show -->
    <div class="dash-content-area">
        <!-- column 1 -->
        <div class="column" style="width:49%" data-col="1">
            <div class="sortable  ui-sortable">       
                <?php
                $itemColumn1s = Mage::getModel('inventorydashboard/items')->getCollection()
                        ->addFieldToFilter('tab_id', $tabId)
                        ->addFieldToFilter('item_column', 1)
                        ->setOrder('item_row', 'ASC');
                $resource = Mage::getSingleton('core/resource');
                $readConnection = $resource->getConnection('read_write');
                $attribute_column1 = false;
                $attribute_column2 = false;
                $group_attributes = array('payment_method', 'shipping_method', 'status', 'tax_code');
                ?>
                <?php if (count($itemColumn1s->getSize())): ?>
                    <?php foreach ($itemColumn1s as $itemColumn1): ?>
                        <div id="data-view-id-<?php echo $itemColumn1->getId() ?>" class="inventory-view-item" data-view-id="<?php echo $itemColumn1->getId() ?>" data-view-type="" data-loaded="true">
                            <div id="ui-id-<?php echo $itemColumn1->getId() ?>" class="options move" title="<?php echo $this->__('Drag and drop the chart to change its position.') ?>">
                                <b><?php echo $itemColumn1->getName() ?></b>
                                <a href="#" onclick="deleteChart('<?php echo $itemColumn1->getId() ?>');
                                        return false;" title="<?php echo $this->__('Delete chart') ?>" class="edit screen" data-ajax-method="DELETE"  data-ajax-delete="true">
                                    <i class="sprite" style="background-position: 8px -3135px"></i>
                                </a>                            
                                <a href="#" onclick="editItem('<?php echo $itemColumn1->getId() ?>');
                                        return false;" title="<?php echo $this->__('Edit chart') ?>" class="edit screen">
                                    <i class="sprite" style="background-position: 7px -3102px"></i>
                                </a>                    
                            </div>
                            <?php
                            $sql = 'Select distinct(`type`) from ' . $resource->getTableName('erp_inventory_dashboard_report_type') . ' where `report_code` = \'' . $itemColumn1->getReportCode() . '\'';
                            if (in_array($itemColumn1->getReportCode(), $group_attributes, true)) {
                                $attribute_column1 = true;
                                $sql = 'Select distinct(`type`) from ' . $resource->getTableName('erp_inventory_dashboard_report_type') . ' where `report_code` = "order_attribute"';
                            }
                            $results = $readConnection->fetchAll($sql);
                            $type = $results[0]['type'];
                            ?>
                            <?php
                            if ($attribute_column1) {
                                echo $this->getLayout()->createBlock('adminhtml/template')->setIdBox($itemColumn1->getId())->setReportCode('order_attribute')->setTemplate('inventorydashboard/chart/' . $itemColumn1->getChartCode() . '/' . $type . '_' . $itemColumn1->getReportCode() . '.phtml')->toHtml();
                            }
                            ?>
                            <?php
                            if (!$attribute_column1) {
                                echo $this->getLayout()->createBlock('adminhtml/template')->setIdBox($itemColumn1->getId())->setReportCode($itemColumn1->getReportCode())->setTemplate('inventorydashboard/chart/' . $itemColumn1->getChartCode() . '/' . $type . '_' . $itemColumn1->getReportCode() . '.phtml')->toHtml();
                            }
                            ?>
                            <?php $attribute_column1 = false; ?>
                        </div>
                    <?php endforeach ?>
                <?php endif ?>

            </div>
            <div class="clear"></div>
        </div>

        <!-- column 2 -->
        <div class="column" style="width:49%" data-col="2">
            <div class="sortable  ui-sortable">
                <?php
                $itemColumn2s = Mage::getModel('inventorydashboard/items')->getCollection()
                        ->addFieldToFilter('tab_id', $tabId)
                        ->addFieldToFilter('item_column', '2')
                        ->setOrder('item_row', 'ASC');
                ?>
                <?php if ($itemColumn2s->getSize()): ?>
                    <?php foreach ($itemColumn2s as $itemColumn2): ?>
                        <div id="data-view-id-<?php echo $itemColumn2->getId() ?>" class="inventory-view-item" data-view-id="<?php echo $itemColumn2->getId() ?>" data-view-type="" data-loaded="true">
                            <div id="ui-id-<?php echo $itemColumn2->getId() ?>" class="options move" title="<?php echo $this->__('Drag and drop the chart to change its position.') ?>">
                                <b><?php echo $itemColumn2->getName() ?></b>
                                <a href="#" onclick="deleteChart('<?php echo $itemColumn2->getId() ?>');
                                        return false;" title="<?php echo $this->__('Delete chart') ?>" class="edit screen" data-ajax-method="DELETE"  data-ajax-delete="true">
                                    <i class="sprite" style="background-position: 8px -3135px"></i>
                                </a>                            
                                <a href="#" onclick="editItem('<?php echo $itemColumn2->getId() ?>');
                                        return false;" title="<?php echo $this->__('Edit chart') ?>" class="edit screen">
                                    <i class="sprite" style="background-position: 7px -3102px"></i>
                                </a>                    
                            </div>      
                            <?php
                            $sql = 'Select distinct(`type`) from ' . $resource->getTableName('erp_inventory_dashboard_report_type') . ' where `report_code` = \'' . $itemColumn2->getReportCode() . '\'';
                            if (in_array($itemColumn2->getReportCode(), $group_attributes, true)) {
                                $attribute_column2 = true;
                                $sql = 'Select distinct(`type`) from ' . $resource->getTableName('erp_inventory_dashboard_report_type') . ' where `report_code` = "order_attribute"';
                            }
                            $results = $readConnection->fetchAll($sql);
                            $type = $results[0]['type'];
                            ?>
                            <?php
                            if ($attribute_column2) {
                                echo $this->getLayout()->createBlock('adminhtml/template')->setIdBox($itemColumn2->getId())->setReportCode('order_attribute')->setTemplate('inventorydashboard/chart/' . $itemColumn2->getChartCode() . '/' . $type . '_' . $itemColumn2->getReportCode() . '.phtml')->toHtml();
                            }
                            ?>
                            <?php
                            if (!$attribute_column2) {
                                echo $this->getLayout()->createBlock('adminhtml/template')->setIdBox($itemColumn2->getId())->setReportCode($itemColumn2->getReportCode())->setTemplate('inventorydashboard/chart/' . $itemColumn2->getChartCode() . '/' . $type . '_' . $itemColumn2->getReportCode() . '.phtml')->toHtml();
                            }
                            ?>                        
                            <?php $attribute_column2 = false; ?>
                        </div>
                    <?php endforeach ?>
                <?php endif ?>
            </div>
            <div class="clear"></div>
        </div>

    </div>
    <script type="text/javascript">
        function editItem(itemId) {
            if (itemId) {
                if ($('edit_item_form')) {
                    if ($('add_tab_chart')) {
                        if (document.getElementById('add_tab_chart').style.display == 'block'
                                || document.getElementById('add_tab_chart').style.display == '') {
                            $_('#add_tab_chart').fadeOut(20);
                        }
                    }
                    if ($('edit_tab')) {
                        if (document.getElementById('edit_tab').style.display == 'block'
                                || document.getElementById('edit_tab').style.display == '') {
    //                        document.getElementById('edit_tab').style.display='none'; 
                            $_('#edit_tab').fadeOut(20);
                        }
                    }
                    if ($('add_tab')) {
                        if (document.getElementById('add_tab').style.display == 'block'
                                || document.getElementById('add_tab').style.display == '') {
    //                        document.getElementById('add_tab').style.display='none';
                            $_('#add_tab').fadeOut(20);
                        }
                    }
                    var editItemTypeUrl = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/edititemform', array('_secure' => true)) ?>';
                    editItemTypeUrl += 'item_id/' + itemId;
                    new Ajax.Request(editItemTypeUrl, {
                        method: 'get',
                        parameters: '',
                        onFailure: '',
                        onSuccess: function (transport) {
                            if (transport.status == 200) {
                                var stringre = transport.responseText;
                                $('edit_item_form').innerHTML = stringre;
                                $_('#edit_item_form').fadeIn(20);
                            }
                        }
                    });
                }
            }
        }
    </script>

    <script type="text/javascript">
        function changeEditSelectChartType() {
            if ($('edit_report_type') && $('edit_report_type').value) {
                var reportType = $('edit_report_type').value;
                var changeSelectChartTypeUrl = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/changecharttype', array('_secure' => true)) ?>';
                changeSelectChartTypeUrl += 'report_code/' + reportType;
                new Ajax.Request(changeSelectChartTypeUrl, {
                    method: 'get',
                    parameters: '',
                    onFailure: '',
                    onSuccess: function (transport) {
                        if (transport.status == 200) {
                            var stringre = transport.responseText;
                            if ($('edit_select_chart_type'))
                                $('edit_select_chart_type').innerHTML = stringre;
                        }
                    }
                });
            }
        }

        function submitEditChartForm() {
            var edit_chart_form = new varienForm('edit_chart_form', '');
            if (edit_chart_form.validate()) {
                $('edit_chart_form').submit();
            }
        }

        function cancelEditChartForm() {
            if ($('edit_item_form'))
                $('edit_item_form').innerHTML = '';
        }

        function deleteChart(id) {

            var r = confirm('<?php echo $this->__('Are you sure you want to delete this chart?') ?>');
            if (r == true) {
                if ($('edit_item_form')) {
                    if (document.getElementById('edit_item_form').style.display == 'block'
                            || document.getElementById('edit_item_form').style.display == '') {
                        $_('#edit_item_form').fadeOut(20);
                    }
                }
                var deleteChartUrl = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/deleteitem', array('_secure' => true)) ?>';
                deleteChartUrl += 'item_id/' + id;
                new Ajax.Request(deleteChartUrl, {
                    method: 'get',
                    parameters: '',
                    onFailure: '',
                    onSuccess: function (transport) {
                        if ($('data-view-id-' + id))
                            $('data-view-id-' + id).style.display = 'none';

                        var messageDiv = document.getElementById('messages');
                        messageDiv.innerHTML = '';
                        var ulMessage = document.createElement('UL');
                        ulMessage.className = 'messages';
                        var liMessage = document.createElement('LI');
                        liMessage.className = 'success-msg';
                        var textnode = document.createTextNode('<?php echo "Chart was successfully deleted" ?>');
                        liMessage.appendChild(textnode);
                        ulMessage.appendChild(liMessage);
                        messageDiv.appendChild(ulMessage);
                        return false;
                    }
                });
            }
        }














        function changeSelectGroupTypeEdit(id) {
            if (id.value == "sales") {
                $('sales_report_edit').style.display = "inline-block";
            }
            else {
                $("sales_report_edit").style.display = "none";
                $("sales_report_edit").className = "";
            }
            if (id.value == 'warehouse') {
                $("warehouse_report_edit").style.display = "inline-block";
                $("warehouse_report_edit").className = "required-entry required-entry select";
                $("attribute_sales_report_edit").style.display = "none";
                $("attribute_sales_report_edit").className = "";
            }
            else {
                $("warehouse_report_edit").style.display = "none";
                $("warehouse_report_edit").className = "";
            }
            if (id.value == 'product') {
                $("product_report_edit").style.display = "inline-block";
                $("product_report_edit").className = "required-entry required-entry select";
                $("attribute_sales_report_edit").style.display = "none";
                $("attribute_sales_report_edit").className = "";
            }
            else {
                $("product_report_edit").style.display = "none";
                $("product_report_edit").className = "";
            }
            if (id.value == 'supplier') {
                $("supplier_report_edit").style.display = "inline-block";
                $("supplier_report_edit").className = "required-entry required-entry select";
                $("attribute_sales_report_edit").style.display = "none";
                $("attribute_sales_report_edit").className = "";
            }
            else {
                $("supplier_report_edit").style.display = "none";
                $("supplier_report_edit").className = "";
            }
            if (id.value == 'unknown') {
                $("report_type_edit").style.display = "inline-block";
                $("report_type_edit").className = "required-entry required-entry select";
                $("attribute_sales_report_edit").style.display = "none";
                $("attribute_sales_report_edit").className = "";
            }
            else {
                $("report_type_edit").style.display = "none";
                $("report_type_edit").className = "";
            }
        }

        function changeSelectChartTypeEdit() {
            if ($("report_type_edit") && $("report_type_edit").value) {
                $("default_chart_type_edit").style.display = "none";
                $("default_chart_type_edit").checked = false;
                var reportType = $('report_type_edit').value;
                var changeSelectChartTypeUrl = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/changecharttype', array('_secure' => true)) ?>';
                changeSelectChartTypeUrl += 'report_code/' + reportType;
                new Ajax.Request(changeSelectChartTypeUrl, {
                    method: 'get',
                    parameters: '',
                    onFailure: '',
                    onSuccess: function (transport) {
                        if (transport.status == 200) {
                            var stringre = transport.responseText;
    //                    if($('select_chart_type'))
    //                        $('select_chart_type').innerHTML = stringre;
                        }
                    }
                });
            }
        }
        function changeSalesChartTypeEdit() {
            if ($("sales_report_edit") && $("sales_report_edit").value) {
                $("default_chart_type_edit").style.display = "none";
                $("default_chart_type_edit").checked = false;
                if ($('sales_report_edit').value == 'order_attribute') {
                    $('attribute_sales_report_edit').style.display = "inline-block";
                    $('attribute_sales_report_edit').className = "required-entry required-entry select";
                }
                else {
                    $('attribute_sales_report_edit').style.display = "none";
                    $("attribute_sales_report_edit").className = "";
                }
                var reportType = $('sales_report_edit').value;
                var changeSelectChartTypeUrl = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/changecharttype', array('_secure' => true)) ?>';
                changeSelectChartTypeUrl += 'report_code/' + reportType;
                new Ajax.Request(changeSelectChartTypeUrl, {
                    method: 'get',
                    parameters: '',
                    onFailure: '',
                    onSuccess: function (transport) {
                        if (transport.status == 200) {
                            var stringre = transport.responseText;
    //                    if($('select_chart_type'))
    //                        $('select_chart_type').innerHTML = stringre;
                        }
                    }
                });
            }
        }
        function changeWarehouseChartTypeEdit() {
            if ($("warehouse_report_edit") && $("warehouse_report_edit").value) {
                $("default_chart_type_edit").style.display = "none";
                $("default_chart_type_edit").checked = false;
                var reportType = $('warehouse_report_edit').value;
                var changeSelectChartTypeUrl = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/changecharttype', array('_secure' => true)) ?>';
                changeSelectChartTypeUrl += 'report_code/' + reportType;
                new Ajax.Request(changeSelectChartTypeUrl, {
                    method: 'get',
                    parameters: '',
                    onFailure: '',
                    onSuccess: function (transport) {
                        if (transport.status == 200) {
                            var stringre = transport.responseText;
    //                    if($('select_chart_type'))
    //                        $('select_chart_type').innerHTML = stringre;
                        }
                    }
                });
            }
        }
        function changeProductChartTypeEdit() {
            if ($("product_report_edit") && $("product_report_edit").value) {
                $("default_chart_type_edit").style.display = "none";
                $("default_chart_type_edit").checked = false;
                var reportType = $('product_report_edit').value;
                var changeSelectChartTypeUrl = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/changecharttype', array('_secure' => true)) ?>';
                changeSelectChartTypeUrl += 'report_code/' + reportType;
                new Ajax.Request(changeSelectChartTypeUrl, {
                    method: 'get',
                    parameters: '',
                    onFailure: '',
                    onSuccess: function (transport) {
                        if (transport.status == 200) {
                            var stringre = transport.responseText;
    //                    if($('select_chart_type'))
    //                        $('select_chart_type').innerHTML = stringre;
                        }
                    }
                });
            }
        }
        function changeSupplierChartTypeEdit() {
            if ($("supplier_report_edit") && $("supplier_report_edit").value) {
                $("default_chart_type_edit").style.display = "none";
                $("default_chart_type_edit").checked = false;
                var reportType = $('supplier_report_edit').value;
                var changeSelectChartTypeUrl = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/changecharttype', array('_secure' => true)) ?>';
                changeSelectChartTypeUrl += 'report_code/' + reportType;
                new Ajax.Request(changeSelectChartTypeUrl, {
                    method: 'get',
                    parameters: '',
                    onFailure: '',
                    onSuccess: function (transport) {
                        if (transport.status == 200) {
                            var stringre = transport.responseText;
    //                    if($('select_chart_type'))
    //                        $('select_chart_type').innerHTML = stringre;
                        }
                    }
                });
            }
        }







    </script> 

    <script type="text/javascript" src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/_JSSettings.js"></script>
    <script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/js_002"></script>
    <script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/dashboards"></script>

    <script type="text/javascript">
        var saveViewPositions = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/saveviewposition') ?>';
        var saveTabPositions = '<?php echo $this->getUrl('inventorydashboardadmin/adminhtml_inventorydashboard/savetabposition') ?>';
        var form_key_dashboard = '<?php echo $this->getFormKey() ?>';
    </script>
    <script type="text/javascript">
        var $sd = new InventoryDashboard.Views.Dashboards();
        $sd.isShare = false;
        $sd.backgroundColour = '#808080';
        $sd.init();
    </script>
<?php endif; ?>