<?php $showDropship = false ?>
<?php foreach ($_items as $itemCheck): ?>
    <?php
    $supplierP = Mage::getModel('inventorypurchasing/supplier_product')
            ->getCollection()
            ->addFieldToFilter('product_id', $itemCheck->getProductId())
            ->getFirstItem();
    if ($supplierP->getId()) {
        $showDropship = true;
        break;
    }
    ?>
<?php endforeach ?>    
<?php if ($showDropship): ?>
    <div style="padding:10px;">
        <input type="checkbox" id="check_dropship" name="echeck_dropship" value="1" /> <?php echo $this->__('Use drop refund') ?>
    </div>
<?php else: ?>
    <div id="messages">
        <ul class="messages">
            <li class="notice-msg">
                <ul>
                    <li>
                        <span><?php echo Mage::helper('inventorydropship')->__('Drop shipping is not supported. No supplier available to fulfill this order!') ?></span>
                    </li>
                </ul>
            </li>
        </ul>
    </div>        
<?php endif ?>

<script type="text/javascript">
    Event.observe($('check_dropship'), 'click', function () {
        
        
            if ($('check_dropship').checked) {               
                
                appendColumn();
                
            } else {
                            
                deleteColumns();
                
            }
        
    });

    function submitDropShip(btn)
    {
        if (editForm.submit()) {
            disableElements('submit-button');
        }
    }

    // create DIV element and append to the table cell
    function createCell(cell, text, className, style) {
        var div = document.createElement('div'); // create text node       
        div.innerHTML = text;                    //ínert html to DIV
        div.setAttribute('class', className);        // set DIV class attribute
        div.setAttribute('className', className);    // set DIV class attribute for IE (?!)
        div.setAttribute('style', style);    // set style attribute
        cell.appendChild(div);                   // append DIV to the table cell        
    }

    function deleteColumns() {
        var tbl = document.getElementsByClassName('order-tables')[0], // table reference
                lastCol = tbl.rows[0].cells.length - 1, // set the last column index
                i, j;
        // delete cells with index greater then 0 (for each row)
        for (i = 0; i < tbl.rows.length; i++) {
                tbl.rows[i].deleteCell(tbl.rows[i].cells.length-1);
        }
    }

    // append column to the HTML table
    function appendColumn() {
        
        var tbl = document.getElementsByClassName('order-tables')[0], // table reference
                i = 0;
        $$('tr').each(function (el) {
            if (el.parentElement.parentElement.className == 'data order-tables')
            {
                var html = '';
                var style = '';
                if (i == 0) {

                    html = '<?php echo $this->__('Supplier') ?>';
                    style = 'font-weight:bold; width:110px;';
                    var itemHTML = tbl.rows[i].down('td h5 span');
                    var thHTML = tbl.rows[i].down('th.last');
                    
                    if (typeof tdHTML != 'undefined') {
                        tdHTML.removeClassName('last');
                    }
                    
                    createCell(tbl.rows[i].insertCell(tbl.rows[i].cells.length), html, 'col', style, i);
                    i = 1;
                } else {
                    if(el.className == 'border' || el.className == 'bundle' || el.className == 'border bundle'){
                        
                        var itemHTML = el.down('td h5.title span');
                        if(typeof itemHTML != 'undefined'){
                            style = 'width:110px;';
                            var tdHTML = el.down('td.last');

                            if (typeof tdHTML != 'undefined') {
                                tdHTML.removeClassName('last');
                            }

                            var text = itemHTML.id.split('_');
                            var sku = text[2];

                            html = sku;

                            var selectUrl = '<?php echo $this->getUrl('inventorydropshipadmin/adminhtml_inventorydropship/selectsupplier', array('_secure' => true)) ?>';
                            selectUrl += 'item_id/' + html;
                            new Ajax.Request(selectUrl, {
                                method: 'post',
                                parameters: '',
                                onFailure: '',
                                onSuccess: function (transport) {
                                    if (transport.status == 200) {
                                        var warehouseReturn = transport.responseText;
                                        createCell(el.insertCell(el.cells.length), warehouseReturn, 'col', style, i);
                                    }
                                }
                            });
                        }else{
                             createCell(el.insertCell(el.cells.length), '<td></td>', 'col', style, i);
                        }
                    }else{
                             createCell(el.insertCell(el.cells.length), '<td></td>', 'col', style, i);
                        }
                }
            }
        }
        );

    }
</script>