<?php
/**
 * BelVG LLC.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 *
 *******************************************************************
 * @category   Belvg
 * @package    Belvg_Sizes
 * @copyright  Copyright (c) 2010 - 2014 BelVG LLC. (http://www.belvg.com)
 * @license    http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 */
?>
<?php $helper = Mage::helper('sizes'); ?>
<?php $dems = $this->getDems(); ?>
<?php $params = $this->getRequest()->getParams() ?>
<form id="sizes_fields" enctype="multipart/form-data" method="post" action="<?php echo $this->getUrl() ?>sizes/front/result/">
<input style="display:none" value="<?php echo $params['product_id'] ?>" type="text" name="product_id">
        <h1>
        <?php echo $this->__($this->getCategoryLabel()) ?>
            <!--<button class="button" title="Calculate Size" type="button" id="sizes_calculate">
                <span>
                    <span><?php echo $this->__('Calculate your size') ?></span>
                </span>
            </button>-->
        </h1>
<?php foreach ($dems as $key=>$dem): ?>
        <div class="sizes_dem_container">
            <table class="sizes_dem">
            <tbody>
            <tr>
            <td style="width:50%" class="sizes_dem_label">
                <label for="dem_<?php echo $key ?>"><?php echo $this->__($dem['label']) ?></label>
            </td>
            <td style="width:50%" class="sizes_dem_input">
                <input class="dems" id="dem_<?php echo $key ?>" class="required-digits required-entry" type="text" name="sizes[<?php echo $dem['dem_id'] ?>]" readonly="readonly">
                <?php echo $this->__($helper->getUnitSizes()) ?>
            </td>
            </tr>
            <tr>            
            <td style="width:100%" colspan="2">
                <div class="sizes_dem_slider">
                    <div id="dem_slider_<?php echo $key ?>"></div>
                </div>
                <div class="sizes_dem_helper">
                    <?php foreach($this->getRanges($dem['dem_id']) as $n=>$range): ?>
                    <div class="sizes_dem_range<?php echo ($n == 0)?' first':''; ?>" style="width:<?php echo $range ?>%;float:left;"><?php echo $n ?></div>
                    <?php endforeach; ?>
                </div>
            </td>
            </tr>
            </tbody>
            </table>
            <script type="text/javascript">
                <?php $limits = $this->getLimits($dem['dem_id']); ?>
                jQblvg("#dem_slider_<?php echo $key ?>" ).slider({
                    range: "min",
                    value: <?php if (isset($params['sizes'][$dem['dem_id']])) echo $params['sizes'][$dem['dem_id']]; else echo $helper->getStoredValue($dem['dem_id'], $limits); ?>,
                    min: <?php echo $limits['min'] ?>,
                    max: <?php echo $limits['max'] ?>,
                    step: <?php echo $limits['step'] ?>,
                    slide: function(event, ui) {
                        jQblvg("#dem_<?php echo $key ?>").val(ui.value);
                    }
                });
                jQblvg("#dem_<?php echo $key ?>").val(jQblvg("#dem_slider_<?php echo $key ?>" ).slider("value"));            
            </script>
        </div>
<?php endforeach; ?>
        <div id="sizes_result_buttons">
            <button class="button" title="Calculate Size" type="button" id="sizes_calculate">
                <span>
                    <span><?php echo $this->__('Calculate your size') ?></span>
                </span>
            </button>
        </div>
</form>
<div id="sizes-image">
<img src="<?php echo $this->getCatImageUrl() ?>"/>
</div>