<?php $showDropship = false ?>
<?php foreach ($_items as $itemCheck): ?>
    <?php
    $supplierP = Mage::getModel('inventorypurchasing/supplier_product')
            ->getCollection()
            ->addFieldToFilter('product_id', $itemCheck->getProductId())
            ->getFirstItem();
    if ($supplierP->getId()) {
        $showDropship = true;
        break;
    }
    ?>
<?php endforeach ?>    
<?php if ($showDropship): ?>
    <div style="padding:10px;">
        <input type="checkbox" id="check_dropship" name="echeck_dropship" value="1" /> <?php echo $this->__('Use drop shipping') ?>
    </div>
<?php else: ?>
    <div id="messages">
        <ul class="messages">
            <li class="notice-msg">
                <ul>
                    <li>
                        <span><?php echo Mage::helper('inventorydropship')->__('Drop shipping is not supported. No supplier available to fulfill this order!') ?></span>
                    </li>
                </ul>
            </li>
        </ul>
    </div>        
<?php endif ?>

<script type="text/javascript">
    Event.observe($('check_dropship'), 'click', function () {
        if ($('select_warehouse_supplier')) {
            if ($('check_dropship').checked) {
                for(var i=0;i < $$('.barcode-column').length; i++){
                    $$('.barcode-column')[i].hide();
                }
                $('select_warehouse_supplier').innerHTML = '<?php echo $this->__('Supplier') ?>';
                enableElements('submit-button');
                $$('button').each(function (el) {
                    var el_class = el.className;
                    if (el_class.search('submit-button') != -1) {
                        $(el.id).onclick = function () {
                            submitDropShip(this);
                        }
                        $('edit_form').action = '<?php echo $this->getUrl('inventorydropshipadmin/adminhtml_inventorydropship/savedropship', array('order_id' => $this->getRequest()->getParam('order_id'))); ?>';
                        //                        $('edit_form').action = '<?php echo $this->getUrl('inventorydropshipadmin/adminhtml_inventorydropship/savedropship'); ?>';
                        $(el.id).innerHTML = "<span><?php echo $this->__('Submit Drop Shipment'); ?></span>";
                    }
                });
                $$('div').each(function (el) {
                
                    var div_id = el.id;
                    if ((div_id.search('show_select_warehouse_supplier') != -1) || (div_id.search('show_select_only_warehouse') != -1) || (div_id.search('show_select_only_supplier') != -1)) {
                        
                        var selectUrl = '<?php echo $this->getUrl('inventorydropshipadmin/adminhtml_inventorydropship/selectsupplier', array('_secure' => true)) ?>';
                        selectUrl += 'div_id/' + div_id;
                        new Ajax.Request(selectUrl, {
                            method: 'post',
                            parameters: '',
                            onFailure: '',
                            onSuccess: function (transport) {
                                if (transport.status == 200) {
                                    var supplierReturn = transport.responseText;
                                    if (supplierReturn == '1') {
                                        $(div_id).innerHTML = '';
                                    } else {
                                        $(div_id).innerHTML = supplierReturn;
                                    }
                                    var res = div_id.replace('show_select_warehouse_supplier_', '');
                                    if (res == div_id)
                                        var res = div_id.replace('show_select_only_warehouse_', '');
                                    if (res == div_id)
                                        var res = div_id.replace('show_select_only_supplier_', '');
                                    var res2 = res.split('_');
                                    var orderItemId = res2[0];
                                    if (!supplierReturn || supplierReturn == '' || supplierReturn == null) {
                                        if ($("span-shipment-dropship[items][" + orderItemId + "]"))
                                            $("span-shipment-dropship[items][" + orderItemId + "]").innerHTML = '<img src="<?php echo Mage::getDesign()->getSkinUrl('images/error_msg_icon.gif', array("_area" => "adminhtml")); ?> "/>';
                                        if ($("span-shipment[items][" + orderItemId + "]"))
                                            $("span-shipment[items][" + orderItemId + "]").innerHTML
                                                    = '<img src="<?php echo Mage::getDesign()->getSkinUrl('images/error_msg_icon.gif', array("_area" => "adminhtml")); ?> "/>\n\ ' +
                                                    '<input type="hidden" id="check-shipment[items][' + orderItemId + ']" value="0" />';
                                    } else {
                                        if (supplierReturn == '1') {
                                            if ($("span-shipment[items][" + orderItemId + "]"))
                                                $("span-shipment[items][" + orderItemId + "]").innerHTML = '';
                                        } else {
                                            if ($("span-shipment-dropship[items][" + orderItemId + "]"))
                                                $("span-shipment-dropship[items][" + orderItemId + "]").innerHTML
                                                        = '<img src="<?php echo Mage::getDesign()->getSkinUrl("images/success_msg_icon.gif", array("_area" => "adminhtml")); ?> " />' +
                                                        '<input type="hidden" id="check-shipment[items][' + orderItemId + ']" value="1" />';
                                            if ($("span-shipment[items][" + orderItemId + "]"))
                                                $("span-shipment[items][" + orderItemId + "]").innerHTML
                                                        = '<img src="<?php echo Mage::getDesign()->getSkinUrl("images/success_msg_icon.gif", array("_area" => "adminhtml")); ?> " />' +
                                                        '<input type="hidden" id="check-shipment[items][' + orderItemId + ']" value="1" />';
                                        }
                                    }
                                }
                            }
                        });
                    }
                });
            } else {
                for(var i=0;i < $$('.barcode-column').length; i++){
                    $$('.barcode-column')[i].show();
                }
                $('select_warehouse_supplier').innerHTML = '<?php echo $this->__('Warehouse') ?>';
                $$('button').each(function (el) {
                    var el_class = el.className;
                    if (el_class.search('submit-button') != -1) {
                        $(el.id).innerHTML = "<span><?php echo $this->__('Submit Shipment'); ?></span>";
                        $(el.id).onclick = function () {
                            submitShipment(this);
                        }
                        $('edit_form').action = '<?php echo $this->getUrl('admin/sales_order_shipment/save', array('order_id' => $this->getRequest()->getParam('order_id'))); ?>';
                    }
                });
                $$('div').each(function (el) {
                    var div_id = el.id;
                    if (div_id.search('show_select_warehouse_supplier') != -1 || (div_id.search('show_select_only_warehouse') != -1) || (div_id.search('show_select_only_supplier') != -1)) {
                        var selectUrl = '<?php echo $this->getUrl('inventorydropshipadmin/adminhtml_inventorydropship/selectwarehouse', array('_secure' => true)) ?>';
                        selectUrl += 'div_id/' + div_id;
                        new Ajax.Request(selectUrl, {
                            method: 'post',
                            parameters: '',
                            onFailure: '',
                            onSuccess: function (transport) {
                                if (transport.status == 200) {
                                    var warehouseReturn = transport.responseText;
                                    $(div_id).innerHTML = warehouseReturn;
                                    var res = div_id.replace('show_select_warehouse_supplier_', '');
                                    if (res == div_id)
                                        var res = div_id.replace('show_select_only_warehouse_', '');
                                    if (res == div_id)
                                        var res = div_id.replace('show_select_only_supplier_', '');
                                    if (div_id.search('show_select_only_warehouse') != -1) {
                                        var res2 = res.split('_');
                                        var orderItemId = res2[0];
                                        $("span-shipment-dropship[items][" + orderItemId + "]").innerHTML = '';
                                        $(div_id).innerHTML = '';
                                    }
                                    if (div_id.search('show_select_only_supplier') != -1) {
                                        var res2 = res.split('_');
                                        var orderItemId = res2[0];
                                        $("span-shipment-dropship[items][" + orderItemId + "]").innerHTML = '';
                                        $(div_id).innerHTML = '';
                                    }
                                    if (div_id.search('show_select_warehouse_supplier') != -1) {
                                        var res2 = res.split('_');
                                        var productId = res2[1];
                                        var orderid = '<?php echo Mage::app()->getRequest()->getParam('order_id'); ?>';
                                        var warehouseId = $("warehouse-shipment[items][" + res2[0] + "]").value;
                                        var checkparenturl = '<?php echo $this->getUrl('inventorydropshipadmin/adminhtml_inventorydropship/checkparent', array('_secure' => true)) ?>';
                                        var orderItemId = res2[0];
                                        checkparenturl += 'itemid/' + orderItemId;
                                        new Ajax.Request(checkparenturl, {
                                            method: 'post',
                                            parameters: '',
                                            onFailure: '',
                                            onSuccess: function (transport) {
                                                if (transport.status == 200) {
                                                    var parentIdReturn = transport.responseText;
                                                    var qtyToShip = $$('[name="shipment[items][' + parentIdReturn + ']"]')[0].value;
                                                    var orderItemId = res2[0];
                                                    checkStatusAvailableAOrderItemByEventDropShip(warehouseId, productId, qtyToShip, orderItemId, orderid, qtyToShip);
                                                }
                                            }
                                        });
                                    }
                                }
                            }
                        });
                    }
                });
            }
        } else {
        
            if ($('check_dropship').checked) {
                $$('button').each(function (el) {
                    var el_class = el.className;
                    if (el_class.search('submit-button') != -1) {
                        $(el.id).onclick = function () {
                            submitDropShip(this);
                        }
                        $('edit_form').action = '<?php echo $this->getUrl('inventorydropshipadmin/adminhtml_inventorydropship/savedropship', array('order_id' => $this->getRequest()->getParam('order_id'))); ?>';
                        $(el.id).innerHTML = "<span><?php echo $this->__('Submit Drop Shipment'); ?></span>";
                    }
                });
                
                appendColumn();
                
            } else {
            
                $$('button').each(function (el) {
                    var el_class = el.className;
                    if (el_class.search('submit-button') != -1) {
                        $(el.id).innerHTML = "<span><?php echo $this->__('Submit Shipment'); ?></span>";
                        $(el.id).onclick = function () {
                            submitShipment(this);
                        }
                        $('edit_form').action = '<?php echo $this->getUrl('adminhtml/sales_order_shipment/save', array('order_id' => $this->getRequest()->getParam('order_id'))); ?>';
                    }
                });
                
                deleteColumns();
                
            }
        }
    });

    function submitDropShip(btn)
    {
        if (editForm.submit()) {
            disableElements('submit-button');
        }
    }

    // create DIV element and append to the table cell
    function createCell(cell, text, className, style) {
        var div = document.createElement('div'); // create text node       
        div.innerHTML = text;                    //ínert html to DIV
        div.setAttribute('class', className);        // set DIV class attribute
        div.setAttribute('className', className);    // set DIV class attribute for IE (?!)
        div.setAttribute('style', style);    // set style attribute
        cell.appendChild(div);                   // append DIV to the table cell        
    }

    function deleteColumns() {
        var tbl = document.getElementsByClassName('order-tables')[0], // table reference
                lastCol = tbl.rows[0].cells.length - 1, // set the last column index
                i, j;
        // delete cells with index greater then 0 (for each row)
        for (i = 0; i < tbl.rows.length; i++) {
                tbl.rows[i].deleteCell(tbl.rows[i].cells.length-1);
        }
    }

    // append column to the HTML table
    function appendColumn() {
        
        var tbl = document.getElementsByClassName('order-tables')[0], // table reference
                i = 0;
        $$('tr').each(function (el) {
            if (el.parentElement.parentElement.className == 'data order-tables')
            {
                var html = '';
                var style = '';
                if (i == 0) {

                    html = '<?php echo $this->__('Supplier') ?>';
                    style = 'font-weight:bold; width:110px;';
                    var itemHTML = tbl.rows[i].down('td h5 span');
                    var thHTML = tbl.rows[i].down('th.last');
                    
                    if (typeof tdHTML != 'undefined') {
                        tdHTML.removeClassName('last');
                    }
                    
                    createCell(tbl.rows[i].insertCell(tbl.rows[i].cells.length), html, 'col', style, i);
                    i = 1;
                } else {
                    var itemHTML = el.down('td h5 span');
                    style = 'width:110px;';
                    var tdHTML = el.down('td.last');
                    
                    if (typeof tdHTML != 'undefined') {
                        tdHTML.removeClassName('last');
                    }
                    
                    var text = itemHTML.id.split('_');
                    var sku = text[2];

                    html = sku;

                    var selectUrl = '<?php echo $this->getUrl('inventorydropshipadmin/adminhtml_inventorydropship/selectsupplier', array('_secure' => true)) ?>';
                    selectUrl += 'item_id/' + html;
                    new Ajax.Request(selectUrl, {
                        method: 'post',
                        parameters: '',
                        onFailure: '',
                        onSuccess: function (transport) {
                            if (transport.status == 200) {
                                var warehouseReturn = transport.responseText;
                                createCell(el.insertCell(el.cells.length), warehouseReturn, 'col', style, i);
                            }
                        }
                    });
                }
            }
        }
        );

    }
</script>